#!/usr/bin/env python3
"""Shared manifest helpers for grill-adapter.

grill-adapter ships as Claude Code and Codex plugins, so the component inventory is declared
by each runtime's plugin manifest -- not by this file. What is left here is the one thing a
plugin cannot express: which host convention block to write into a target project's durable
instruction file.
"""

from __future__ import annotations

import json
from pathlib import Path


def load_manifest(root: Path) -> dict:
    return json.loads((root / "manifest.json").read_text(encoding="utf-8"))


def generated_marker(root: Path) -> str:
    return str(load_manifest(root).get("generatedMarker", "Generated by grill-adapter"))


def host_conventions(root: Path, runtime: str = "claude") -> dict[str, str]:
    """Workflow host name -> convention path for one agent runtime."""
    all_conventions = load_manifest(root).get("projectLevel", {}).get("hostConventions", {})
    runtime_conventions = all_conventions.get(runtime, {})
    return dict(runtime_conventions) if isinstance(runtime_conventions, dict) else {}


def removed_paths(root: Path) -> list[str]:
    return list(load_manifest(root).get("removedPaths", []))
