#!/usr/bin/env python3
"""Shared manifest helpers for grill-adapter.

grill-adapter is host-agnostic — it installs standalone skills/agents/hooks and never
targets a specific host plugin, so (unlike the Superpowers-coupled ancestor) there is no
host version floor to reason about here. This module just reads manifest.json.
"""

from __future__ import annotations

import json
from pathlib import Path


def load_manifest(root: Path) -> dict:
    return json.loads((root / "manifest.json").read_text(encoding="utf-8"))


def generated_marker(root: Path) -> str:
    return str(load_manifest(root).get("generatedMarker", "Generated by grill-adapter"))


def user_level_skills(root: Path) -> list[str]:
    return list(load_manifest(root).get("userLevel", {}).get("skills", []))


def user_level_agents(root: Path) -> list[str]:
    return list(load_manifest(root).get("userLevel", {}).get("agents", []))


def payload_dirs(root: Path) -> list[str]:
    """Directories copied verbatim into the user-level payload (scripts/, contracts/, hooks/, mcp/)."""
    return list(load_manifest(root).get("userLevel", {}).get("payload", []))


def removed_paths(root: Path) -> list[str]:
    return list(load_manifest(root).get("removedPaths", []))
