#!/usr/bin/env python3
"""Shared manifest helpers for grill-adapter.

grill-adapter ships as a Claude Code plugin, so the component inventory (skills, agents,
hooks, MCP) is declared by the plugin layout itself and discovered by Claude Code -- not by
this manifest. What is left here is the one thing the plugin cannot express: which host
convention block to write into a target project's CLAUDE.md.
"""

from __future__ import annotations

import json
from pathlib import Path


def load_manifest(root: Path) -> dict:
    return json.loads((root / "manifest.json").read_text(encoding="utf-8"))


def generated_marker(root: Path) -> str:
    return str(load_manifest(root).get("generatedMarker", "Generated by grill-adapter"))


def host_conventions(root: Path) -> dict[str, str]:
    """host name -> repo-relative path of its CLAUDE.md convention block."""
    return dict(load_manifest(root).get("projectLevel", {}).get("hostConventions", {}))


def removed_paths(root: Path) -> list[str]:
    return list(load_manifest(root).get("removedPaths", []))
