#!/usr/bin/env python3
"""Render thin host convention blocks from one runtime-neutral specification."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


RUNTIMES = {
    "claude": {
        "adapter_prefix": "/grill-adapter:",
        "file_name": "CLAUDE.md",
        "label": "Claude Code",
        "stage_prefix": "/",
    },
    "codex": {
        "adapter_prefix": "$grill-adapter:",
        "file_name": "AGENTS.md",
        "label": "Codex",
        "stage_prefix": "$mattpocock-skills:",
    },
}
HOSTS = ("grill", "plain")


def fail(message: str) -> None:
    raise ValueError(f"host convention specification error: {message}")


def as_string(value: object, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        fail(f"{name} must be a non-empty string")
    return value


def as_string_list(value: object, name: str) -> list[str]:
    if not isinstance(value, list) or not value:
        fail(f"{name} must be a non-empty list")
    return [as_string(item, f"{name} item") for item in value]


def load_spec(root: Path) -> dict[str, Any]:
    path = root / "contracts" / "host-conventions-v1.json"
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"missing {path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSON in {path}: {exc}") from exc

    if not isinstance(raw, dict) or raw.get("schemaVersion") != 1:
        fail("schemaVersion must be 1")
    common = raw.get("common")
    hosts = raw.get("hosts")
    if not isinstance(common, dict) or not isinstance(hosts, dict):
        fail("common and hosts must be objects")
    if set(hosts) != set(HOSTS):
        fail("hosts must define exactly grill and plain")

    as_string_list(common.get("invariants"), "common.invariants")
    as_string(common.get("stateBoundary"), "common.stateBoundary")
    for host in HOSTS:
        host_spec = hosts[host]
        if not isinstance(host_spec, dict):
            fail(f"hosts.{host} must be an object")
        as_string_list(host_spec.get("activation"), f"hosts.{host}.activation")
        as_string(host_spec.get("rosterBoundary"), f"hosts.{host}.rosterBoundary")
        for group in ("routes", "crossStage"):
            entries = host_spec.get(group)
            if not isinstance(entries, list) or not entries:
                fail(f"hosts.{host}.{group} must be a non-empty list")
            for index, entry in enumerate(entries):
                if not isinstance(entry, dict):
                    fail(f"hosts.{host}.{group}[{index}] must be an object")
                as_string(entry.get("moment"), f"hosts.{host}.{group}[{index}].moment")
                as_string_list(entry.get("skills"), f"hosts.{host}.{group}[{index}].skills")
                as_string(entry.get("purpose"), f"hosts.{host}.{group}[{index}].purpose")
    return raw


def adapter_skill(runtime: str, skill: str) -> str:
    return f"{RUNTIMES[runtime]['adapter_prefix']}{skill}"


def route_moment(host: str, runtime: str, moment: str, is_stage: bool) -> str:
    if host == "grill" and is_stage:
        return f"{RUNTIMES[runtime]['stage_prefix']}{moment}"
    return moment


def render_table(
    host: str, runtime: str, entries: list[dict[str, Any]], is_stage_table: bool
) -> list[str]:
    lines = ["| Workflow moment | Entry skill | Purpose |", "|---|---|---|"]
    for entry in entries:
        skills = ", ".join(adapter_skill(runtime, skill) for skill in entry["skills"])
        lines.append(
            f"| {route_moment(host, runtime, entry['moment'], is_stage_table)} | {skills} | {entry['purpose']} |"
        )
    return lines


def render_host(host: str, runtime: str, spec: dict[str, Any]) -> str:
    if host not in HOSTS:
        raise ValueError(f"unknown host: {host}")
    if runtime not in RUNTIMES:
        raise ValueError(f"unknown runtime: {runtime}")

    common = spec["common"]
    host_spec = spec["hosts"][host]
    label = RUNTIMES[runtime]["label"]
    lines = [
        f"<!-- grill-adapter:host:{host}:start -->",
        f"## grill-adapter stage router ({host} / {label})",
        "",
        "Generated by grill-adapter. This marker opts the project into a thin convention-only router.",
        "",
        "### Activation gate:",
    ]
    lines.extend(f"- {item}" for item in host_spec["activation"])
    lines.extend(("", "### Stage routing", ""))
    lines.extend(render_table(host, runtime, host_spec["routes"], is_stage_table=True))
    lines.extend(("", "### Cross-stage entries", ""))
    lines.extend(render_table(host, runtime, host_spec["crossStage"], is_stage_table=False))
    lines.extend(("", "### Boundaries", ""))
    lines.extend(f"- {item}" for item in common["invariants"])
    lines.append(f"- **Roster boundary:** {host_spec['rosterBoundary']}")
    lines.append(f"- **State boundary:** {common['stateBoundary']}")
    lines.extend(("", f"<!-- grill-adapter:host:{host}:end -->", ""))
    return "\n".join(lines)


def output_path(root: Path, host: str, runtime: str) -> Path:
    return root / "host-adapters" / host / str(RUNTIMES[runtime]["file_name"])


def sync(root: Path, write: bool) -> int:
    spec = load_spec(root)
    stale: list[Path] = []
    changed: list[Path] = []
    for host in HOSTS:
        for runtime in RUNTIMES:
            path = output_path(root, host, runtime)
            expected = render_host(host, runtime, spec)
            actual = path.read_text(encoding="utf-8") if path.is_file() else None
            if actual == expected:
                continue
            if not write:
                stale.append(path)
                continue
            path.write_text(expected, encoding="utf-8")
            changed.append(path)

    if stale:
        for path in stale:
            print(f"out of sync: {path}", file=sys.stderr)
        print("run scripts/render_host_conventions.py --write", file=sys.stderr)
        return 1
    for path in changed:
        print(f"rendered: {path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail when a derived block is stale")
    mode.add_argument("--write", action="store_true", help="write every derived block")
    args = parser.parse_args()
    try:
        return sync(args.root.resolve(), write=args.write)
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
