#!/usr/bin/env python3
"""Generated by grill-adapter.

Scaffold / convert project best-practice skill packs and stage content-addressed
Obsidian Skill Card candidates. This is the MECHANICAL layer only: it creates
skeleton files, carries over bundled assets, validates pack invariants, hashes
the complete pack, and appends structured registration candidates. It performs NO semantic judgement about
what a skill should contain or how to split it — the `scaffold-practice-skill`
agent decides that and authors the real content.

Commands:
  scaffold       Create a new pack skeleton under <project>/.claude/skills/<name>/.
  convert        Stage a layered pack from an existing skill (non-destructive),
                 carry over bundled files, and report source-content coverage gaps.
  stage-card     Validate and stage a pending registration in the feature journal.
  validate       Check pack invariants (+ optional --from coverage).

A skill pack has exactly one fixed file — `SKILL.md` (a thin router). Everything
else (implement.md / review.md / rules.md / examples.md / scripts/ / assets ...)
is an open set created only when asked. The goal of that single invariant is
progressive disclosure: SKILL.md stays small and points at sibling files loaded
on demand.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import uuid
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from wiki_common import repo_root, write_text_lf  # noqa: E402
from wiki_section import (  # noqa: E402
    KNOWN_BINDING_ROLES,
    list_section_ids,
    parse_binding_roles,
)
from wiki_candidate_journal import append_events, new_event  # noqa: E402

SKILLS_DIR_REL = Path(".claude") / "skills"
GENERATED_MARKER = "Generated by grill-adapter"
SKILL_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
SKILL_VERSION_RE = re.compile(
    r"^(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)"
    r"(?:-(?:0|[1-9][0-9]*|[A-Za-z-][0-9A-Za-z-]*)"
    r"(?:\.(?:0|[1-9][0-9]*|[A-Za-z-][0-9A-Za-z-]*))*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$")
FENCE_RE = re.compile(r"^(`{3,}|~{3,})")
BACKTICK_RE = re.compile(r"`([^`]+)`")

DEFAULT_DESCRIPTION = (
    "TODO(agent): 一句话说明该最佳实践 skill 的适用场景与触发词，供 Claude 按需加载时匹配。"
)
class ScaffoldError(Exception):
    pass


def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #
def resolve_project(args: argparse.Namespace) -> Path:
    # Anchor to the enclosing project root whether the path came from --project-root or CWD.
    start = Path(args.project_root).resolve() if getattr(args, "project_root", None) else Path.cwd()
    return repo_root(start)


def require_name(name: str | None) -> str:
    if not name:
        raise ScaffoldError("--name is required")
    if not SKILL_NAME_RE.match(name):
        raise ScaffoldError(
            f"invalid skill name {name!r}; use kebab-case [a-z0-9][a-z0-9-]*"
        )
    return name


def require_version(version: str | None) -> str:
    value = (version or "").strip()
    if not SKILL_VERSION_RE.fullmatch(value):
        raise ScaffoldError("--version must be a semantic major.minor.patch version")
    return value


def title_from_name(name: str) -> str:
    cleaned = name.replace("-", " ").replace("_", " ").strip()
    if cleaned.isascii():
        return cleaned.title()
    return cleaned


def parse_files(raw: str | None) -> list[str]:
    """Parse a comma-separated list of pack-relative paths (open set)."""
    if not raw:
        return []
    out: list[str] = []
    for item in raw.split(","):
        rel = item.strip().replace("\\", "/").strip("/")
        if not rel:
            continue
        if rel == "SKILL.md":
            # SKILL.md is the mandatory router, handled separately.
            continue
        parts = Path(rel).parts
        if any(part in ("..",) for part in parts) or rel.startswith("/"):
            raise ScaffoldError(f"unsafe pack-relative path: {item!r}")
        if rel not in out:
            out.append(rel)
    return out


def parse_roles(raw: str | None) -> list[str]:
    """Parse --roles into ordered, validated binding roles (default: every known role).

    A card binds to both implement and review by default. Pass a strict subset to scope it —
    e.g. ``review`` for a review-checklist skill so only reviewers get bound. Unknown tokens are
    rejected loudly so a typo (``reviewer``) never silently widens the card back to both roles.
    """
    if raw is None:
        return list(KNOWN_BINDING_ROLES)
    tokens = [token.strip().lower() for token in raw.split(",") if token.strip()]
    if not tokens:
        return list(KNOWN_BINDING_ROLES)
    unknown = sorted({token for token in tokens if token not in KNOWN_BINDING_ROLES})
    if unknown:
        raise ScaffoldError(
            f"invalid --roles value(s) {', '.join(unknown)}; allowed: {', '.join(KNOWN_BINDING_ROLES)}"
        )
    return parse_binding_roles(",".join(tokens))


def runtime_roles(raw: str | None) -> list[str]:
    role_map = {"implement": "implementer", "review": "reviewer"}
    return [role_map[role] for role in parse_roles(raw)]


def parse_triggers(raw: str | None) -> list[str]:
    triggers = list(dict.fromkeys(
        item.strip() for item in (raw or "").split(",") if item.strip()
    ))
    if not triggers:
        raise ScaffoldError("--triggers must contain at least one comma-separated trigger")
    return triggers


def skill_contract_hash(pack: Path) -> str:
    if not pack.is_dir() or not (pack / "SKILL.md").is_file():
        raise ScaffoldError(f"skill pack has no SKILL.md: {pack}")
    digest = hashlib.sha256()
    digest.update(b"grill-adapter.skill-pack-contract/v1\0")
    files = sorted(
        [
            (path.relative_to(pack).as_posix(), path)
            for path in pack.rglob("*")
            if path.is_file() or path.is_symlink()
        ],
        key=lambda item: item[0].encode("utf-8"),
    )
    for rel, path in files:
        if path.is_symlink():
            raise ScaffoldError(
                f"skill pack contract does not allow symlinks: {rel}"
            )
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
        digest.update(b"\0")
    return f"sha256:{digest.hexdigest()}"


def parse_frontmatter(text: str) -> dict[str, str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    fm: dict[str, str] = {}
    for line in match.group(1).splitlines():
        kv = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if kv:
            value = kv.group(2).strip().strip('"').strip("'")
            fm[kv.group(1)] = value
    return fm


def heading_texts(text: str) -> list[str]:
    """Markdown heading text in document order, skipping frontmatter + fences."""
    body = FRONTMATTER_RE.sub("", text, count=1)
    headings: list[str] = []
    in_fence = False
    fence = ""
    for line in body.splitlines():
        stripped = line.strip()
        fence_match = FENCE_RE.match(stripped)
        if fence_match:
            token = fence_match.group(1)
            if not in_fence:
                in_fence = True
                fence = token[0]
            elif stripped.startswith(fence * 3):
                in_fence = False
            continue
        if in_fence:
            continue
        heading = HEADING_RE.match(line)
        if heading:
            headings.append(heading.group(1).strip())
    return headings


def referenced_paths(text: str) -> list[str]:
    """Pack-relative paths the SKILL.md body points at (backtick code spans)."""
    refs: list[str] = []
    for raw in BACKTICK_RE.findall(text):
        candidate = raw.strip().replace("\\", "/").strip("/")
        if not candidate or candidate == "SKILL.md":
            continue
        looks_like_path = "/" in candidate or Path(candidate).suffix
        if looks_like_path and candidate not in refs:
            refs.append(candidate)
    return refs


def pack_files(pack: Path) -> list[str]:
    return [
        p.relative_to(pack).as_posix()
        for p in sorted(pack.rglob("*"))
        if p.is_file() and p.relative_to(pack).as_posix() != "SKILL.md"
    ]


def render_skill_md(name: str, description: str, version: str, extra: list[str]) -> str:
    if extra:
        files_block = "\n".join(f"- `{rel}`" for rel in extra)
    else:
        files_block = "- （暂无附加文件；按需新增 implement.md / review.md / rules.md / examples.md / scripts/ 等）"
    return f"""---
name: {name}
description: {description}
version: {version}
---

{GENERATED_MARKER} (scaffold skeleton — replace placeholders with real content).

# {title_from_name(name)}

<!-- TODO(agent): 适用场景与触发词；何时使用本 skill。 -->

## 模式
- implement：实现相关代码/文档时，按需加载实现细节。
- review：审查相关产物时，按需加载审查 checklist。

## 上下文优先级（保证脱离特定 host 也能独立使用）
1. 当前上下文已提供的项目规范。
2. 用户明确指定的规范文档。
3. 本地可发现的项目文档。
4. 本 skill 的通用流程。

缺少项目专属规范时先询问，不要假设项目规则。

## 包内文件（按需加载）
{files_block}
"""


def render_extra_stub(rel: str) -> str:
    suffix = Path(rel).suffix
    if suffix in (".md", ".markdown", ".mdx"):
        return f"# {title_from_name(Path(rel).stem)}\n\n<!-- TODO(agent): 内容 -->\n"
    if suffix == ".py":
        return "#!/usr/bin/env python3\n"
    if suffix == ".sh":
        return "#!/usr/bin/env bash\n"
    return ""


def sanitize_summary(text: str | None) -> str:
    """Normalize an authored Card summary to one safe line."""
    if not text:
        return ""
    cleaned = re.sub(r"\s+", " ", text).strip()
    return cleaned.replace('"', "'").replace(">", "").strip()


def emit(result: dict[str, Any], as_json: bool) -> None:
    if as_json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return
    command = result.get("command")
    if command in ("scaffold", "convert"):
        print(f"{command}: {result.get('skillName') or result.get('target')}")
        if result.get("created"):
            print("  created: " + ", ".join(result["created"]))
        if result.get("skipped"):
            print("  skipped: " + ", ".join(result["skipped"]))
        if result.get("carriedFiles"):
            print("  carried: " + ", ".join(result["carriedFiles"]))
        if result.get("uncovered"):
            print(f"  uncovered: {len(result['uncovered'])} item(s) not yet represented")
    elif command == "stage-card":
        print(f"stage-card: {result['skillName']} -> {result['journalPath']}")
        print(f"  discovery state: {result['discoveryState']}")
    elif command == "validate":
        print(f"validate: {'ok' if result['ok'] else 'FAILED'}")
        for err in result.get("errors", []):
            print(f"  error: {err}")
        for warn in result.get("warnings", []):
            print(f"  warning: {warn}")


# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #
def cmd_scaffold(args: argparse.Namespace) -> None:
    project = resolve_project(args)
    name = require_name(args.name)
    version = require_version(args.version)
    extra = parse_files(args.files)
    pack = project / SKILLS_DIR_REL / name
    pack.mkdir(parents=True, exist_ok=True)

    created: list[str] = []
    skipped: list[str] = []
    skill_md = pack / "SKILL.md"
    if skill_md.exists() and not args.force:
        skipped.append("SKILL.md")
    else:
        write_text_lf(
            skill_md,
            render_skill_md(name, args.description or DEFAULT_DESCRIPTION, version, extra),
        )
        created.append("SKILL.md")

    for rel in extra:
        dest = pack / rel
        if dest.exists() and not args.force:
            skipped.append(rel)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        write_text_lf(dest, render_extra_stub(rel))
        created.append(rel)

    emit(
        {
            "command": "scaffold",
            "skillName": name,
            "packDir": str(pack),
            "created": created,
            "skipped": skipped,
        },
        args.json,
    )


def resolve_source(src: Path) -> tuple[Path, Path]:
    src = src.resolve()
    if src.is_dir():
        skill_md = src / "SKILL.md"
        if not skill_md.is_file():
            raise ScaffoldError(f"source skill dir has no SKILL.md: {src}")
        return src, skill_md
    if src.is_file():
        if src.name != "SKILL.md":
            raise ScaffoldError(f"source must be a SKILL.md or its directory: {src}")
        return src.parent, src
    raise ScaffoldError(f"source not found: {src}")


def source_inventory(src_dir: Path, src_skill: Path) -> dict[str, Any]:
    text = src_skill.read_text(encoding="utf-8")
    bundled = [
        p.relative_to(src_dir).as_posix()
        for p in sorted(src_dir.rglob("*"))
        if p.is_file() and p.relative_to(src_dir).as_posix() != "SKILL.md"
    ]
    return {
        "headings": heading_texts(text),
        "sectionIds": list_section_ids(text),
        "bundledFiles": bundled,
    }


def coverage_gaps(inventory: dict[str, Any], target: Path) -> list[dict[str, str]]:
    target_md = "\n".join(
        p.read_text(encoding="utf-8")
        for p in sorted(target.rglob("*.md"))
        if p.is_file()
    )
    gaps: list[dict[str, str]] = []
    for heading in inventory["headings"]:
        if heading and heading not in target_md:
            gaps.append({"type": "heading", "value": heading})
    for rel in inventory["bundledFiles"]:
        if not (target / rel).exists():
            gaps.append({"type": "file", "value": rel})
    return gaps


def cmd_convert(args: argparse.Namespace) -> None:
    project = resolve_project(args)
    src_dir, src_skill = resolve_source(Path(args.src))
    fm = parse_frontmatter(src_skill.read_text(encoding="utf-8"))
    name = require_name(args.name or fm.get("name") or src_dir.name)
    version = require_version(args.version or fm.get("version") or "1.0.0")
    extra = parse_files(args.files)

    target = project / SKILLS_DIR_REL / name
    staging = False
    if target.resolve() == src_dir.resolve():
        target = project / SKILLS_DIR_REL / f"{name}.converted"
        staging = True
    target.mkdir(parents=True, exist_ok=True)

    # Carry over every bundled file (scripts/, assets, ...) except SKILL.md — never lose them.
    carried: list[str] = []
    for path in sorted(src_dir.rglob("*")):
        if path.is_dir():
            continue
        rel = path.relative_to(src_dir).as_posix()
        if rel == "SKILL.md":
            continue
        dest = target / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists() and dest.read_bytes() == path.read_bytes():
            continue
        shutil.copy2(path, dest)
        carried.append(rel)

    created: list[str] = []
    skipped: list[str] = []
    skill_md = target / "SKILL.md"
    if not skill_md.exists() or args.force:
        write_text_lf(
            skill_md,
            render_skill_md(
                name,
                fm.get("description") or DEFAULT_DESCRIPTION,
                version,
                extra,
            ),
        )
        created.append("SKILL.md")
    else:
        skipped.append("SKILL.md")
    for rel in extra:
        dest = target / rel
        if dest.exists() and not args.force:
            skipped.append(rel)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        write_text_lf(dest, render_extra_stub(rel))
        created.append(rel)

    inventory = source_inventory(src_dir, src_skill)
    uncovered = coverage_gaps(inventory, target)

    emit(
        {
            "command": "convert",
            "source": str(src_dir),
            "target": str(target),
            "skillName": name,
            "staging": staging,
            "replacedOriginal": False,
            "carriedFiles": carried,
            "created": created,
            "skipped": skipped,
            "inventory": inventory,
            "uncovered": uncovered,
        },
        args.json,
    )
    if args.strict and uncovered:
        raise ScaffoldError(
            f"coverage incomplete: {len(uncovered)} source item(s) not yet represented in target pack"
        )


def validate_pack(pack: Path) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    skill_md = pack / "SKILL.md"
    if not skill_md.is_file():
        return [f"SKILL.md missing under {pack}"], warnings

    body = skill_md.read_text(encoding="utf-8")
    frontmatter = parse_frontmatter(body)
    if not frontmatter.get("name"):
        errors.append("SKILL.md frontmatter missing name")
    if not frontmatter.get("description"):
        errors.append("SKILL.md frontmatter missing description")
    if not SKILL_VERSION_RE.fullmatch(frontmatter.get("version", "")):
        errors.append("SKILL.md frontmatter missing a valid version")
    referenced = referenced_paths(body)
    for rel in referenced:
        if not (pack / rel).exists():
            errors.append(f"SKILL.md references missing file: {rel}")
    for rel in pack_files(pack):
        if rel not in referenced:
            warnings.append(f"pack file not referenced from SKILL.md (won't load on demand): {rel}")
    for md in sorted(pack.rglob("*.md")):
        if md.name != "SKILL.md" and not md.read_text(encoding="utf-8").strip():
            errors.append(f"empty markdown file: {md.relative_to(pack).as_posix()}")
    return errors, warnings


def cmd_stage_card(args: argparse.Namespace) -> None:
    project = resolve_project(args)
    name = require_name(args.name)
    pack = project / SKILLS_DIR_REL / name
    errors, warnings = validate_pack(pack)
    if errors or warnings:
        raise ScaffoldError(
            "skill pack validation failed: " + "; ".join([*errors, *warnings])
        )
    skill_md = pack / "SKILL.md"
    frontmatter = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
    if frontmatter.get("name") != name:
        raise ScaffoldError(
            f"SKILL.md frontmatter name {frontmatter.get('name')!r} does not match {name!r}"
        )
    if not frontmatter.get("description"):
        raise ScaffoldError("SKILL.md frontmatter must include a trigger-rich description")
    version = require_version(args.version)
    if frontmatter.get("version") != version:
        raise ScaffoldError(
            f"--version {version!r} does not match SKILL.md frontmatter version "
            f"{frontmatter.get('version')!r}"
        )
    summary = sanitize_summary(args.summary)
    if not summary:
        raise ScaffoldError("--summary must be a non-empty single-line theme summary")
    roles = runtime_roles(args.roles)
    triggers = parse_triggers(args.triggers)
    contract_hash = skill_contract_hash(pack)
    registration = {
        "provider": args.provider,
        "name": name,
        "version": version,
        "contractHash": contract_hash,
        "roles": roles,
        "triggers": triggers,
        "summary": summary,
        "discoveryState": "pending",
    }
    identity = "\n".join(
        (
            args.provider,
            name,
            version,
            contract_hash,
            ",".join(roles),
            ",".join(triggers),
            summary,
        )
    )
    candidate_id = f"skill-card-{uuid.uuid5(uuid.NAMESPACE_URL, identity).hex}"
    journal = project / ".adapter" / "context" / f"{args.feature_slug}.wiki-candidates.jsonl"
    event = new_event(
        "candidate",
        args.feature_slug,
        candidateId=candidate_id,
        stage="capture",
        candidateType="skill_card",
        kind="skill_registration",
        claim=f"Register executable skill pack {name} at contract {contract_hash}.",
        why=summary,
        sourceRefs=[f".claude/skills/{name}/SKILL.md"],
        taskId=None,
        carveOut=False,
        origin="scaffold-practice-skill",
        skillRegistration=registration,
    )
    appended, skipped = append_events(
        journal,
        [event],
        args.feature_slug,
        allow_identical_candidates=True,
    )
    emit(
        {
            "command": "stage-card",
            "skillName": name,
            "journalPath": str(journal),
            "candidateId": candidate_id,
            "appended": appended,
            "skipped": skipped,
            "discoveryState": "pending",
            "skillRegistration": registration,
        },
        args.json,
    )


def cmd_validate(args: argparse.Namespace) -> None:
    project = resolve_project(args)

    if args.pack_dir:
        pack = Path(args.pack_dir).resolve()
    elif args.name:
        name = require_name(args.name)
        pack = project / SKILLS_DIR_REL / name
    else:
        raise ScaffoldError("validate requires --name or --pack-dir")

    errors, warnings = validate_pack(pack)

    if args.src:
        src_dir, src_skill = resolve_source(Path(args.src))
        for gap in coverage_gaps(source_inventory(src_dir, src_skill), pack):
            errors.append(f"coverage gap ({gap['type']}): {gap['value']}")

    ok = not errors
    emit(
        {"command": "validate", "ok": ok, "errors": errors, "warnings": warnings},
        args.json,
    )
    if not ok:
        sys.exit(1)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Scaffold / convert best-practice skill packs.")
    parser.add_argument("--project-root", default=None, help="Project root (default: discovered from CWD).")
    parser.add_argument("--json", action="store_true", help="Emit a JSON result object.")
    sub = parser.add_subparsers(dest="command", required=True)

    p_scaffold = sub.add_parser("scaffold", help="Create a new pack skeleton.")
    p_scaffold.add_argument("--name", required=True)
    p_scaffold.add_argument("--description", default=None)
    p_scaffold.add_argument("--version", default="1.0.0")
    p_scaffold.add_argument("--files", default=None, help="Comma-separated pack-relative paths (open set).")
    p_scaffold.add_argument("--force", action="store_true", help="Overwrite existing files.")
    p_scaffold.set_defaults(func=cmd_scaffold)

    p_convert = sub.add_parser("convert", help="Stage a layered pack from an existing skill (non-destructive).")
    p_convert.add_argument("--from", dest="src", required=True, help="Existing SKILL.md or its directory.")
    p_convert.add_argument("--name", default=None)
    p_convert.add_argument("--version", default=None)
    p_convert.add_argument("--files", default=None)
    p_convert.add_argument("--force", action="store_true")
    p_convert.add_argument("--strict", action="store_true", help="Fail if any source content is uncovered.")
    p_convert.set_defaults(func=cmd_convert)

    p_stage = sub.add_parser(
        "stage-card",
        help="Validate a pack and append a content-addressed Skill Card registration candidate.",
    )
    p_stage.add_argument("--name", required=True)
    p_stage.add_argument("--feature-slug", required=True)
    p_stage.add_argument(
        "--provider",
        choices=["claude-code-project"],
        default="claude-code-project",
    )
    p_stage.add_argument("--version", required=True)
    p_stage.add_argument("--roles", default=None)
    p_stage.add_argument("--triggers", required=True)
    p_stage.add_argument("--summary", required=True)
    p_stage.set_defaults(func=cmd_stage_card)

    p_validate = sub.add_parser("validate", help="Validate pack invariants and optional source coverage.")
    p_validate.add_argument("--name", default=None)
    p_validate.add_argument("--pack-dir", default=None)
    p_validate.add_argument("--from", dest="src", default=None, help="Optional source for coverage check.")
    p_validate.set_defaults(func=cmd_validate)

    return parser


def main(argv: list[str] | None = None) -> int:
    _configure_stdio()
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.func(args)
    except (ScaffoldError, PermissionError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
