#!/usr/bin/env python3
"""Generated by grill-adapter."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

from feature_context import (
    context_root,
    feature_context_dir,
    infer_project_root,
    is_feature_context_dir,
)
from wiki_context_render import (
    FingerprintError,
    ValidationError,
    _v6_task_notes,
    load_ticket_roster,
)
from wiki_task_snapshot import (
    SnapshotError,
    approval_path,
    evaluate_snapshot_freshness,
    file_digest,
    render_snapshot,
    safe_task_id,
    snapshot_path,
    validate_approval,
    validate_snapshot,
    write_approval,
    write_snapshot,
)
from wiki_session_state import SessionStateError, update_session_state


KIND = "grill-adapter.wiki-readiness"
SCHEMA_VERSION = 1
GENERATED_BY = "grill-adapter"
RESULT_KIND = "grill-adapter.wiki-readiness-result"
RESULT_SCHEMA_VERSION = 1
STATUS_DISPOSITIONS = {
    "ready": "materialized",
    "no-relevant": "none",
    "disabled": "none",
    "broken": "discarded",
}


class ReadinessError(Exception):
    pass


def _refresh_session_state(
    feature_directory: Path,
    *,
    task_id: str | None = None,
    next_command: str | None = None,
    readiness_status: str | None = None,
) -> None:
    """Keep the continuation hint best-effort; never make it an authority or a gate."""

    try:
        update_session_state(
            feature_directory,
            task_id=task_id,
            next_command=next_command,
            readiness_status=readiness_status,
        )
    except (OSError, SessionStateError, ValueError):
        pass


def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")


def _load_json(path: Path, label: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ReadinessError(f"Could not read {label} {path}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ReadinessError(f"Invalid JSON in {label} {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ReadinessError(f"{label} must be a JSON object")
    return value


def _write_json(path: Path, value: dict[str, Any]) -> None:
    text = json.dumps(value, ensure_ascii=False, indent=2) + "\n"
    _write_text(path, text)


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temp_name = handle.name
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        Path(temp_name).replace(path)
    finally:
        if temp_name:
            Path(temp_name).unlink(missing_ok=True)


def _required_text(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ReadinessError(f"{field} must be a non-empty string")
    return value


def _feature_slug(value: Any) -> str:
    slug = _required_text(value, "featureSlug").strip()
    if "/" in slug or "\\" in slug or slug in {".", ".."}:
        raise ReadinessError("featureSlug must not contain path separators")
    return slug


def _same_context_directory(reference: Path, candidate: Path, label: str) -> None:
    if reference.resolve().parent != candidate.resolve().parent:
        raise ReadinessError(f"{label} must be in the same feature context directory as the readiness receipt")


def _is_allowed_context_directory(directory: Path, project_root: Path) -> bool:
    root = context_root(project_root)
    resolved = directory.resolve()
    # The root is retained only for pre-directory legacy artifacts. New task artifacts
    # belong in one direct <feature-slug> child directory.
    return resolved == root or is_feature_context_dir(resolved, project_root)


def _safe_context_filename(value: Any, field: str) -> str:
    filename = _required_text(value, field)
    if Path(filename).name != filename or filename in {".", ".."}:
        raise ReadinessError(f"{field} must be a plain filename in the readiness receipt directory")
    return filename


def _roster_metadata(roster_path: Path) -> tuple[dict[str, Any], str, str, dict[str, dict[str, str]]]:
    raw = _load_json(roster_path, "ticket roster")
    feature_slug = _feature_slug(raw.get("featureSlug"))
    ticket_source = _required_text(raw.get("ticketSource"), "ticketSource").strip()
    tasks = load_ticket_roster(roster_path, feature_slug)
    return raw, feature_slug, ticket_source, tasks


def _write_single_task_roster(
    roster_path: Path,
    feature_slug: str,
    ticket_source: str,
    task_id: str,
    task_title: str,
    task_text: str,
) -> None:
    roster = {
        "featureSlug": _feature_slug(feature_slug),
        "ticketSource": ticket_source,
        "tickets": [
            {
                "taskId": _required_text(task_id, "taskId").strip(),
                "taskTitle": _required_text(task_title, "taskTitle").strip(),
                "text": _required_text(task_text, "text"),
            }
        ],
    }
    _write_json(roster_path, roster)


def prepare_issue(issue_json_path: Path, roster_path: Path, feature_slug: str) -> str:
    issue = _load_json(issue_json_path, "GitHub issue JSON")
    number = issue.get("number")
    if isinstance(number, bool) or not isinstance(number, (int, str)):
        raise ReadinessError("GitHub issue number must be a positive integer")
    task_id = str(number).strip()
    if not task_id.isdigit() or int(task_id) <= 0:
        raise ReadinessError("GitHub issue number must be a positive integer")
    _write_single_task_roster(
        roster_path,
        feature_slug,
        "github-issues",
        task_id,
        _required_text(issue.get("title"), "GitHub issue title"),
        _required_text(issue.get("body"), "GitHub issue body"),
    )
    _refresh_session_state(roster_path.parent, task_id=task_id)
    return f"prepared GitHub issue task {task_id} -> {roster_path}"


def prepare_manual(task_text_path: Path, roster_path: Path, feature_slug: str, task_title: str) -> str:
    try:
        task_text = task_text_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ReadinessError(f"Could not read manual task brief {task_text_path}: {exc}") from exc
    _write_single_task_roster(
        roster_path,
        feature_slug,
        "manual",
        "manual",
        task_title,
        task_text,
    )
    _refresh_session_state(roster_path.parent, task_id="manual")
    return f"prepared manual task -> {roster_path}"


def _wiki_provider_state(project_root: Path) -> str:
    """Classify whether late Carry can be attempted without touching the Wiki runtime."""

    settings_path = project_root / ".grill-adapter" / "settings.json"
    if not settings_path.is_file():
        return "disabled"
    try:
        payload = json.loads(settings_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return "broken"
    if not isinstance(payload, dict):
        return "broken"
    if "wiki" not in payload:
        return "disabled"
    wiki = payload.get("wiki")
    if not isinstance(wiki, dict):
        return "broken"
    provider = wiki.get("provider")
    if provider in {None, "", "disabled", "none"}:
        return "disabled"
    return "configured" if provider == "obsidian" else "broken"


def _validate_context(
    context_path: Path,
    roster_path: Path,
    project_root: Path | None = None,
) -> dict[str, Any]:
    renderer = Path(__file__).with_name("wiki_context_render.py")
    command = [
            sys.executable,
            str(renderer),
            str(context_path),
            "--validate-only",
            "--strict",
            "--execution-ready",
            "--ticket-roster",
            str(roster_path),
        ]
    if project_root is not None:
        command.extend(["--project-root", str(project_root)])
    result = subprocess.run(
        command,
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "unknown validation failure"
        raise ReadinessError(f"Wiki context is not execution-ready: {detail}")
    return _load_json(context_path, "wiki context")


def _run_context_command(command: list[str], label: str) -> str:
    try:
        result = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    except OSError as exc:
        raise ReadinessError(f"{label} could not start: {exc}") from exc
    if result.returncode != 0:
        # Never include stdout here: a failed renderer/fetcher may have emitted partial context.
        detail = result.stderr.strip() or f"exit code {result.returncode}; partial stdout discarded"
        raise ReadinessError(f"{label} failed: {detail}")
    return result.stdout


def _render_and_materialize_context(
    *,
    context_path: Path,
    task_id: str,
    role: str,
    project_root: Path,
    obsidian_wiki_cmd: str | None = None,
    ignore_snapshot: bool = False,
) -> tuple[str, str, list[dict[str, Any]]]:
    renderer = Path(__file__).with_name("wiki_context_render.py")
    materializer = Path(__file__).with_name("wiki_materialize_task.py")
    common_args = [
        str(context_path),
        "--task-id",
        task_id,
        "--role",
        role,
        "--strict",
        "--execution-ready",
    ]
    renderer_args = [*common_args, "--project-root", str(project_root)]

    rendered = _run_context_command(
        [sys.executable, str(renderer), *renderer_args],
        f"{role.capitalize()} Wiki task rendering",
    )
    manifest_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            dir=context_path.parent,
            prefix=f".{task_id}.{role}.freshness.",
            suffix=".json",
            delete=False,
        ) as handle:
            manifest_path = Path(handle.name)
        materialize_command = [
            sys.executable,
            str(materializer),
            *common_args,
            "--project-root",
            str(project_root),
            "--freshness-manifest",
            str(manifest_path),
        ]
        if obsidian_wiki_cmd:
            materialize_command.extend(["--obsidian-wiki-cmd", obsidian_wiki_cmd])
        if ignore_snapshot:
            materialize_command.append("--ignore-snapshot")
        materialized = _run_context_command(
            materialize_command,
            f"{role.capitalize()} Wiki materialization",
        )
        try:
            freshness_entries = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ReadinessError(
                f"could not read {role} Wiki freshness manifest: {exc}"
            ) from exc
        if not isinstance(freshness_entries, list):
            raise ReadinessError(f"{role} Wiki freshness manifest must be a list")
        return rendered, materialized, freshness_entries
    finally:
        if manifest_path is not None:
            manifest_path.unlink(missing_ok=True)


def _snapshot_paths(context_path: Path, task_id: str) -> tuple[Path, Path]:
    return (
        snapshot_path(context_path, task_id, "implementer"),
        snapshot_path(context_path, task_id, "reviewer"),
    )


def _load_role_snapshots(
    *,
    context_path: Path,
    context: dict[str, Any],
    feature_slug: str,
    ticket_source: str,
    task_id: str,
    task: dict[str, str],
    implement_digest: str | None = None,
    review_digest: str | None = None,
    now: datetime | None = None,
) -> tuple[tuple[Path, str, list[str]], tuple[Path, str, list[str]]]:
    implement_path, review_path = _snapshot_paths(context_path, task_id)
    if not implement_path.is_file() or not review_path.is_file():
        raise ReadinessError(
            f"task Wiki snapshots are incomplete; expected {implement_path.name} and {review_path.name}"
        )
    try:
        approval_file = approval_path(context_path, task_id)
        if not approval_file.is_file():
            raise SnapshotError(f"task Wiki approval manifest is missing: {approval_file.name}")
        approved_implement, approved_review = validate_approval(
            approval_file,
            context_path=context_path,
            context=context,
            task=task,
            task_id=task_id,
        )
        if implement_digest is not None and approved_implement != implement_digest:
            raise SnapshotError("receipt implementer snapshot digest differs from the approval manifest")
        if review_digest is not None and approved_review != review_digest:
            raise SnapshotError("receipt reviewer snapshot digest differs from the approval manifest")
        implement_metadata, implement_body = validate_snapshot(
            implement_path,
            context_path=context_path,
            feature_slug=feature_slug,
            ticket_source=ticket_source,
            task_id=task_id,
            task_title=task["title"],
            task_fingerprint=task["hash"],
            role="implementer",
            expected_digest=approved_implement,
        )
        review_metadata, review_body = validate_snapshot(
            review_path,
            context_path=context_path,
            feature_slug=feature_slug,
            ticket_source=ticket_source,
            task_id=task_id,
            task_title=task["title"],
            task_fingerprint=task["hash"],
            role="reviewer",
            expected_digest=approved_review,
        )
        implement_warnings = evaluate_snapshot_freshness(implement_metadata, now)
        review_warnings = evaluate_snapshot_freshness(review_metadata, now)
    except SnapshotError as exc:
        raise ReadinessError(f"task Wiki snapshot validation failed: {exc}") from exc
    return (
        (implement_path, implement_body, implement_warnings),
        (review_path, review_body, review_warnings),
    )


def _role_freshness_entries(
    context: dict[str, Any],
    task_id: str,
    role: str,
    materialized_entries: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    notes, skills = _v6_task_notes(context, task_id, role)
    entries: list[dict[str, Any]] = []
    seen: set[str] = set()
    for note in [*notes, *skills, *materialized_entries]:
        wiki_id = note.get("wikiId")
        if not isinstance(wiki_id, str) or wiki_id in seen:
            continue
        seen.add(wiki_id)
        entries.append(
            {
                "wikiId": wiki_id,
                "path": note.get("path"),
                "verifiedAt": note.get("verifiedAt"),
                "reviewAfter": note.get("reviewAfter"),
                "expiresAt": note.get("expiresAt"),
            }
        )
    return entries


def _prepare_role_snapshot_texts(
    *,
    context_path: Path,
    context: dict[str, Any],
    feature_slug: str,
    ticket_source: str,
    task_id: str,
    task: dict[str, str],
    project_root: Path,
    obsidian_wiki_cmd: str | None,
    origin: str,
) -> tuple[str, str]:
    _validate_context_identity(context, feature_slug, ticket_source, task_id)

    (
        rendered_implement,
        materialized_implement,
        implement_freshness,
    ) = _render_and_materialize_context(
        context_path=context_path,
        task_id=task_id,
        role="implementer",
        project_root=project_root,
        obsidian_wiki_cmd=obsidian_wiki_cmd,
        ignore_snapshot=True,
    )
    (
        rendered_review,
        materialized_review,
        review_freshness,
    ) = _render_and_materialize_context(
        context_path=context_path,
        task_id=task_id,
        role="reviewer",
        project_root=project_root,
        obsidian_wiki_cmd=obsidian_wiki_cmd,
        ignore_snapshot=True,
    )
    implement_text = render_snapshot(
        context=context,
        context_path=context_path,
        task=task,
        task_id=task_id,
        role="implementer",
        rendered=rendered_implement,
        materialized=materialized_implement,
        freshness_entries=_role_freshness_entries(
            context,
            task_id,
            "implementer",
            implement_freshness,
        ),
        origin=origin,
    )
    review_text = render_snapshot(
        context=context,
        context_path=context_path,
        task=task,
        task_id=task_id,
        role="reviewer",
        rendered=rendered_review,
        materialized=materialized_review,
        freshness_entries=_role_freshness_entries(
            context,
            task_id,
            "reviewer",
            review_freshness,
        ),
        origin=origin,
    )
    return implement_text, review_text


def _write_role_snapshots(
    *,
    context_path: Path,
    context: dict[str, Any],
    task: dict[str, str],
    task_id: str,
    implement_text: str,
    review_text: str,
) -> tuple[tuple[Path, str], tuple[Path, str]]:
    implement_path, review_path = _snapshot_paths(context_path, task_id)
    approval_file = approval_path(context_path, task_id)

    # Materialize the complete role pair and its approval manifest before replacing any existing
    # artifact. A compatibility freeze is allowed to replace an incomplete/legacy set, but a
    # renderer or filesystem failure must preserve the previous set byte-for-byte.
    with tempfile.TemporaryDirectory(
        dir=context_path.resolve().parent,
        prefix=f".{task_id}.wiki-readiness-",
    ) as staging:
        staging_dir = Path(staging)
        staged_implement = staging_dir / implement_path.name
        staged_review = staging_dir / review_path.name
        staged_approval = staging_dir / approval_file.name
        implement_digest = write_snapshot(staged_implement, implement_text)
        review_digest = write_snapshot(staged_review, review_text)
        write_approval(
            staged_approval,
            context_path=context_path,
            context=context,
            task=task,
            task_id=task_id,
            implement_digest=implement_digest,
            review_digest=review_digest,
        )
        _atomic_replace_files(
            [
                (staged_implement, implement_path),
                (staged_review, review_path),
                (staged_approval, approval_file),
            ]
        )
    return (implement_path, implement_digest), (review_path, review_digest)


def _atomic_replace_files(files: list[tuple[Path, Path]]) -> None:
    """Replace a related set of files together, restoring old files if a rename fails."""

    backups: list[tuple[Path, Path]] = []
    installed: list[Path] = []
    try:
        for _, target in files:
            if not target.exists():
                continue
            fd, backup_name = tempfile.mkstemp(
                dir=target.parent,
                prefix=f".{target.name}.",
                suffix=".bak",
            )
            os.close(fd)
            backup = Path(backup_name)
            backup.unlink(missing_ok=True)
            target.replace(backup)
            backups.append((target, backup))
        for staged, target in files:
            staged.replace(target)
            installed.append(target)
    except BaseException as install_error:
        rollback_errors: list[OSError] = []
        for target in reversed(installed):
            try:
                target.unlink(missing_ok=True)
            except OSError as exc:
                rollback_errors.append(exc)
        for target, backup in reversed(backups):
            if backup.exists():
                try:
                    target.unlink(missing_ok=True)
                    backup.replace(target)
                except OSError as exc:
                    rollback_errors.append(exc)
        if rollback_errors:
            detail = "; ".join(str(error) for error in rollback_errors)
            raise OSError(f"could not restore prior task Wiki artifacts: {detail}") from install_error
        raise
    else:
        for _, backup in backups:
            try:
                backup.unlink(missing_ok=True)
            except OSError:
                # The target set is already complete; an orphaned hidden backup is not consumed
                # by any readiness path and can be cleaned up separately.
                pass


def _freeze_role_snapshots(
    *,
    context_path: Path,
    roster_path: Path,
    feature_slug: str,
    ticket_source: str,
    task_id: str,
    task: dict[str, str],
    project_root: Path,
    obsidian_wiki_cmd: str | None,
    origin: str,
) -> tuple[tuple[Path, str], tuple[Path, str]]:
    try:
        context = _validate_context(context_path, roster_path, project_root)
    except ReadinessError:
        raise
    except (ValidationError, FingerprintError) as exc:
        raise ReadinessError(f"Wiki context is not execution-ready: {exc}") from exc
    implement_text, review_text = _prepare_role_snapshot_texts(
        context_path=context_path,
        context=context,
        feature_slug=feature_slug,
        ticket_source=ticket_source,
        task_id=task_id,
        task=task,
        project_root=project_root,
        obsidian_wiki_cmd=obsidian_wiki_cmd,
        origin=origin,
    )
    return _write_role_snapshots(
        context_path=context_path,
        context=context,
        task=task,
        task_id=task_id,
        implement_text=implement_text,
        review_text=review_text,
    )


def _validate_context_identity(
    context: dict[str, Any],
    feature_slug: str,
    ticket_source: str,
    task_id: str,
) -> None:
    if context.get("featureSlug") != feature_slug:
        raise ReadinessError("Wiki context featureSlug does not match the ticket roster")
    if context.get("ticketSource") != ticket_source:
        raise ReadinessError("Wiki context ticketSource does not match the ticket roster")
    task_refs = context.get("taskWikiRefs")
    if not isinstance(task_refs, list) or not any(
        isinstance(item, dict) and item.get("taskId") == task_id for item in task_refs
    ):
        raise ReadinessError(f"Wiki context has no finalized taskWikiRefs entry for {task_id}")


def _validate_receipt_shape(receipt: dict[str, Any]) -> None:
    allowed = {
        "schemaVersion",
        "kind",
        "generatedBy",
        "featureSlug",
        "ticketSource",
        "rosterFile",
        "tasks",
    }
    unknown = sorted(set(receipt) - allowed)
    if unknown:
        raise ReadinessError(f"readiness receipt contains unsupported fields: {', '.join(unknown)}")
    if receipt.get("schemaVersion") != SCHEMA_VERSION:
        raise ReadinessError(f"readiness receipt schemaVersion must be {SCHEMA_VERSION}")
    if receipt.get("kind") != KIND:
        raise ReadinessError(f"readiness receipt kind must be {KIND}")
    if receipt.get("generatedBy") != GENERATED_BY:
        raise ReadinessError(f"readiness receipt generatedBy must be {GENERATED_BY}")
    _feature_slug(receipt.get("featureSlug"))
    _required_text(receipt.get("ticketSource"), "ticketSource")
    _safe_context_filename(receipt.get("rosterFile"), "rosterFile")
    if not isinstance(receipt.get("tasks"), list) or not receipt["tasks"]:
        raise ReadinessError("readiness receipt tasks must be a non-empty array")


def _validate_task_entry(task: Any) -> dict[str, Any]:
    if not isinstance(task, dict):
        raise ReadinessError("readiness receipt task must be an object")
    allowed = {
        "taskId",
        "taskTitle",
        "taskFingerprint",
        "status",
        "contextDisposition",
        "reason",
        "contextFile",
        "implementWikiFile",
        "implementWikiDigest",
        "reviewWikiFile",
        "reviewWikiDigest",
    }
    unknown = sorted(set(task) - allowed)
    if unknown:
        raise ReadinessError(f"readiness task contains unsupported fields: {', '.join(unknown)}")
    _required_text(task.get("taskId"), "taskId")
    _required_text(task.get("taskTitle"), "taskTitle")
    fingerprint = _required_text(task.get("taskFingerprint"), "taskFingerprint")
    if len(fingerprint) != 64 or any(char not in "0123456789abcdef" for char in fingerprint):
        raise ReadinessError("taskFingerprint must be a 64-character lowercase sha256 digest")
    status = task.get("status")
    if status not in STATUS_DISPOSITIONS:
        raise ReadinessError(f"readiness status must be one of {', '.join(STATUS_DISPOSITIONS)}")
    if task.get("contextDisposition") != STATUS_DISPOSITIONS[status]:
        raise ReadinessError(f"contextDisposition does not match readiness status {status}")
    _required_text(task.get("reason"), "reason")
    context_file = task.get("contextFile")
    if status == "ready":
        _safe_context_filename(context_file, "contextFile")
        snapshot_fields = ("implementWikiFile", "implementWikiDigest", "reviewWikiFile", "reviewWikiDigest")
        present = [field in task for field in snapshot_fields]
        if any(present) and not all(present):
            raise ReadinessError("ready readiness must retain all role-specific task Wiki snapshot fields")
        if all(present):
            for field in ("implementWikiFile", "reviewWikiFile"):
                _safe_context_filename(task.get(field), field)
            for field in ("implementWikiDigest", "reviewWikiDigest"):
                digest = _required_text(task.get(field), field)
                if not digest.startswith("sha256:") or len(digest) != 71:
                    raise ReadinessError(f"{field} must be a sha256 digest")
    elif context_file is not None:
        raise ReadinessError(f"{status} readiness must not retain a contextFile")
    elif any(field in task for field in ("implementWikiFile", "implementWikiDigest", "reviewWikiFile", "reviewWikiDigest")):
        raise ReadinessError(f"{status} readiness must not retain task Wiki snapshots")
    return task


def record_readiness(
    receipt_path: Path,
    roster_path: Path,
    task_id: str,
    status: str,
    reason: str,
    context_path: Path | None,
    materialized: bool = False,
    project_root: Path | None = None,
    implement_wiki: tuple[Path, str] | None = None,
    review_wiki: tuple[Path, str] | None = None,
) -> str:
    _same_context_directory(receipt_path, roster_path, "ticket roster")
    raw_roster, feature_slug, ticket_source, tasks = _roster_metadata(roster_path)
    task_id = safe_task_id(_required_text(task_id, "taskId").strip())
    if task_id not in tasks:
        raise ReadinessError(f"ticket roster has no task {task_id}")
    if status not in STATUS_DISPOSITIONS:
        raise ReadinessError(f"readiness status must be one of {', '.join(STATUS_DISPOSITIONS)}")
    reason = _required_text(reason, "reason").strip()
    if status == "ready" and not materialized:
        raise ReadinessError("ready readiness must use the bind command so materialization is proven")

    context_file: str | None = None
    if status == "ready":
        if context_path is None:
            raise ReadinessError("ready readiness requires --context")
        if implement_wiki is None or review_wiki is None:
            raise ReadinessError("ready readiness requires both role-specific task Wiki snapshots")
        _same_context_directory(receipt_path, context_path, "Wiki context")
        context = _validate_context(
            context_path,
            roster_path,
            project_root or infer_project_root(roster_path),
        )
        _validate_context_identity(context, feature_slug, ticket_source, task_id)
        context_file = context_path.name
    elif context_path is not None:
        raise ReadinessError(f"{status} readiness must not retain or reference --context")

    if receipt_path.exists():
        receipt = _load_json(receipt_path, "readiness receipt")
        _validate_receipt_shape(receipt)
        if receipt["featureSlug"] != feature_slug:
            raise ReadinessError("existing readiness receipt featureSlug does not match the ticket roster")
        if receipt["ticketSource"] != ticket_source:
            raise ReadinessError("existing readiness receipt ticketSource does not match the ticket roster")
        if receipt["rosterFile"] != roster_path.name:
            raise ReadinessError("existing readiness receipt points at a different ticket roster")
        existing = {
            _validate_task_entry(item)["taskId"]: item
            for item in receipt["tasks"]
        }
    else:
        existing = {}

    task = tasks[task_id]
    entry: dict[str, Any] = {
        "taskId": task_id,
        "taskTitle": task["title"],
        "taskFingerprint": task["hash"],
        "status": status,
        "contextDisposition": STATUS_DISPOSITIONS[status],
        "reason": reason,
    }
    if context_file is not None:
        entry["contextFile"] = context_file
        entry["implementWikiFile"] = implement_wiki[0].name
        entry["implementWikiDigest"] = implement_wiki[1]
        entry["reviewWikiFile"] = review_wiki[0].name
        entry["reviewWikiDigest"] = review_wiki[1]
    existing[task_id] = entry

    ordered_tasks = [
        existing[roster_task_id]
        for roster_task_id in tasks
        if roster_task_id in existing
    ]
    receipt = {
        "schemaVersion": SCHEMA_VERSION,
        "kind": KIND,
        "generatedBy": GENERATED_BY,
        "featureSlug": feature_slug,
        "ticketSource": raw_roster["ticketSource"],
        "rosterFile": roster_path.name,
        "tasks": ordered_tasks,
    }
    _write_json(receipt_path, receipt)
    _refresh_session_state(receipt_path.parent, task_id=task_id)
    return f"recorded {status} readiness for task {task_id} -> {receipt_path}"


def bind_readiness(
    receipt_path: Path,
    roster_path: Path,
    context_path: Path,
    task_id: str,
    project_root: Path,
    reason: str,
    obsidian_wiki_cmd: str | None = None,
    now: datetime | None = None,
) -> str:
    _same_context_directory(receipt_path, roster_path, "ticket roster")
    _same_context_directory(receipt_path, context_path, "Wiki context")
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")

    _, feature_slug, ticket_source, tasks = _roster_metadata(roster_path)
    task_id = safe_task_id(_required_text(task_id, "taskId").strip())
    if task_id not in tasks:
        raise ReadinessError(f"ticket roster has no task {task_id}")
    context = _validate_context(context_path, roster_path, project_root)
    _validate_context_identity(context, feature_slug, ticket_source, task_id)

    implement_path, review_path = _snapshot_paths(context_path, task_id)
    approval_file = approval_path(context_path, task_id)
    have_implement = implement_path.is_file()
    have_review = review_path.is_file()
    have_approval = approval_file.is_file()
    have_complete_approval = have_implement and have_review and have_approval
    if have_complete_approval:
        implement_info = (implement_path, file_digest(implement_path))
        review_info = (review_path, file_digest(review_path))
        snapshots = _load_role_snapshots(
            context_path=context_path,
            context=context,
            feature_slug=feature_slug,
            ticket_source=ticket_source,
            task_id=task_id,
            task=tasks[task_id],
            implement_digest=implement_info[1],
            review_digest=review_info[1],
            now=now,
        )
    else:
        # A finalized context may predate role-specific snapshots, or may have an incomplete
        # unapproved pair left by an interrupted/legacy attempt. Re-freeze the complete pair as
        # one transaction; do not reject the compatibility path merely because one old artifact
        # is present.
        implement_info, review_info = _freeze_role_snapshots(
            context_path=context_path,
            roster_path=roster_path,
            feature_slug=feature_slug,
            ticket_source=ticket_source,
            task_id=task_id,
            task=tasks[task_id],
            project_root=project_root,
            obsidian_wiki_cmd=obsidian_wiki_cmd,
            origin="implementation-entry",
        )
        snapshots = _load_role_snapshots(
            context_path=context_path,
            context=context,
            feature_slug=feature_slug,
            ticket_source=ticket_source,
            task_id=task_id,
            task=tasks[task_id],
            implement_digest=implement_info[1],
            review_digest=review_info[1],
            now=now,
        )

    record_readiness(
        receipt_path,
        roster_path,
        task_id,
        "ready",
        reason,
        context_path,
        materialized=True,
        project_root=project_root,
        implement_wiki=implement_info,
        review_wiki=review_info,
    )
    body = snapshots[0][1]
    warnings = snapshots[0][2]
    if warnings:
        return (
            "## Knowledge Freshness Warnings\n\n"
            + "\n".join(f"- {warning}" for warning in warnings)
            + "\n\n"
            + body
        )
    return body


def _discard_late_carry_artifacts(feature_directory: Path, task_id: str) -> None:
    """Remove unapproved late-Carry output while preserving the identity inputs."""

    names = {
        "obsidian-wiki-selection.json",
        "wiki-context.json",
        f"{task_id}.wiki-implement.md",
        f"{task_id}.wiki-review.md",
        f"{task_id}.wiki-approval.json",
        f"{task_id}.wiki-review-handoff.md",
    }
    for name in names:
        (feature_directory / name).unlink(missing_ok=True)


def late_carry_readiness(
    *,
    project_root: Path,
    feature_slug: str,
    task_id: str,
    context_path: Path,
    roster_path: Path,
    reason: str = "Late Carry readiness validated.",
    obsidian_wiki_cmd: str | None = None,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Commit one direct/manual task's finalized late-Carry output atomically.

    Research and semantic routing happen outside the execution layer. This seam accepts only the
    resulting execution-ready context and the host-produced single-task roster, then stages the
    two role contracts, approval manifest, and readiness receipt before replacing the approved set.
    """

    project_root = project_root.expanduser().resolve()
    feature_slug = _feature_slug(feature_slug)
    raw_task_id = _required_text(task_id, "taskId").strip()
    try:
        task_id = safe_task_id(raw_task_id)
    except SnapshotError as exc:
        return _result_base(feature_slug=feature_slug, task_id=raw_task_id, status="broken", reason=str(exc))
    reason = _required_text(reason, "reason").strip()
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")
    _same_context_directory(context_path, roster_path, "ticket roster")
    feature_directory = context_path.resolve().parent
    if feature_directory != feature_context_dir(project_root, feature_slug).resolve():
        raise ReadinessError("late Carry artifacts must be in the selected feature context directory")

    ticket_source: str | None = None
    task_title: str | None = None
    try:
        _, roster_feature, ticket_source, tasks = _roster_metadata(roster_path)
        if roster_feature != feature_slug:
            raise ReadinessError("ticket roster featureSlug does not match the selected feature")
        if ticket_source not in {"github-issues", "manual"}:
            raise ReadinessError("late Carry requires a direct tracker or manual single-task roster")
        if len(tasks) != 1 or task_id not in tasks:
            raise ReadinessError("late Carry requires exactly one roster task matching taskId")
        task_title = tasks[task_id]["title"]
        if not context_path.is_file():
            raise ReadinessError("late Carry requires a finalized execution-ready Wiki context")

        # Validate the caller's semantic routing before staging any execution artifacts. The
        # staged copy is what freeze/bind read, so a failed materialization cannot mutate the live
        # context or leave a one-role approval behind.
        context = _validate_context(context_path, roster_path, project_root)
        _validate_context_identity(context, feature_slug, ticket_source, task_id)
        with tempfile.TemporaryDirectory(
            dir=feature_directory,
            prefix=f".{task_id}.late-carry-",
        ) as staging:
            stage_dir = Path(staging)
            staged_context = stage_dir / context_path.name
            staged_roster = stage_dir / roster_path.name
            shutil.copyfile(context_path, staged_context)
            shutil.copyfile(roster_path, staged_roster)
            staged_implement, staged_review = _freeze_role_snapshots(
                context_path=staged_context,
                roster_path=staged_roster,
                feature_slug=feature_slug,
                ticket_source=ticket_source,
                task_id=task_id,
                task=tasks[task_id],
                project_root=project_root,
                obsidian_wiki_cmd=obsidian_wiki_cmd,
                origin="late-carry",
            )
            staged_receipt = stage_dir / "wiki-readiness.json"
            record_readiness(
                staged_receipt,
                staged_roster,
                task_id,
                "ready",
                reason,
                staged_context,
                materialized=True,
                project_root=project_root,
                implement_wiki=staged_implement,
                review_wiki=staged_review,
            )
            staged_result = _structured_readiness_result(
                receipt_path=staged_receipt,
                task_id=task_id,
                project_root=project_root,
                now=now,
            )
            _atomic_replace_files(
                [
                    (staged_implement[0], feature_directory / staged_implement[0].name),
                    (staged_review[0], feature_directory / staged_review[0].name),
                    (
                        stage_dir / approval_path(staged_context, task_id).name,
                        feature_directory / approval_path(context_path, task_id).name,
                    ),
                    (staged_receipt, feature_directory / "wiki-readiness.json"),
                ]
            )

        # The selection is only a Carry input. A successful late commit leaves the finalized
        # context and role contracts, never a second selection source for later execution.
        (feature_directory / "obsidian-wiki-selection.json").unlink(missing_ok=True)
        _refresh_session_state(feature_directory, task_id=task_id, readiness_status="ready")
        return staged_result
    except (ReadinessError, ValidationError, FingerprintError, SnapshotError, OSError) as exc:
        # A direct/manual late-Carry attempt owns the transient context. Do not leave a partial
        # sidecar, selection, role snapshot, or approval manifest after a broken transaction.
        _discard_late_carry_artifacts(feature_directory, task_id)
        receipt_path = feature_directory / "wiki-readiness.json"
        if roster_path.is_file():
            try:
                record_readiness(
                    receipt_path,
                    roster_path,
                    task_id,
                    "broken",
                    str(exc),
                    None,
                )
            except (ReadinessError, OSError):
                pass
        return _result_base(
            feature_slug=feature_slug,
            task_id=task_id,
            status="broken",
            reason=str(exc),
            ticket_source=ticket_source,
            task_title=task_title,
        )


def freeze_task_snapshots(
    *,
    context_path: Path,
    roster_path: Path,
    task_id: str,
    project_root: Path,
    obsidian_wiki_cmd: str | None,
) -> str:
    _same_context_directory(context_path, roster_path, "ticket roster")
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")
    _, feature_slug, ticket_source, tasks = _roster_metadata(roster_path)
    task_id = safe_task_id(_required_text(task_id, "taskId").strip())
    if task_id not in tasks:
        raise ReadinessError(f"ticket roster has no task {task_id}")
    implement_info, review_info = _freeze_role_snapshots(
        context_path=context_path,
        roster_path=roster_path,
        feature_slug=feature_slug,
        ticket_source=ticket_source,
        task_id=task_id,
        task=tasks[task_id],
        project_root=project_root,
        obsidian_wiki_cmd=obsidian_wiki_cmd,
        origin="planning-approved",
    )
    _refresh_session_state(context_path.parent, task_id=task_id)
    return (
        f"froze task Wiki snapshots for {task_id}: "
        f"{implement_info[0].name} ({implement_info[1]}), "
        f"{review_info[0].name} ({review_info[1]})"
    )


def freeze_all_task_snapshots(
    *,
    context_path: Path,
    roster_path: Path,
    project_root: Path,
    obsidian_wiki_cmd: str | None,
) -> str:
    """Freeze every finalized roster task from one approved planning snapshot.

    Rendering/materialization is completed for the full roster before any snapshot or approval
    manifest is written. This preserves the per-task approval contract while avoiding a partially
    approved batch when a later task cannot be materialized.
    """
    _same_context_directory(context_path, roster_path, "ticket roster")
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")
    _, feature_slug, ticket_source, tasks = _roster_metadata(roster_path)
    try:
        context = _validate_context(context_path, roster_path, project_root)
    except ReadinessError:
        raise
    except (ValidationError, FingerprintError) as exc:
        raise ReadinessError(f"Wiki context is not execution-ready: {exc}") from exc

    prepared: list[tuple[str, dict[str, str], str, str]] = []
    for task_id, task in tasks.items():
        implement_text, review_text = _prepare_role_snapshot_texts(
            context_path=context_path,
            context=context,
            feature_slug=feature_slug,
            ticket_source=ticket_source,
            task_id=task_id,
            task=task,
            project_root=project_root,
            obsidian_wiki_cmd=obsidian_wiki_cmd,
            origin="planning-approved",
        )
        prepared.append((task_id, task, implement_text, review_text))

    frozen: list[str] = []
    for task_id, task, implement_text, review_text in prepared:
        implement_info, review_info = _write_role_snapshots(
            context_path=context_path,
            context=context,
            task=task,
            task_id=task_id,
            implement_text=implement_text,
            review_text=review_text,
        )
        frozen.append(
            f"{task_id}: {implement_info[0].name} ({implement_info[1]}), "
            f"{review_info[0].name} ({review_info[1]})"
        )
    _refresh_session_state(context_path.parent)
    return f"froze task Wiki snapshots for {len(frozen)} task(s): " + "; ".join(frozen)


def validate_readiness(
    receipt_path: Path,
    task_id: str,
    project_root: Path | None = None,
) -> str:
    _, _, entry, _ = _validated_readiness_task(receipt_path, task_id, project_root)
    return f"readiness {entry['status']} is valid for task {entry['taskId']}"


def _validated_readiness_task(
    receipt_path: Path,
    task_id: str,
    project_root: Path | None = None,
) -> tuple[dict[str, Any], Path, dict[str, Any], Path | None]:
    receipt = _load_json(receipt_path, "readiness receipt")
    _validate_receipt_shape(receipt)
    roster_path = receipt_path.parent / _safe_context_filename(receipt["rosterFile"], "rosterFile")
    _, feature_slug, ticket_source, roster_tasks = _roster_metadata(roster_path)
    if receipt["featureSlug"] != feature_slug:
        raise ReadinessError("readiness receipt featureSlug does not match the current ticket roster")
    if receipt["ticketSource"] != ticket_source:
        raise ReadinessError("readiness receipt ticketSource does not match the current ticket roster")

    seen: set[str] = set()
    task_entries: dict[str, dict[str, Any]] = {}
    for raw_task in receipt["tasks"]:
        task = _validate_task_entry(raw_task)
        entry_id = task["taskId"]
        if entry_id in seen:
            raise ReadinessError(f"readiness receipt duplicates task {entry_id}")
        seen.add(entry_id)
        task_entries[entry_id] = task

    task_id = safe_task_id(_required_text(task_id, "taskId").strip())
    if task_id not in task_entries:
        raise ReadinessError(f"readiness receipt has no result for task {task_id}")
    if task_id not in roster_tasks:
        raise ReadinessError(f"current ticket roster has no task {task_id}")
    entry = task_entries[task_id]
    roster_task = roster_tasks[task_id]
    if entry["taskTitle"] != roster_task["title"]:
        raise ReadinessError(f"task title drift for {task_id}")
    if entry["taskFingerprint"] != roster_task["hash"]:
        raise ReadinessError(f"task fingerprint drift for {task_id}")

    if entry["status"] == "ready":
        context_path = receipt_path.parent / _safe_context_filename(entry["contextFile"], "contextFile")
        context = _validate_context(
            context_path,
            roster_path,
            project_root or infer_project_root(roster_path),
        )
        _validate_context_identity(context, feature_slug, ticket_source, task_id)
        if "implementWikiFile" in entry:
            _load_role_snapshots(
                context_path=context_path,
                context=context,
                feature_slug=feature_slug,
                ticket_source=ticket_source,
                task_id=task_id,
                task=roster_task,
                implement_digest=entry.get("implementWikiDigest"),
                review_digest=entry.get("reviewWikiDigest"),
            )
    else:
        context_path = None
    return receipt, roster_path, entry, context_path


def _review_handoff_text(
    *,
    status: str,
    task_id: str | None,
    detail: str,
    materialized: str | None = None,
) -> str:
    lines = [
        "# Reviewer Wiki Context",
        "",
        f"- Status: {status}",
        f"- Task ID: `{task_id}`" if task_id else "- Task ID: unknown",
        "",
    ]
    if status != "ready":
        lines.extend(
            [
                "## Non-blocking caveat",
                "",
                "No verified Wiki reviewer context is available for this review.",
                f"This is a non-blocking caveat: {detail}",
                "Continue both Standards and Spec review without Wiki constraints. Do not run late research or delay review.",
                "",
            ]
        )
        return "\n".join(lines)

    lines.extend(
        [
            "Use this same read-only context for both isolated review axes:",
            "",
            "- Standards still reports only repository-standard and code-quality findings.",
            "- Spec still reports only issue/spec completeness, correctness, and scope findings.",
            "- Wiki constraints may inform either axis but must not merge or change their output structure.",
            "",
        ]
    )
    if materialized and materialized.strip():
        lines.extend([materialized.strip(), ""])
    return "\n".join(lines)


def review_handoff(
    *,
    receipt_path: Path | None,
    task_id: str | None,
    project_root: Path,
    handoff_path: Path,
    obsidian_wiki_cmd: str | None,
    now: datetime | None = None,
) -> str:
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")
    handoff_directory = handoff_path.resolve().parent
    if not _is_allowed_context_directory(handoff_directory, project_root):
        raise ReadinessError(
            "review handoff must be a plain file in <project-root>/.grill-adapter/context/<feature-slug>"
        )

    normalized_task_id = task_id.strip() if isinstance(task_id, str) and task_id.strip() else None
    if (
        normalized_task_id is not None
        and handoff_path.name
        == snapshot_path(handoff_path.parent / "wiki-context.json", normalized_task_id, "reviewer").name
    ):
        raise ReadinessError("review handoff must not overwrite the approved reviewer snapshot")
    if receipt_path is None or normalized_task_id is None or not receipt_path.is_file():
        _write_text(
            handoff_path,
            _review_handoff_text(
                status="unknown",
                task_id=normalized_task_id,
                detail="the current task or its implementation readiness receipt could not be identified.",
            ),
        )
        return f"wrote fail-open unknown reviewer handoff -> {handoff_path}"

    try:
        receipt_directory = receipt_path.resolve().parent
        if not _is_allowed_context_directory(receipt_directory, project_root):
            raise ReadinessError("readiness receipt is outside the current project .grill-adapter/context")
        if handoff_directory != receipt_directory:
            raise ReadinessError("review handoff must be in the same feature context directory as the readiness receipt")
        _, roster_path, entry, context_path = _validated_readiness_task(
            receipt_path,
            normalized_task_id,
            project_root,
        )
    except (ReadinessError, ValidationError, FingerprintError):
        _write_text(
            handoff_path,
            _review_handoff_text(
                status="broken",
                task_id=normalized_task_id,
                detail="the implementation readiness receipt or its bound context failed validation; all Wiki output was discarded.",
            ),
        )
        return f"wrote fail-open broken reviewer handoff -> {handoff_path}"

    status = entry["status"]
    if status != "ready":
        _write_text(
            handoff_path,
            _review_handoff_text(
                status=status,
                task_id=normalized_task_id,
                detail=f"implementation readiness is {status}; no late research or reviewer materialization was attempted.",
            ),
        )
        return f"wrote fail-open {status} reviewer handoff -> {handoff_path}"

    if context_path is None:
        raise ReadinessError("ready readiness did not resolve a Wiki context")

    reviewer_snapshot = snapshot_path(context_path, normalized_task_id, "reviewer")
    implementer_snapshot = snapshot_path(context_path, normalized_task_id, "implementer")
    approved_pair_exists = (
        reviewer_snapshot.is_file()
        and implementer_snapshot.is_file()
        and approval_path(context_path, normalized_task_id).is_file()
    )
    if "reviewWikiFile" in entry or approved_pair_exists:
        try:
            _, feature_slug, ticket_source, tasks = _roster_metadata(roster_path)
            _, review_snapshot = _load_role_snapshots(
                context_path=context_path,
                context=_load_json(context_path, "wiki context"),
                feature_slug=feature_slug,
                ticket_source=ticket_source,
                task_id=normalized_task_id,
                task=tasks[normalized_task_id],
                implement_digest=entry["implementWikiDigest"],
                review_digest=entry["reviewWikiDigest"],
                now=now,
            )
            materialized = review_snapshot[1]
            warnings = review_snapshot[2]
            review_path = (
                context_path.parent / _safe_context_filename(entry["reviewWikiFile"], "reviewWikiFile")
                if "reviewWikiFile" in entry
                else reviewer_snapshot
            )
            if review_path.name != reviewer_snapshot.name:
                raise ReadinessError("reviewWikiFile does not match the task-specific reviewer snapshot name")
        except (ReadinessError, SnapshotError, KeyError) as exc:
            _write_text(
                handoff_path,
                _review_handoff_text(
                    status="materialize-failed",
                    task_id=normalized_task_id,
                    detail=f"reviewer task Wiki snapshot validation failed: {exc}; stale output was discarded.",
                ),
            )
            return f"wrote fail-open materialize-failed reviewer handoff -> {handoff_path}"
        if warnings:
            materialized = (
                "## Knowledge Freshness Warnings\n\n"
                + "\n".join(f"- {warning}" for warning in warnings)
                + "\n\n"
                + materialized
            )
    else:
        # Review is an execution-time consumer of the approved role contract. Never fall back to
        # a live Wiki read when a legacy/partial receipt has no frozen reviewer pair; the host can
        # continue with a caveat and a later readiness repair can deliberately re-freeze it.
        _write_text(
            handoff_path,
            _review_handoff_text(
                status="materialize-failed",
                task_id=normalized_task_id,
                detail="the approved reviewer snapshot is missing; rerun wiki-readiness before retrying the review.",
            ),
        )
        return f"wrote fail-open materialize-failed reviewer handoff -> {handoff_path}"

    _write_text(
        handoff_path,
        _review_handoff_text(
            status="ready",
            task_id=normalized_task_id,
            detail="",
            materialized=materialized,
        ),
    )
    return f"wrote ready reviewer handoff -> {handoff_path}"


def _result_base(
    *,
    feature_slug: str,
    task_id: str,
    status: str,
    reason: str,
    ticket_source: str | None = None,
    task_title: str | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "schemaVersion": RESULT_SCHEMA_VERSION,
        "kind": RESULT_KIND,
        "generatedBy": GENERATED_BY,
        "featureSlug": feature_slug,
        "taskId": task_id,
        "status": status,
        "reason": reason,
        "rosterFile": "ticket-roster.json",
        "receiptFile": "wiki-readiness.json",
    }
    if ticket_source is not None:
        result["ticketSource"] = ticket_source
    if task_title is not None:
        result["taskTitle"] = task_title
    if status in STATUS_DISPOSITIONS:
        result["contextDisposition"] = STATUS_DISPOSITIONS[status]
    return result


def _structured_readiness_result(
    *,
    receipt_path: Path,
    task_id: str,
    project_root: Path,
    now: datetime | None = None,
) -> dict[str, Any]:
    receipt, roster_path, entry, context_path = _validated_readiness_task(
        receipt_path,
        task_id,
        project_root,
    )
    result = _result_base(
        feature_slug=receipt["featureSlug"],
        task_id=entry["taskId"],
        status=entry["status"],
        reason=entry["reason"],
        ticket_source=receipt["ticketSource"],
        task_title=entry["taskTitle"],
    )
    if entry["status"] != "ready":
        return result
    if context_path is None:
        raise ReadinessError("ready readiness did not resolve a Wiki context")

    _, feature_slug, ticket_source, tasks = _roster_metadata(roster_path)
    snapshots = _load_role_snapshots(
        context_path=context_path,
        context=_load_json(context_path, "wiki context"),
        feature_slug=feature_slug,
        ticket_source=ticket_source,
        task_id=task_id,
        task=tasks[task_id],
        implement_digest=entry.get("implementWikiDigest"),
        review_digest=entry.get("reviewWikiDigest"),
        now=now,
    )
    implement_path, _, implement_warnings = snapshots[0]
    review_path, _, review_warnings = snapshots[1]
    result["contextFile"] = context_path.name
    result["implementer"] = {
        "file": implement_path.name,
        "digest": file_digest(implement_path),
    }
    result["reviewer"] = {
        "file": review_path.name,
        "digest": file_digest(review_path),
    }
    warnings = []
    for warning in [*implement_warnings, *review_warnings]:
        if warning not in warnings:
            warnings.append(warning)
    if warnings:
        result["warnings"] = warnings
    # The task body remains in the role Markdown file. Returning only filenames/digests keeps this
    # coordinator result metadata-only and lets the host consume the approved file explicitly.
    return result


def readiness_entry(
    *,
    project_root: Path,
    feature_slug: str,
    task_id: str,
    reason: str = "Implementation readiness validated.",
    obsidian_wiki_cmd: str | None = None,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Run one formal-ticket readiness transaction from a stable task identity.

    This is the host-facing seam. It resolves local artifacts, validates ticket/context
    fingerprints, reuses an approved role pair when present, and performs the compatibility freeze
    only when the pair is absent or incomplete. Failures become a structured ``broken`` result
    without retaining partial Wiki output; existing non-ready receipts are returned unchanged.
    """

    project_root = project_root.expanduser().resolve()
    feature_slug = _feature_slug(feature_slug)
    raw_task_id = _required_text(task_id, "taskId").strip()
    try:
        task_id = safe_task_id(raw_task_id)
    except SnapshotError as exc:
        return _result_base(
            feature_slug=feature_slug,
            task_id=raw_task_id,
            status="broken",
            reason=str(exc),
        )
    reason = _required_text(reason, "reason").strip()
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")

    directory = feature_context_dir(project_root, feature_slug)
    roster_path = directory / "ticket-roster.json"
    context_path = directory / "wiki-context.json"
    receipt_path = directory / "wiki-readiness.json"
    ticket_source: str | None = None
    task_title: str | None = None

    try:
        _, roster_feature, ticket_source, tasks = _roster_metadata(roster_path)
        if roster_feature != feature_slug:
            raise ReadinessError("ticket roster featureSlug does not match the selected feature")
        if task_id not in tasks:
            raise ReadinessError(f"ticket roster has no task {task_id}")
        task_title = tasks[task_id]["title"]

        # Direct/manual tasks may arrive without a formal Carry context. An absent provider is a
        # clean disabled terminal state; a configured provider still needs the model-driven
        # researcher/routing step and is therefore a broken, fail-open readiness result here.
        if not context_path.is_file() and not receipt_path.is_file():
            provider_state = _wiki_provider_state(project_root)
            if provider_state == "disabled":
                reason_text = "No enabled Wiki provider is configured for this project."
                _discard_late_carry_artifacts(directory, task_id)
                record_readiness(
                    receipt_path,
                    roster_path,
                    task_id,
                    "disabled",
                    reason_text,
                    None,
                )
                return _result_base(
                    feature_slug=feature_slug,
                    task_id=task_id,
                    status="disabled",
                    reason=reason_text,
                    ticket_source=ticket_source,
                    task_title=task_title,
                )
            if provider_state == "broken":
                raise ReadinessError("Project Wiki settings are malformed; late Carry cannot start")
            raise ReadinessError(
                "No finalized Wiki context exists; complete the single-task late Carry routing approval first"
            )

        if receipt_path.is_file():
            raw_receipt = _load_json(receipt_path, "readiness receipt")
            _validate_receipt_shape(raw_receipt)
            if (
                raw_receipt["featureSlug"] != feature_slug
                or raw_receipt["ticketSource"] != ticket_source
                or raw_receipt["rosterFile"] != roster_path.name
            ):
                raise ReadinessError("existing readiness artifact does not match the selected ticket roster")
            raw_entry = next(
                (
                    item for item in raw_receipt["tasks"]
                    if isinstance(item, dict) and item.get("taskId") == task_id
                ),
                None,
            )
            if raw_entry is None:
                raise ReadinessError(f"readiness receipt has no result for task {task_id}")
            raw_entry = _validate_task_entry(raw_entry)
            receipt = raw_receipt
            entry = raw_entry
            snapshot_fields = {
                "implementWikiFile",
                "implementWikiDigest",
                "reviewWikiFile",
                "reviewWikiDigest",
            }
            implement_path, review_path = _snapshot_paths(context_path, task_id)
            approved_pair_missing = (
                raw_entry["status"] == "ready"
                and snapshot_fields.issubset(raw_entry)
                and not (
                    implement_path.is_file()
                    and review_path.is_file()
                    and approval_path(context_path, task_id).is_file()
                )
            )
            if not approved_pair_missing:
                try:
                    receipt, _, entry, _ = _validated_readiness_task(
                        receipt_path,
                        task_id,
                        project_root,
                    )
                except (ReadinessError, ValidationError, FingerprintError, SnapshotError) as exc:
                    raise ReadinessError(f"existing readiness artifact failed validation: {exc}") from exc
                if entry["status"] != "ready":
                    _refresh_session_state(
                        receipt_path.parent,
                        task_id=task_id,
                        readiness_status=entry["status"],
                    )
                    return _result_base(
                        feature_slug=feature_slug,
                        task_id=task_id,
                        status=entry["status"],
                        reason=entry["reason"],
                        ticket_source=receipt["ticketSource"],
                        task_title=task_title,
                    )

            # A legacy ready receipt may not have recorded role digests. If the complete approved
            # pair exists, the structured result still validates it; otherwise bind performs the
            # compatibility freeze and upgrades the receipt atomically.
            if (
                snapshot_fields.issubset(entry)
                and implement_path.is_file()
                and review_path.is_file()
                and approval_path(context_path, task_id).is_file()
            ):
                _refresh_session_state(receipt_path.parent, task_id=task_id, readiness_status="ready")
                return _structured_readiness_result(
                    receipt_path=receipt_path,
                    task_id=task_id,
                    project_root=project_root,
                    now=now,
                )

        bind_readiness(
            receipt_path,
            roster_path,
            context_path,
            task_id,
            project_root,
            reason,
            obsidian_wiki_cmd,
            now=now,
        )
        return _structured_readiness_result(
            receipt_path=receipt_path,
            task_id=task_id,
            project_root=project_root,
            now=now,
        )
    except (ReadinessError, ValidationError, FingerprintError, SnapshotError, OSError) as exc:
        if ticket_source in {"github-issues", "manual"}:
            _discard_late_carry_artifacts(receipt_path.parent, task_id)
            receipt_path.unlink(missing_ok=True)
        if not receipt_path.exists():
            try:
                record_readiness(
                    receipt_path,
                    roster_path,
                    task_id,
                    "broken",
                    str(exc),
                    None,
                )
            except (ReadinessError, OSError):
                pass
        return _result_base(
            feature_slug=feature_slug,
            task_id=task_id,
            status="broken",
            reason=str(exc),
            ticket_source=ticket_source,
            task_title=task_title,
        )


def review_entry(
    *,
    project_root: Path,
    feature_slug: str,
    task_id: str,
    obsidian_wiki_cmd: str | None = None,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Derive one read-only reviewer handoff from the canonical implementation receipt."""

    project_root = project_root.expanduser().resolve()
    feature_slug = _feature_slug(feature_slug)
    raw_task_id = _required_text(task_id, "taskId").strip()
    try:
        task_id = safe_task_id(raw_task_id)
    except SnapshotError as exc:
        return _result_base(
            feature_slug=feature_slug,
            task_id=raw_task_id,
            status="broken",
            reason=str(exc),
        )
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")
    directory = feature_context_dir(project_root, feature_slug)
    receipt_path = directory / "wiki-readiness.json"
    handoff_path = directory / f"{task_id}.wiki-review-handoff.md"

    result = _result_base(
        feature_slug=feature_slug,
        task_id=task_id,
        status="broken",
        reason="The implementation readiness receipt could not be identified.",
    )
    try:
        identity_error: str | None = None
        # Read identity metadata on a best-effort basis. The handoff helper below owns the
        # fail-open validation path and must still write a caveat handoff for malformed receipts.
        if receipt_path.is_file():
            try:
                receipt = _load_json(receipt_path, "readiness receipt")
                if receipt.get("featureSlug") != feature_slug:
                    identity_error = "readiness receipt featureSlug does not match the selected feature"
                elif isinstance(receipt.get("rosterFile"), str):
                    roster_path = receipt_path.parent / _safe_context_filename(receipt["rosterFile"], "rosterFile")
                    _, roster_feature, _, _ = _roster_metadata(roster_path)
                    if roster_feature != feature_slug:
                        identity_error = "ticket roster featureSlug does not match the selected feature"
                    else:
                        raw_entry = next(
                            item for item in receipt.get("tasks", [])
                            if isinstance(item, dict) and item.get("taskId") == task_id
                        )
                        entry = _validate_task_entry(raw_entry)
                        result = _result_base(
                            feature_slug=feature_slug,
                            task_id=task_id,
                            status=entry["status"],
                            reason=entry["reason"],
                            ticket_source=receipt.get("ticketSource"),
                            task_title=entry["taskTitle"],
                        )
            except (ReadinessError, ValidationError, FingerprintError, SnapshotError, StopIteration, KeyError):
                pass
        if identity_error:
            _write_text(
                handoff_path,
                _review_handoff_text(
                    status="broken",
                    task_id=task_id,
                    detail=identity_error,
                ),
            )
            result["status"] = "broken"
            result["reason"] = identity_error
            result["handoff"] = {
                "file": handoff_path.name,
                "digest": file_digest(handoff_path),
            }
            return result
        review_handoff(
            receipt_path=receipt_path if receipt_path.is_file() else None,
            task_id=task_id,
            project_root=project_root,
            handoff_path=handoff_path,
            obsidian_wiki_cmd=obsidian_wiki_cmd,
            now=now,
        )
        handoff_text = handoff_path.read_text(encoding="utf-8")
        status_line = next(
            (line.split(":", 1)[1].strip() for line in handoff_text.splitlines() if line.startswith("- Status:")),
            "unknown",
        )
        status = status_line if status_line in {"ready", "no-relevant", "disabled", "broken"} else "broken"
        result["status"] = status
        result["handoff"] = {
            "file": handoff_path.name,
            "digest": file_digest(handoff_path),
        }
        if status == "ready":
            result["reason"] = "Reviewer handoff validated from the implementation readiness receipt."
        elif status == "broken":
            result["reason"] = "Reviewer handoff is caveat-only because readiness validation failed."
        return result
    except (ReadinessError, ValidationError, FingerprintError, SnapshotError, OSError) as exc:
        result["status"] = "broken"
        result["reason"] = str(exc)
        return result


def main() -> int:
    _configure_stdio()
    parser = argparse.ArgumentParser(
        description="Prepare stable single-task rosters and record reusable implementation Wiki readiness."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    issue = subparsers.add_parser("prepare-issue", help="Build one ticket roster from gh issue JSON")
    issue.add_argument("--feature-slug", required=True)
    issue.add_argument("--issue-json", required=True)
    issue.add_argument("--roster", required=True)

    manual = subparsers.add_parser("prepare-manual", help="Build one manual ticket roster from a confirmed brief")
    manual.add_argument("--feature-slug", required=True)
    manual.add_argument("--task-title", required=True)
    manual.add_argument("--task-text-file", required=True)
    manual.add_argument("--roster", required=True)

    record = subparsers.add_parser("record", help="Record one task's Wiki readiness result")
    record.add_argument("--receipt", required=True)
    record.add_argument("--roster", required=True)
    record.add_argument("--task-id", required=True)
    record.add_argument("--status", choices=sorted(STATUS_DISPOSITIONS), required=True)
    record.add_argument("--reason", required=True)
    record.add_argument("--context")

    bind = subparsers.add_parser(
        "bind",
        help="Validate/consume one implementer task snapshot and record ready only on success",
    )
    bind.add_argument("--receipt", required=True)
    bind.add_argument("--roster", required=True)
    bind.add_argument("--context", required=True)
    bind.add_argument("--task-id", required=True)
    bind.add_argument("--project-root", required=True)
    bind.add_argument("--reason", required=True)
    bind.add_argument("--obsidian-wiki-cmd")

    late_carry = subparsers.add_parser(
        "late-carry",
        help="Atomically freeze and record one direct/manual task after routing approval",
    )
    late_carry.add_argument("--project-root", required=True)
    late_carry.add_argument("--feature-slug", required=True)
    late_carry.add_argument("--task-id", required=True)
    late_carry.add_argument("--context", required=True)
    late_carry.add_argument("--roster", required=True)
    late_carry.add_argument("--reason", default="Late Carry readiness validated.")
    late_carry.add_argument("--obsidian-wiki-cmd")

    freeze = subparsers.add_parser(
        "freeze",
        help="Generate approved role-specific task Wiki snapshots for one task or the full roster",
    )
    freeze.add_argument("--context", required=True)
    freeze.add_argument("--roster", required=True)
    freeze_target = freeze.add_mutually_exclusive_group(required=True)
    freeze_target.add_argument("--task-id")
    freeze_target.add_argument("--all", dest="all_tasks", action="store_true")
    freeze.add_argument("--project-root", required=True)
    freeze.add_argument("--obsidian-wiki-cmd")

    validate = subparsers.add_parser("validate", help="Validate a receipt against its current roster/context")
    validate.add_argument("--receipt", required=True)
    validate.add_argument("--task-id", required=True)
    validate.add_argument("--project-root")

    review = subparsers.add_parser(
        "review-handoff",
        help="Fail-open reviewer snapshot handoff from an existing implementation readiness receipt",
    )
    review.add_argument("--receipt")
    review.add_argument("--task-id")
    review.add_argument("--project-root", required=True)
    review.add_argument("--handoff", required=True)
    review.add_argument("--obsidian-wiki-cmd")

    run = subparsers.add_parser(
        "run",
        help="Run one formal-ticket readiness transaction from canonical project artifacts",
    )
    run.add_argument("--project-root", required=True)
    run.add_argument("--feature-slug", required=True)
    run.add_argument("--task-id", required=True)
    run.add_argument("--reason", default="Implementation readiness validated.")
    run.add_argument("--obsidian-wiki-cmd")

    review_entry_parser = subparsers.add_parser(
        "review",
        help="Derive one canonical reviewer handoff from implementation readiness",
    )
    review_entry_parser.add_argument("--project-root", required=True)
    review_entry_parser.add_argument("--feature-slug", required=True)
    review_entry_parser.add_argument("--task-id", required=True)
    review_entry_parser.add_argument("--obsidian-wiki-cmd")

    args = parser.parse_args()
    try:
        if args.command == "prepare-issue":
            print(
                prepare_issue(
                    Path(args.issue_json),
                    Path(args.roster),
                    args.feature_slug,
                )
            )
        elif args.command == "prepare-manual":
            print(
                prepare_manual(
                    Path(args.task_text_file),
                    Path(args.roster),
                    args.feature_slug,
                    args.task_title,
                )
            )
        elif args.command == "record":
            print(
                record_readiness(
                    Path(args.receipt),
                    Path(args.roster),
                    args.task_id,
                    args.status,
                    args.reason,
                    Path(args.context) if args.context else None,
                )
            )
        elif args.command == "bind":
            print(
                bind_readiness(
                    Path(args.receipt),
                    Path(args.roster),
                    Path(args.context),
                    args.task_id,
                    Path(args.project_root),
                    args.reason,
                    args.obsidian_wiki_cmd,
                )
            )
        elif args.command == "late-carry":
            print(
                json.dumps(
                    late_carry_readiness(
                        project_root=Path(args.project_root),
                        feature_slug=args.feature_slug,
                        task_id=args.task_id,
                        context_path=Path(args.context),
                        roster_path=Path(args.roster),
                        reason=args.reason,
                        obsidian_wiki_cmd=args.obsidian_wiki_cmd,
                    ),
                    ensure_ascii=False,
                    indent=2,
                    sort_keys=True,
                )
            )
        elif args.command == "freeze":
            if args.all_tasks:
                print(
                    freeze_all_task_snapshots(
                        context_path=Path(args.context),
                        roster_path=Path(args.roster),
                        project_root=Path(args.project_root),
                        obsidian_wiki_cmd=args.obsidian_wiki_cmd,
                    )
                )
            else:
                print(
                    freeze_task_snapshots(
                        context_path=Path(args.context),
                        roster_path=Path(args.roster),
                        task_id=args.task_id,
                        project_root=Path(args.project_root),
                        obsidian_wiki_cmd=args.obsidian_wiki_cmd,
                    )
                )
        elif args.command == "validate":
            print(
                validate_readiness(
                    Path(args.receipt),
                    args.task_id,
                    Path(args.project_root) if args.project_root else None,
                )
            )
        else:
            if args.command == "run":
                print(
                    json.dumps(
                        readiness_entry(
                            project_root=Path(args.project_root),
                            feature_slug=args.feature_slug,
                            task_id=args.task_id,
                            reason=args.reason,
                            obsidian_wiki_cmd=args.obsidian_wiki_cmd,
                        ),
                        ensure_ascii=False,
                        indent=2,
                        sort_keys=True,
                    )
                )
            elif args.command == "review":
                print(
                    json.dumps(
                        review_entry(
                            project_root=Path(args.project_root),
                            feature_slug=args.feature_slug,
                            task_id=args.task_id,
                            obsidian_wiki_cmd=args.obsidian_wiki_cmd,
                        ),
                        ensure_ascii=False,
                        indent=2,
                        sort_keys=True,
                    )
                )
            else:
                print(
                    review_handoff(
                        receipt_path=Path(args.receipt) if args.receipt else None,
                        task_id=args.task_id,
                        project_root=Path(args.project_root),
                        handoff_path=Path(args.handoff),
                        obsidian_wiki_cmd=args.obsidian_wiki_cmd,
                    )
                )
        return 0
    except (ReadinessError, ValidationError, FingerprintError, SnapshotError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
