#!/usr/bin/env python3
"""Generated by grill-adapter."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from adr_identity import AdrIdentityError, source_id_for_path, validate_identity

KIND = "grill-adapter.wiki-context"
SCHEMA_VERSION = 6
SUPPORTED_SCHEMA_VERSIONS = {SCHEMA_VERSION}
DESTINATION_KINDS = {"task-bound", "global", "planning-only"}
SCAFFOLD_GENERATED_BY = "grill-adapter"
# taskRouting block emitted by --scaffold. These are the pre-confirmation values: the author flips
# status to "confirmed" and selectedSectionsFrozen to true once routing is final, and
# --bind-fingerprints + --execution-ready then gate it. The other three are fixed declared strings.
SCAFFOLD_TASK_ROUTING = {
    "status": "candidate_sections_only",
    "ticketRosterFormat": "grill-adapter-ticket-roster-v1",
    "fingerprintAlgorithm": "sha256:grill-adapter-task-text-v1",
    "selectedSectionsFrozen": False,
    "refreshPolicy": "refresh-taskWikiRefs-and-fingerprints-only",  # Note bindings, hashes, and routing are frozen.
}
# Declared ticket sources. Audit metadata only: the engine fingerprints whatever text the roster
# hands it and never branches on this value, reads a tracker, or touches the network.
TICKET_SOURCES = {"grill-local-scratch", "github-issues", "manual"}
HEX_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
SHA256_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
SKILL_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
SKILL_VERSION_RE = re.compile(
    r"^(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)"
    r"(?:-(?:0|[1-9][0-9]*|[A-Za-z-][0-9A-Za-z-]*)"
    r"(?:\.(?:0|[1-9][0-9]*|[A-Za-z-][0-9A-Za-z-]*))*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)
V6_NOTE_TYPES = {"constraint", "domain", "decision", "guide"}
V6_ROLES = {"project", "shared"}
V6_REQUIRED_SKILL_ROLES = {"implementer", "reviewer"}
ADR_SOURCE_ID_RE = re.compile(r"^project-adr:[a-f0-9]{64}$")
# A digest of 64 identical hex chars (0000…, 1111…, ffff…) is an authoring placeholder, never a
# real sha256. Rejecting it stops copy-pasted skeleton fingerprints from passing validation and
# only blowing up later at the execution-side --fingerprint-preflight.
PLACEHOLDER_FINGERPRINT_RE = re.compile(r"^([0-9a-f])\1{63}$")


class ValidationError(Exception):
    pass


class FingerprintError(Exception):
    pass


def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass


def _as_list(value: Any, field: str) -> list[Any]:
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValidationError(f"{field} must be a list")
    return value


def _as_dict(value: Any, field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValidationError(f"{field} must be an object")
    return value


def _load_json(path: Path, label: str) -> dict[str, Any]:
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValidationError(f"Cannot read {label}: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValidationError(f"Invalid JSON in {label}: {exc}") from exc
    return _as_dict(data, label)


def _load_context(path: Path) -> dict[str, Any]:
    if path.suffix == ".md":
        raise ValidationError("Legacy .wiki-context.md is not supported; create a schemaVersion 6 Obsidian sidecar.")
    return _load_json(path, "wiki context")


def _validate_task_fingerprint(task_ref: dict[str, Any], field: str) -> None:
    fingerprint = task_ref.get("taskFingerprint")
    if not isinstance(fingerprint, str) or not HEX_SHA256_RE.match(fingerprint):
        raise ValidationError(f"{field}.taskFingerprint must be a 64-character lowercase sha256 hex digest")
    if PLACEHOLDER_FINGERPRINT_RE.match(fingerprint):
        raise ValidationError(
            f"{field}.taskFingerprint looks like a placeholder; run --bind-fingerprints --ticket-roster <roster> to stamp the real fingerprint"
        )


def _validate_v6_note(
    note: Any,
    field: str,
    require_skill: bool = False,
    allow_destination: bool = False,
    project_root: Path | None = None,
) -> dict[str, Any]:
    value = _as_dict(note, field)
    allowed_fields = {
        "sourceId", "role", "path", "wikiId", "type", "summary", "bindingDigest", "contentHash",
        "adrSourceId", "adrSourcePath", "adrSourceContentHash",
        *(
            (
                "requiredFor",
                "skillProvider",
                "skillName",
                "skillVersion",
                "skillContractHash",
                "skillTriggers",
                "discoveryState",
            )
            if require_skill
            else ("constraintStrength",)
        ),
        *( ("destination",) if allow_destination else () ),
    }
    unknown_fields = sorted(set(value) - allowed_fields)
    if unknown_fields:
        raise ValidationError(f"{field} contains unsupported fields: {', '.join(unknown_fields)}")
    for key in ("sourceId", "path", "wikiId", "summary", "bindingDigest", "contentHash"):
        if not isinstance(value.get(key), str) or not value[key].strip():
            raise ValidationError(f"{field}.{key} must be a non-empty string")
    if value.get("role") not in V6_ROLES:
        raise ValidationError(f"{field}.role must be one of {', '.join(sorted(V6_ROLES))}")
    if value.get("type") not in V6_NOTE_TYPES:
        raise ValidationError(f"{field}.type must be one of {', '.join(sorted(V6_NOTE_TYPES))}")
    if not HEX_SHA256_RE.match(value["bindingDigest"]):
        raise ValidationError(f"{field}.bindingDigest must be a 64-character sha256 digest")
    if not SHA256_RE.match(value["contentHash"]):
        raise ValidationError(f"{field}.contentHash must be a sha256 digest")
    adr_values = [value.get("adrSourceId"), value.get("adrSourcePath"), value.get("adrSourceContentHash")]
    if any(item is not None for item in adr_values):
        if require_skill:
            raise ValidationError(f"{field} Skill Cards must not carry ADR execution projection identity")
        if any(not isinstance(item, str) or not item.strip() for item in adr_values):
            raise ValidationError(f"{field} ADR identity must include adrSourceId, adrSourcePath, and adrSourceContentHash together")
        if value.get("role") != "project":
            raise ValidationError(f"{field} ADR execution projections must use the project Source")
        if value.get("type") != "constraint" or value.get("constraintStrength") != "hard":
            raise ValidationError(f"{field} ADR execution projections must be hard constraint Notes")
        if not ADR_SOURCE_ID_RE.fullmatch(value["adrSourceId"]):
            raise ValidationError(f"{field}.adrSourceId must be project-adr:<sha256>")
        if not SHA256_RE.fullmatch(value["adrSourceContentHash"]):
            raise ValidationError(f"{field}.adrSourceContentHash must be a sha256 digest")
        try:
            expected_id = source_id_for_path(value["adrSourcePath"])
        except AdrIdentityError as exc:
            raise ValidationError(f"{field}.adrSourcePath is invalid: {exc}") from exc
        if value["adrSourceId"] != expected_id:
            raise ValidationError(f"{field}.adrSourceId does not match adrSourcePath")
        if project_root is not None:
            try:
                validate_identity(
                    project_root,
                    value["adrSourceId"],
                    value["adrSourcePath"],
                    value["adrSourceContentHash"],
                )
            except AdrIdentityError as exc:
                raise ValidationError(f"{field} ADR authority validation failed: {exc}") from exc
    if "content" in value:
        raise ValidationError(f"{field}.content is not allowed; schemaVersion 6 carries Note metadata only")
    if require_skill:
        roles = _as_list(value.get("requiredFor"), f"{field}.requiredFor")
        if (
            not roles
            or len(roles) != len(set(roles))
            or any(role not in V6_REQUIRED_SKILL_ROLES for role in roles)
        ):
            raise ValidationError(
                f"{field}.requiredFor must be a non-empty unique subset of "
                f"{sorted(V6_REQUIRED_SKILL_ROLES)}"
            )
        if value.get("skillProvider") != "claude-code-project":
            raise ValidationError(f"{field}.skillProvider must be claude-code-project")
        if not isinstance(value.get("skillName"), str) or not SKILL_NAME_RE.fullmatch(value["skillName"]):
            raise ValidationError(f"{field}.skillName must use kebab-case")
        if not isinstance(value.get("skillVersion"), str) or not SKILL_VERSION_RE.fullmatch(value["skillVersion"]):
            raise ValidationError(
                f"{field}.skillVersion must be a semantic major.minor.patch version"
            )
        if not SHA256_RE.match(str(value.get("skillContractHash", ""))):
            raise ValidationError(f"{field}.skillContractHash must be a sha256 digest")
        triggers = _as_list(value.get("skillTriggers"), f"{field}.skillTriggers")
        if (
            not triggers
            or any(not isinstance(trigger, str) or not trigger.strip() for trigger in triggers)
            or len(set(triggers)) != len(triggers)
        ):
            raise ValidationError(f"{field}.skillTriggers must be a non-empty unique string array")
        if value.get("discoveryState") != "discoverable":
            raise ValidationError(f"{field}.discoveryState must be discoverable")
    elif value.get("constraintStrength") not in ("hard", "soft", None):
        raise ValidationError(f"{field}.constraintStrength must be hard or soft when present")
    return value


def _validate_v6_execution_ready(data: dict[str, Any]) -> None:
    task_routing = _as_dict(data.get("taskRouting"), "taskRouting")
    if task_routing.get("status") != "confirmed":
        raise ValidationError("taskRouting.status must be confirmed for execution-ready wiki context")
    if task_routing.get("selectedSectionsFrozen") is not True:
        raise ValidationError("taskRouting.selectedSectionsFrozen must be true for execution-ready wiki context")
    task_refs = _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
    task_ids: set[str] = set()
    for index, task_ref in enumerate(task_refs):
        task = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task.get("taskId")
        if not isinstance(task_id, str) or not task_id.strip() or task_id in task_ids:
            raise ValidationError(f"taskWikiRefs[{index}].taskId must be a unique non-empty task id")
        task_ids.add(task_id)
        if not isinstance(task.get("taskTitle"), str) or not task["taskTitle"].strip():
            raise ValidationError(f"taskWikiRefs[{index}].taskTitle is required")
        _validate_task_fingerprint(task, f"taskWikiRefs[{index}]")
    for collection in ("wikiNotes", "requiredSkills"):
        for index, raw_note in enumerate(_as_list(data.get(collection), collection)):
            note = _as_dict(raw_note, f"{collection}[{index}]")
            destination = _as_dict(note.get("destination"), f"{collection}[{index}].destination")
            kind = destination.get("kind")
            if kind not in DESTINATION_KINDS:
                raise ValidationError(f"{collection}[{index}].destination.kind must be one of {', '.join(sorted(DESTINATION_KINDS))}")
            if not isinstance(destination.get("reason"), str) or not destination["reason"].strip():
                raise ValidationError(f"{collection}[{index}].destination.reason is required")
            if collection == "wikiNotes" and note.get("constraintStrength") == "hard" and kind == "planning-only":
                raise ValidationError(f"hard Note {note.get('wikiId')} cannot have planning-only destination")
            tasks = destination.get("tasks")
            if kind == "task-bound":
                task_list = _as_list(tasks, f"{collection}[{index}].destination.tasks")
                if not task_list or any(not isinstance(task_id, str) or not task_id.strip() or task_id not in task_ids for task_id in task_list):
                    raise ValidationError(f"{collection}[{index}].destination.tasks must name known task ids")
                if len(set(task_list)) != len(task_list):
                    raise ValidationError(f"{collection}[{index}].destination.tasks must not duplicate task ids")
            elif tasks:
                raise ValidationError(f"{collection}[{index}].destination.tasks is only valid for task-bound routing")


def _validate_execution_ready(data: dict[str, Any]) -> None:
    _validate_v6_execution_ready(data)


def _validate_v6_context(
    data: dict[str, Any],
    execution_ready: bool,
    project_root: Path | None = None,
) -> list[str]:
    if data.get("kind") != KIND:
        raise ValidationError(f"kind must be {KIND}")
    if not isinstance(data.get("featureSlug"), str) or not data["featureSlug"].strip():
        raise ValidationError("schemaVersion 6 wiki context requires a non-empty featureSlug")
    snapshot = data.get("snapshotHash")
    if not isinstance(snapshot, str) or not SHA256_RE.match(snapshot):
        raise ValidationError("snapshotHash must be a sha256 digest")
    bindings = _as_list(data.get("wikiBindings"), "wikiBindings")
    binding_digests: dict[str, str] = {}
    binding_roles: dict[str, str] = {}
    for index, raw_binding in enumerate(bindings):
        binding = _as_dict(raw_binding, f"wikiBindings[{index}]")
        source_id = binding.get("sourceId")
        if not isinstance(source_id, str) or not source_id.strip() or source_id in binding_digests:
            raise ValidationError(f"wikiBindings[{index}].sourceId must be a unique non-empty string")
        if binding.get("role") not in V6_ROLES:
            raise ValidationError(f"wikiBindings[{index}].role must be one of {', '.join(sorted(V6_ROLES))}")
        digest = binding.get("bindingDigest")
        if not isinstance(digest, str) or not HEX_SHA256_RE.match(digest):
            raise ValidationError(f"wikiBindings[{index}].bindingDigest must be a 64-character sha256 digest")
        binding_digests[source_id] = digest
        binding_roles[source_id] = binding["role"]
    if not binding_digests:
        raise ValidationError("wikiBindings must contain one or more bound Sources")
    seen_ids: set[str] = set()
    seen_adr_sources: set[str] = set()
    for collection, is_skill in (("wikiNotes", False), ("requiredSkills", True)):
        for index, raw_note in enumerate(_as_list(data.get(collection), collection)):
            note = _validate_v6_note(
                raw_note,
                f"{collection}[{index}]",
                require_skill=is_skill,
                allow_destination=True,
                project_root=project_root,
            )
            if note["wikiId"] in seen_ids:
                raise ValidationError(f"{collection}[{index}] duplicates wikiId {note['wikiId']}")
            seen_ids.add(note["wikiId"])
            if binding_digests.get(note["sourceId"]) != note["bindingDigest"]:
                raise ValidationError(f"{collection}[{index}] does not match a declared Source binding digest")
            if binding_roles.get(note["sourceId"]) != note["role"]:
                raise ValidationError(f"{collection}[{index}] does not match the declared Source binding role")
            adr_source_id = note.get("adrSourceId")
            if adr_source_id:
                if adr_source_id in seen_adr_sources:
                    raise ValidationError(f"{collection}[{index}] duplicates ADR authority identity {adr_source_id}")
                seen_adr_sources.add(adr_source_id)
    if "wikiPages" in data or "sharedWiki" in data:
        raise ValidationError("schemaVersion 6 uses wikiNotes/wikiBindings, not wikiPages/sharedWiki")
    _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
    _as_dict(data.get("taskRouting"), "taskRouting")
    if "caveats" in data:
        _as_list(data.get("caveats"), "caveats")
    if "maintenanceWarnings" in data:
        _as_list(data.get("maintenanceWarnings"), "maintenanceWarnings")
    if execution_ready:
        _validate_execution_ready(data)
    return []


def _validate_context(
    data: dict[str, Any],
    strict: bool,
    execution_ready: bool = False,
    project_root: Path | None = None,
) -> list[str]:
    schema_version = data.get("schemaVersion")
    if schema_version not in SUPPORTED_SCHEMA_VERSIONS:
        raise ValidationError("schemaVersion must be 6; legacy contexts are migration input only and cannot be executed")
    return _validate_v6_context(data, execution_ready, project_root)


def _v6_task_notes(data: dict[str, Any], task_id: str | None, role: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    if task_id:
        matches = [
            _as_dict(task_ref, "taskWikiRefs[]")
            for task_ref in _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
            if _as_dict(task_ref, "taskWikiRefs[]").get("taskId") == task_id
        ]
        if len(matches) != 1:
            raise ValidationError(f"taskWikiRefs must contain exactly one entry for taskId {task_id}")

    def routed(note: dict[str, Any]) -> bool:
        destination = _as_dict(note.get("destination"), "Note destination")
        if destination.get("kind") == "global":
            return True
        return task_id is not None and destination.get("kind") == "task-bound" and task_id in _as_list(destination.get("tasks"), "destination.tasks")

    notes = [
        _as_dict(note, "wikiNotes[]")
        for note in _as_list(data.get("wikiNotes"), "wikiNotes")
        if routed(_as_dict(note, "wikiNotes[]"))
    ]
    skills = [
        _as_dict(skill, "requiredSkills[]")
        for skill in _as_list(data.get("requiredSkills"), "requiredSkills")
        if role in _as_list(_as_dict(skill, "requiredSkills[]").get("requiredFor"), "requiredSkills[].requiredFor")
        and routed(_as_dict(skill, "requiredSkills[]"))
    ]
    return notes, skills


def _render_v6_markdown(data: dict[str, Any], role: str, task_id: str | None) -> str:
    notes, skills = _v6_task_notes(data, task_id, role)
    if not notes and not skills:
        if task_id:
            return f"No selected wiki constraints for task `{task_id}` and role `{role}`."
        return "No selected wiki constraints for this role."
    lines = ["## Wiki Constraints", ""]
    if task_id:
        lines.extend([f"- Task ID: `{task_id}`", ""])
    for note in notes:
        strength = note.get("constraintStrength") or "context"
        lines.append(f"### `{note['wikiId']}` · {strength}")
        lines.append(f"- Summary: {note['summary']}")
        lines.append(f"- Note: `{note['path']}`")
        lines.append("")
    if skills:
        lines.extend(["### Required Skill Cards", ""])
        for skill in skills:
            lines.append(f"- `{skill['wikiId']}`: {skill['summary']} (`{skill['path']}`)")
        lines.append("")
    for caveat in _as_list(data.get("caveats"), "caveats"):
        lines.append(f"- Context caveat: {caveat}")
    return "\n".join(lines).rstrip()


def render_markdown(data: dict[str, Any], role: str, task_id: str | None = None) -> str:
    return _render_v6_markdown(data, role, task_id)


def reread_entries(data: dict[str, Any], role: str = "implementer", task_id: str | None = None) -> list[dict[str, Any]]:
    """Return task-scoped hard Obsidian Note metadata as JSONL-ready entries."""
    notes, _ = _v6_task_notes(data, task_id, role)
    return [
        {
            "sourceId": note["sourceId"],
            "role": note["role"],
            "path": note["path"],
            "wikiId": note["wikiId"],
            "contentHash": note["contentHash"],
            "bindingDigest": note["bindingDigest"],
            "summary": note["summary"],
        }
        for note in notes
        if note.get("constraintStrength") == "hard"
    ]


def render_reread_list(data: dict[str, Any], role: str = "implementer", task_id: str | None = None) -> str:
    entries = reread_entries(data, role, task_id)
    lines = [json.dumps(entry, ensure_ascii=False, sort_keys=True) for entry in entries]
    if lines:
        return "\n".join(lines)
    if task_id:
        return f"No hard-constraint rereads for task `{task_id}`."
    return "No hard-constraint rereads for selected wiki context."


def _normalize_task_text(task_text: str) -> str:
    lines = task_text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    lines = [line.rstrip() for line in lines]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


def _task_fingerprint(task_text: str) -> str:
    normalized = _normalize_task_text(task_text)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def load_ticket_roster(
    roster_path: Path,
    expected_feature_slug: str | None = None,
) -> dict[str, dict[str, str]]:
    """Load the host-produced ticket roster: the task identity + fingerprint source of truth.

    This is the host-agnostic boundary. The engine never reads a tracker, a plan document, or the
    network -- it fingerprints exactly the text it is handed. Each host's convention block tells the
    agent how to fill the roster (grill local-markdown reads `.scratch/<slug>/issues/<NN>-<slug>.md`,
    grill GitHub runs `gh issue view`, plain takes a user-specified source), so a new host needs a
    convention block and no engine change.

    Returns the same shape the renderer's fingerprint/scaffold paths consume: taskId -> title/text/hash.
    """
    # _load_json already rejects a non-object (as ValidationError) and unreadable/invalid JSON.
    raw = _load_json(roster_path, "ticket roster")
    source = raw.get("ticketSource")
    if source is not None and source not in TICKET_SOURCES:
        raise FingerprintError(f"Unknown ticketSource {source!r}; expected one of {', '.join(sorted(TICKET_SOURCES))}")
    roster_feature_slug = raw.get("featureSlug")
    if expected_feature_slug is not None:
        if not isinstance(expected_feature_slug, str) or not expected_feature_slug.strip():
            raise FingerprintError("wiki context requires a non-empty featureSlug to bind a ticket roster")
        if not isinstance(roster_feature_slug, str) or not roster_feature_slug.strip():
            raise FingerprintError("ticket roster requires a non-empty featureSlug matching the wiki context")
        if roster_feature_slug != expected_feature_slug:
            raise FingerprintError(
                f"ticket roster featureSlug {roster_feature_slug!r} does not match wiki context featureSlug {expected_feature_slug!r}"
            )
    entries = raw.get("tickets")
    if not isinstance(entries, list) or not entries:
        raise FingerprintError("Ticket roster has no tickets; expected a non-empty `tickets` array")

    tasks: dict[str, dict[str, str]] = {}
    for index, entry in enumerate(entries):
        ticket = _as_dict(entry, f"tickets[{index}]")
        task_id = ticket.get("taskId")
        if not isinstance(task_id, str) or not task_id.strip():
            raise FingerprintError(f"tickets[{index}] missing a non-empty taskId")
        task_id = task_id.strip()
        if task_id in tasks:
            raise FingerprintError(f"Duplicate taskId in ticket roster: {task_id}")
        text = ticket.get("text")
        if not isinstance(text, str) or not text.strip():
            raise FingerprintError(f"tickets[{index}] (taskId {task_id}) missing non-empty text to fingerprint")
        title = ticket.get("taskTitle")
        if not isinstance(title, str) or not title.strip():
            raise FingerprintError(f"tickets[{index}] (taskId {task_id}) missing a non-empty taskTitle")
        tasks[task_id] = {"title": title.strip(), "text": text, "hash": _task_fingerprint(text)}
    return tasks


def fingerprint_preflight(data: dict[str, Any], roster_path: Path) -> str:
    roster_tasks = load_ticket_roster(roster_path, data.get("featureSlug"))
    sidecar_tasks: dict[str, dict[str, Any]] = {}
    errors: list[str] = []
    for index, task_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        task_obj = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task_obj.get("taskId")
        if not isinstance(task_id, str) or not task_id:
            errors.append(f"taskWikiRefs[{index}] missing taskId")
            continue
        if task_id in sidecar_tasks:
            errors.append(f"duplicate sidecar taskId: {task_id}")
            continue
        sidecar_tasks[task_id] = task_obj

    for task_id, task in roster_tasks.items():
        sidecar = sidecar_tasks.get(task_id)
        if not sidecar:
            errors.append(f"roster ticket missing from taskWikiRefs: {task_id}")
            continue
        fingerprint = sidecar.get("taskFingerprint")
        if fingerprint != task["hash"]:
            errors.append(f"fingerprint mismatch for {task_id}: expected {fingerprint}, current {task['hash']}")

    for task_id in sorted(set(sidecar_tasks) - set(roster_tasks)):
        errors.append(f"taskWikiRefs contains task not found in the ticket roster: {task_id}")

    if errors:
        raise FingerprintError("\n".join(errors))
    return f"fingerprint preflight passed for {len(roster_tasks)} task(s)"


def bind_fingerprints(data: dict[str, Any], roster_path: Path) -> tuple[int, int, list[str]]:
    """Stamp each taskWikiRefs entry's taskFingerprint from the current ticket roster text.

    Routing (which sections bind to which task) stays author-owned; only the mechanical sha256 of
    the normalized ticket text is (re)written here, from the single source of truth in this
    module. Mirrors fingerprint_preflight's structural checks and refuses to write on any mismatch,
    so a successful bind guarantees the execution-side --fingerprint-preflight will pass.
    """
    roster_tasks = load_ticket_roster(roster_path, data.get("featureSlug"))
    sidecar_tasks: dict[str, dict[str, Any]] = {}
    errors: list[str] = []
    for index, task_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        task_obj = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task_obj.get("taskId")
        if not isinstance(task_id, str) or not task_id:
            errors.append(f"taskWikiRefs[{index}] missing taskId")
            continue
        if task_id in sidecar_tasks:
            errors.append(f"duplicate sidecar taskId: {task_id}")
            continue
        sidecar_tasks[task_id] = task_obj

    for task_id in sorted(set(sidecar_tasks) - set(roster_tasks)):
        errors.append(f"taskWikiRefs contains task not found in the ticket roster: {task_id}")
    for task_id in roster_tasks:
        if task_id not in sidecar_tasks:
            errors.append(f"roster ticket missing from taskWikiRefs: {task_id}")
    if errors:
        raise FingerprintError("\n".join(errors))

    changed = 0
    for task_id, task_obj in sidecar_tasks.items():
        current_hash = roster_tasks[task_id]["hash"]
        if task_obj.get("taskFingerprint") != current_hash:
            task_obj["taskFingerprint"] = current_hash
            changed += 1
    return len(sidecar_tasks), changed, sorted(sidecar_tasks)


def _scaffold_v6_destination(note: dict[str, Any], is_skill: bool = False) -> None:
    hard = not is_skill and note.get("constraintStrength") == "hard"
    note["destination"] = {"kind": "task-bound" if hard or is_skill else "planning-only", "reason": ""}
    if note["destination"]["kind"] == "task-bound":
        note["destination"]["tasks"] = []


def _scaffold_v6_from_selection(selection: dict[str, Any], feature_slug: str | None, ticket_source: str | None) -> dict[str, Any]:
    bindings = [_as_dict(binding, "selection.wikiBindings[]") for binding in _as_list(selection.get("wikiBindings"), "selection.wikiBindings")]
    notes = [_validate_v6_note(note, "selection.wikiNotes[]") for note in _as_list(selection.get("wikiNotes"), "selection.wikiNotes")]
    skills = [_validate_v6_note(skill, "selection.requiredSkills[]", require_skill=True) for skill in _as_list(selection.get("requiredSkills"), "selection.requiredSkills")]
    data: dict[str, Any] = {
        "schemaVersion": SCHEMA_VERSION,
        "kind": KIND,
        "generatedBy": SCAFFOLD_GENERATED_BY,
        "snapshotHash": selection.get("snapshotHash"),
        "wikiBindings": bindings,
        "wikiNotes": [dict(note) for note in notes],
        "requiredSkills": [dict(skill) for skill in skills],
        "taskRouting": dict(SCAFFOLD_TASK_ROUTING),
        "taskWikiRefs": [],
        "caveats": _as_list(selection.get("caveats"), "selection.caveats") if "caveats" in selection else [],
        "maintenanceWarnings": _as_list(selection.get("maintenanceWarnings"), "selection.maintenanceWarnings") if "maintenanceWarnings" in selection else [],
    }
    if feature_slug:
        data["featureSlug"] = feature_slug
    if ticket_source:
        data["ticketSource"] = ticket_source
    for note in data["wikiNotes"]:
        _scaffold_v6_destination(note)
    for skill in data["requiredSkills"]:
        _scaffold_v6_destination(skill, is_skill=True)
    return data


def scaffold_from_selection(
    selection: dict[str, Any], feature_slug: str | None, ticket_source: str | None
) -> dict[str, Any]:
    """Build a schema-v6 sidecar skeleton from a bound Obsidian metadata selection.

    The generator carries only binding, Note identity, path, hash, summary, and declared Skill Card
    roles. It adds task routing plus default destinations; the author then supplies routing reasons and
    task-bound task ids. taskWikiRefs remain empty until the host-produced ticket roster is finalized.
    """
    if ticket_source is not None and ticket_source not in TICKET_SOURCES:
        raise ValidationError(f"Unknown ticketSource {ticket_source!r}; expected one of {', '.join(sorted(TICKET_SOURCES))}")
    if selection.get("phase") != "plan":
        raise ValidationError("Obsidian selection.phase must be plan before Carry can scaffold a sidecar")
    if selection.get("status") not in {"ok", "partial"}:
        raise ValidationError("Obsidian selection.status must be ok or partial before Carry can scaffold a sidecar")
    if not any(key in selection for key in ("wikiNotes", "wikiBindings", "requiredSkills")):
        raise ValidationError(
            "Obsidian selection must contain wikiNotes, wikiBindings, or requiredSkills"
        )
    return _scaffold_v6_from_selection(selection, feature_slug, ticket_source)


def scaffold_tasks(data: dict[str, Any], roster_path: Path) -> tuple[list[str], list[str]]:
    """Scaffold one taskWikiRefs entry per roster ticket (the task roster + fingerprint anchor).

    taskId/taskTitle come mechanically from the ticket roster (load_ticket_roster). Any prior
    taskFingerprint/caveats are preserved for surviving tasks so re-running after a ticket edit is
    idempotent; tasks no longer in the roster are dropped and reported. taskFingerprint is never stamped
    here -- that stays --bind-fingerprints' single responsibility. Section->task routing is NOT touched
    here: it lives on each section's destination.tasks, independent of this roster.
    """
    roster_tasks = load_ticket_roster(roster_path, data.get("featureSlug"))
    existing: dict[str, dict[str, Any]] = {}
    for index, raw_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        ref = _as_dict(raw_ref, f"taskWikiRefs[{index}]")
        task_id = ref.get("taskId")
        if isinstance(task_id, str) and task_id:
            existing[task_id] = ref

    new_refs: list[dict[str, Any]] = []
    for task_id, task in roster_tasks.items():
        prev = existing.get(task_id)
        ref: dict[str, Any] = {"taskId": task_id, "taskTitle": task["title"]}
        if prev and prev.get("taskFingerprint"):
            ref["taskFingerprint"] = prev["taskFingerprint"]
        if prev and prev.get("caveats"):
            ref["caveats"] = prev["caveats"]
        new_refs.append(ref)

    dropped = sorted(set(existing) - set(roster_tasks))
    data["taskWikiRefs"] = new_refs
    return list(roster_tasks), dropped


def _write_context(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    tmp = path.with_name(path.name + ".tmp")
    # Pin LF so the sidecar is byte-deterministic across platforms (Windows text mode
    # would otherwise translate "\n" to "\r\n" and churn against an LF-committed file).
    with tmp.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    tmp.replace(path)


def main() -> int:
    _configure_stdio()
    parser = argparse.ArgumentParser(description="Validate and render schemaVersion 6 Obsidian wiki context JSON.")
    parser.add_argument("context_path", help="Path to .adapter/context/<feature-slug>.wiki-context.json")
    parser.add_argument("--task-id", help="Render only wiki refs bound to the finalized ticket id, plus global refs")
    parser.add_argument("--ticket-roster", help="Path to the host-produced ticket roster JSON (.adapter/context/<feature-slug>.ticket-roster.json) used as the task identity + fingerprint source")
    parser.add_argument("--project-root", help="Project root used to revalidate ADR projection authority (defaults to the current directory)")
    parser.add_argument("--feature-slug", help="With --scaffold, the feature identity stamped into the sidecar")
    parser.add_argument("--ticket-source", choices=sorted(TICKET_SOURCES), help="With --scaffold, records where the roster's tickets came from (audit metadata; the engine never branches on it)")
    parser.add_argument("--execution-ready", action="store_true", help="Require confirmed taskRouting and per-section destination routing suitable for execution")
    parser.add_argument("--fingerprint-preflight", action="store_true", help="Compare taskWikiRefs fingerprints against the current ticket roster text")
    parser.add_argument("--bind-fingerprints", action="store_true", help="Stamp taskWikiRefs taskFingerprint values from the current ticket roster text and write the sidecar in place (requires --ticket-roster)")
    parser.add_argument("--role", choices=["implementer", "reviewer"], default="implementer")
    parser.add_argument("--format", choices=["markdown"], default="markdown")
    parser.add_argument("--validate-only", action="store_true")
    parser.add_argument("--reread-list", action="store_true")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--scaffold", metavar="SELECTION_JSON", help="Generate a sidecar skeleton from a wiki-researcher selection JSON and write it to the positional context path")
    parser.add_argument("--keep-selection", action="store_true", help="With --scaffold, keep the consumed selection JSON instead of removing it on success (for tests/debugging, or to regenerate from an edited selection)")
    parser.add_argument("--scaffold-tasks", action="store_true", help="Scaffold the taskWikiRefs roster (taskId/taskTitle) from the ticket roster into the existing sidecar, preserving any prior taskFingerprint (requires --ticket-roster)")
    parser.add_argument("--finalize", action="store_true", help="One-shot planning finalize after the single destination edit pass: scaffold the taskWikiRefs roster from the ticket roster, stamp every taskFingerprint, validate execution readiness, and write the sidecar once (requires --ticket-roster). Combines --scaffold-tasks + --bind-fingerprints into a single write.")
    args = parser.parse_args()
    project_root = Path(args.project_root).resolve() if args.project_root else Path.cwd().resolve()

    try:
        if args.scaffold and args.scaffold_tasks:
            raise ValidationError("Run --scaffold and --scaffold-tasks in separate invocations: --scaffold builds the sidecar from a selection, --scaffold-tasks adds task routing once the ticket roster exists")
        if args.finalize and (args.scaffold or args.scaffold_tasks or args.bind_fingerprints):
            raise ValidationError("--finalize already runs scaffold-tasks + bind-fingerprints in one write; do not combine it with --scaffold, --scaffold-tasks, or --bind-fingerprints")
        if args.scaffold:
            selection_path = Path(args.scaffold)
            selection = _load_json(selection_path, "wiki selection")
            data = scaffold_from_selection(selection, args.feature_slug, args.ticket_source)
            _validate_context(data, args.strict, execution_ready=False, project_root=project_root)
            context_path = Path(args.context_path)
            _write_context(context_path, data)
            selected_count = len(data["wikiNotes"])
            summary = f"scaffolded wiki context with {selected_count} Note(s) -> {args.context_path}"
            # The selection is a transient intermediate: scaffolding is its only consumer (execution reads
            # the generated sidecar, never the selection). Remove it on success so only the plan and its
            # .wiki-context.json persist. A malformed selection raises above before this write, so a failed
            # scaffold always keeps the selection for repair. --keep-selection opts out (tests/debugging,
            # or to regenerate from an edited selection).
            if args.keep_selection:
                print(f"{summary} (kept selection {selection_path})")
            elif selection_path.resolve() == context_path.resolve():
                print(f"{summary} (selection path equals context path; not removed)")
            else:
                try:
                    selection_path.unlink()
                    print(f"{summary}; removed consumed selection {selection_path}")
                except OSError as exc:
                    print(f"Warning: scaffolded the sidecar but could not remove selection {selection_path}: {exc}", file=sys.stderr)
                    print(summary)
            return 0
        data = _load_context(Path(args.context_path))
        if args.finalize:
            if not args.ticket_roster:
                raise ValidationError("--finalize requires --ticket-roster")
            # Single transactional finalize for the planning flow, run once after the author's lone
            # destination edit pass: refresh the task roster from the ticket roster (idempotent,
            # preserving prior fingerprints), validate structure, stamp every taskFingerprint from the
            # current ticket text, then confirm the result is fully execution-ready before the one
            # write. Combining scaffold-tasks + bind into a single write means the planning agent's
            # Read-tracked sidecar is re-surfaced once here instead of after two separate rewrites.
            task_ids, dropped = scaffold_tasks(data, Path(args.ticket_roster))
            _validate_context(data, args.strict, execution_ready=False, project_root=project_root)
            total, changed, _ = bind_fingerprints(data, Path(args.ticket_roster))
            _validate_context(data, args.strict, execution_ready=True, project_root=project_root)
            _write_context(Path(args.context_path), data)
            for task_id in dropped:
                print(f"Warning: dropped taskWikiRefs entry no longer in the ticket roster: {task_id}", file=sys.stderr)
            status = f"{changed} updated" if changed else "already current"
            print(f"finalized {total} task(s) ({status}): {', '.join(task_ids)}")
            return 0
        if args.scaffold_tasks:
            if not args.ticket_roster:
                raise ValidationError("--scaffold-tasks requires --ticket-roster")
            task_ids, dropped = scaffold_tasks(data, Path(args.ticket_roster))
            _validate_context(data, args.strict, execution_ready=False, project_root=project_root)
            _write_context(Path(args.context_path), data)
            for task_id in dropped:
                print(f"Warning: dropped taskWikiRefs entry no longer in the ticket roster: {task_id}", file=sys.stderr)
            print(f"scaffolded {len(task_ids)} task(s): {', '.join(task_ids)}")
            return 0
        if args.bind_fingerprints:
            if not args.ticket_roster:
                raise ValidationError("--bind-fingerprints requires --ticket-roster")
            # Validate structure but tolerate missing/placeholder fingerprints; stamping fixes them.
            _validate_context(data, args.strict, execution_ready=False, project_root=project_root)
            total, changed, task_ids = bind_fingerprints(data, Path(args.ticket_roster))
            # With real fingerprints stamped, confirm the result is fully execution-ready before
            # writing, so a successful bind is transactional (correct fingerprints + valid routing).
            if args.execution_ready:
                _validate_context(data, args.strict, execution_ready=True, project_root=project_root)
            _write_context(Path(args.context_path), data)
            status = f"{changed} updated" if changed else "already current"
            print(f"bound taskFingerprint for {total} task(s) ({status}): {', '.join(task_ids)}")
            return 0
        caveats = _validate_context(data, args.strict, args.execution_ready, project_root)
        if args.fingerprint_preflight:
            if not args.ticket_roster:
                raise ValidationError("--fingerprint-preflight requires --ticket-roster")
            print(fingerprint_preflight(data, Path(args.ticket_roster)))
            return 0
        if args.validate_only:
            # --ticket-roster alone cannot catch stale fingerprints in validate-only mode (format-only),
            # so when execution-ready validation is requested with a roster, run the same fingerprint
            # preflight execution uses. This closes the gap where placeholder/stale fingerprints
            # passed planning validation and only failed later at dispatch time.
            if args.execution_ready and args.ticket_roster:
                fingerprint_preflight(data, Path(args.ticket_roster))
            for caveat in caveats:
                print(f"Warning: {caveat}", file=sys.stderr)
            print("wiki context JSON is valid")
            return 0
        if args.reread_list:
            print(render_reread_list(data, args.role, args.task_id))
            return 0
        print(render_markdown(data, args.role, args.task_id))
        return 0
    except (ValidationError, FingerprintError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
