#!/usr/bin/env python3
"""Generated by grill-adapter."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from wiki_context_render import FingerprintError, ValidationError, load_ticket_roster


KIND = "grill-adapter.wiki-readiness"
SCHEMA_VERSION = 1
GENERATED_BY = "grill-adapter"
STATUS_DISPOSITIONS = {
    "ready": "materialized",
    "no-relevant": "none",
    "disabled": "none",
    "broken": "discarded",
}


class ReadinessError(Exception):
    pass


def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")


def _load_json(path: Path, label: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ReadinessError(f"Could not read {label} {path}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ReadinessError(f"Invalid JSON in {label} {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ReadinessError(f"{label} must be a JSON object")
    return value


def _write_json(path: Path, value: dict[str, Any]) -> None:
    text = json.dumps(value, ensure_ascii=False, indent=2) + "\n"
    _write_text(path, text)


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temp_name = handle.name
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        Path(temp_name).replace(path)
    finally:
        if temp_name:
            Path(temp_name).unlink(missing_ok=True)


def _required_text(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ReadinessError(f"{field} must be a non-empty string")
    return value


def _feature_slug(value: Any) -> str:
    slug = _required_text(value, "featureSlug").strip()
    if "/" in slug or "\\" in slug or slug in {".", ".."}:
        raise ReadinessError("featureSlug must not contain path separators")
    return slug


def _same_context_directory(reference: Path, candidate: Path, label: str) -> None:
    if reference.resolve().parent != candidate.resolve().parent:
        raise ReadinessError(f"{label} must be in the same .adapter/context directory as the readiness receipt")


def _safe_context_filename(value: Any, field: str) -> str:
    filename = _required_text(value, field)
    if Path(filename).name != filename or filename in {".", ".."}:
        raise ReadinessError(f"{field} must be a plain filename in the readiness receipt directory")
    return filename


def _roster_metadata(roster_path: Path) -> tuple[dict[str, Any], str, str, dict[str, dict[str, str]]]:
    raw = _load_json(roster_path, "ticket roster")
    feature_slug = _feature_slug(raw.get("featureSlug"))
    ticket_source = _required_text(raw.get("ticketSource"), "ticketSource").strip()
    tasks = load_ticket_roster(roster_path, feature_slug)
    return raw, feature_slug, ticket_source, tasks


def _write_single_task_roster(
    roster_path: Path,
    feature_slug: str,
    ticket_source: str,
    task_id: str,
    task_title: str,
    task_text: str,
) -> None:
    roster = {
        "featureSlug": _feature_slug(feature_slug),
        "ticketSource": ticket_source,
        "tickets": [
            {
                "taskId": _required_text(task_id, "taskId").strip(),
                "taskTitle": _required_text(task_title, "taskTitle").strip(),
                "text": _required_text(task_text, "text"),
            }
        ],
    }
    _write_json(roster_path, roster)


def prepare_issue(issue_json_path: Path, roster_path: Path, feature_slug: str) -> str:
    issue = _load_json(issue_json_path, "GitHub issue JSON")
    number = issue.get("number")
    if isinstance(number, bool) or not isinstance(number, (int, str)):
        raise ReadinessError("GitHub issue number must be a positive integer")
    task_id = str(number).strip()
    if not task_id.isdigit() or int(task_id) <= 0:
        raise ReadinessError("GitHub issue number must be a positive integer")
    _write_single_task_roster(
        roster_path,
        feature_slug,
        "github-issues",
        task_id,
        _required_text(issue.get("title"), "GitHub issue title"),
        _required_text(issue.get("body"), "GitHub issue body"),
    )
    return f"prepared GitHub issue task {task_id} -> {roster_path}"


def prepare_manual(task_text_path: Path, roster_path: Path, feature_slug: str, task_title: str) -> str:
    try:
        task_text = task_text_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ReadinessError(f"Could not read manual task brief {task_text_path}: {exc}") from exc
    _write_single_task_roster(
        roster_path,
        feature_slug,
        "manual",
        "manual",
        task_title,
        task_text,
    )
    return f"prepared manual task -> {roster_path}"


def _validate_context(context_path: Path, roster_path: Path) -> dict[str, Any]:
    renderer = Path(__file__).with_name("wiki_context_render.py")
    result = subprocess.run(
        [
            sys.executable,
            str(renderer),
            str(context_path),
            "--validate-only",
            "--strict",
            "--execution-ready",
            "--ticket-roster",
            str(roster_path),
        ],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "unknown validation failure"
        raise ReadinessError(f"Wiki context is not execution-ready: {detail}")
    return _load_json(context_path, "wiki context")


def _run_context_command(command: list[str], label: str) -> str:
    try:
        result = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    except OSError as exc:
        raise ReadinessError(f"{label} could not start: {exc}") from exc
    if result.returncode != 0:
        # Never include stdout here: a failed renderer/fetcher may have emitted partial context.
        detail = result.stderr.strip() or f"exit code {result.returncode}; partial stdout discarded"
        raise ReadinessError(f"{label} failed: {detail}")
    return result.stdout


def _render_and_materialize_context(
    *,
    context_path: Path,
    task_id: str,
    role: str,
    project_root: Path,
    obsidian_wiki_cmd: str | None = None,
    shared_wiki_cmd: str | None = None,
) -> tuple[str, str]:
    renderer = Path(__file__).with_name("wiki_context_render.py")
    materializer = Path(__file__).with_name("wiki_materialize_task.py")
    common_args = [
        str(context_path),
        "--task-id",
        task_id,
        "--role",
        role,
        "--strict",
        "--execution-ready",
    ]
    materialize_command = [
        sys.executable,
        str(materializer),
        *common_args,
        "--project-root",
        str(project_root),
    ]
    if obsidian_wiki_cmd:
        materialize_command.extend(["--obsidian-wiki-cmd", obsidian_wiki_cmd])
    if shared_wiki_cmd:
        materialize_command.extend(["--shared-wiki-cmd", shared_wiki_cmd])

    rendered = _run_context_command(
        [sys.executable, str(renderer), *common_args],
        f"{role.capitalize()} Wiki task rendering",
    )
    materialized = _run_context_command(
        materialize_command,
        f"{role.capitalize()} Wiki materialization",
    )
    return rendered, materialized


def _validate_context_identity(
    context: dict[str, Any],
    feature_slug: str,
    ticket_source: str,
    task_id: str,
) -> None:
    if context.get("featureSlug") != feature_slug:
        raise ReadinessError("Wiki context featureSlug does not match the ticket roster")
    if context.get("ticketSource") != ticket_source:
        raise ReadinessError("Wiki context ticketSource does not match the ticket roster")
    task_refs = context.get("taskWikiRefs")
    if not isinstance(task_refs, list) or not any(
        isinstance(item, dict) and item.get("taskId") == task_id for item in task_refs
    ):
        raise ReadinessError(f"Wiki context has no finalized taskWikiRefs entry for {task_id}")


def _validate_receipt_shape(receipt: dict[str, Any]) -> None:
    allowed = {
        "schemaVersion",
        "kind",
        "generatedBy",
        "featureSlug",
        "ticketSource",
        "rosterFile",
        "tasks",
    }
    unknown = sorted(set(receipt) - allowed)
    if unknown:
        raise ReadinessError(f"readiness receipt contains unsupported fields: {', '.join(unknown)}")
    if receipt.get("schemaVersion") != SCHEMA_VERSION:
        raise ReadinessError(f"readiness receipt schemaVersion must be {SCHEMA_VERSION}")
    if receipt.get("kind") != KIND:
        raise ReadinessError(f"readiness receipt kind must be {KIND}")
    if receipt.get("generatedBy") != GENERATED_BY:
        raise ReadinessError(f"readiness receipt generatedBy must be {GENERATED_BY}")
    _feature_slug(receipt.get("featureSlug"))
    _required_text(receipt.get("ticketSource"), "ticketSource")
    _safe_context_filename(receipt.get("rosterFile"), "rosterFile")
    if not isinstance(receipt.get("tasks"), list) or not receipt["tasks"]:
        raise ReadinessError("readiness receipt tasks must be a non-empty array")


def _validate_task_entry(task: Any) -> dict[str, Any]:
    if not isinstance(task, dict):
        raise ReadinessError("readiness receipt task must be an object")
    allowed = {
        "taskId",
        "taskTitle",
        "taskFingerprint",
        "status",
        "contextDisposition",
        "reason",
        "contextFile",
    }
    unknown = sorted(set(task) - allowed)
    if unknown:
        raise ReadinessError(f"readiness task contains unsupported fields: {', '.join(unknown)}")
    _required_text(task.get("taskId"), "taskId")
    _required_text(task.get("taskTitle"), "taskTitle")
    fingerprint = _required_text(task.get("taskFingerprint"), "taskFingerprint")
    if len(fingerprint) != 64 or any(char not in "0123456789abcdef" for char in fingerprint):
        raise ReadinessError("taskFingerprint must be a 64-character lowercase sha256 digest")
    status = task.get("status")
    if status not in STATUS_DISPOSITIONS:
        raise ReadinessError(f"readiness status must be one of {', '.join(STATUS_DISPOSITIONS)}")
    if task.get("contextDisposition") != STATUS_DISPOSITIONS[status]:
        raise ReadinessError(f"contextDisposition does not match readiness status {status}")
    _required_text(task.get("reason"), "reason")
    context_file = task.get("contextFile")
    if status == "ready":
        _safe_context_filename(context_file, "contextFile")
    elif context_file is not None:
        raise ReadinessError(f"{status} readiness must not retain a contextFile")
    return task


def record_readiness(
    receipt_path: Path,
    roster_path: Path,
    task_id: str,
    status: str,
    reason: str,
    context_path: Path | None,
    materialized: bool = False,
) -> str:
    _same_context_directory(receipt_path, roster_path, "ticket roster")
    raw_roster, feature_slug, ticket_source, tasks = _roster_metadata(roster_path)
    task_id = _required_text(task_id, "taskId").strip()
    if task_id not in tasks:
        raise ReadinessError(f"ticket roster has no task {task_id}")
    if status not in STATUS_DISPOSITIONS:
        raise ReadinessError(f"readiness status must be one of {', '.join(STATUS_DISPOSITIONS)}")
    reason = _required_text(reason, "reason").strip()
    if status == "ready" and not materialized:
        raise ReadinessError("ready readiness must use the bind command so materialization is proven")

    context_file: str | None = None
    if status == "ready":
        if context_path is None:
            raise ReadinessError("ready readiness requires --context")
        _same_context_directory(receipt_path, context_path, "Wiki context")
        context = _validate_context(context_path, roster_path)
        _validate_context_identity(context, feature_slug, ticket_source, task_id)
        context_file = context_path.name
    elif context_path is not None:
        raise ReadinessError(f"{status} readiness must not retain or reference --context")

    if receipt_path.exists():
        receipt = _load_json(receipt_path, "readiness receipt")
        _validate_receipt_shape(receipt)
        if receipt["featureSlug"] != feature_slug:
            raise ReadinessError("existing readiness receipt featureSlug does not match the ticket roster")
        if receipt["ticketSource"] != ticket_source:
            raise ReadinessError("existing readiness receipt ticketSource does not match the ticket roster")
        if receipt["rosterFile"] != roster_path.name:
            raise ReadinessError("existing readiness receipt points at a different ticket roster")
        existing = {
            _validate_task_entry(item)["taskId"]: item
            for item in receipt["tasks"]
        }
    else:
        existing = {}

    task = tasks[task_id]
    entry: dict[str, Any] = {
        "taskId": task_id,
        "taskTitle": task["title"],
        "taskFingerprint": task["hash"],
        "status": status,
        "contextDisposition": STATUS_DISPOSITIONS[status],
        "reason": reason,
    }
    if context_file is not None:
        entry["contextFile"] = context_file
    existing[task_id] = entry

    ordered_tasks = [
        existing[roster_task_id]
        for roster_task_id in tasks
        if roster_task_id in existing
    ]
    receipt = {
        "schemaVersion": SCHEMA_VERSION,
        "kind": KIND,
        "generatedBy": GENERATED_BY,
        "featureSlug": feature_slug,
        "ticketSource": raw_roster["ticketSource"],
        "rosterFile": roster_path.name,
        "tasks": ordered_tasks,
    }
    _write_json(receipt_path, receipt)
    return f"recorded {status} readiness for task {task_id} -> {receipt_path}"


def bind_readiness(
    receipt_path: Path,
    roster_path: Path,
    context_path: Path,
    task_id: str,
    project_root: Path,
    reason: str,
) -> str:
    _same_context_directory(receipt_path, roster_path, "ticket roster")
    _same_context_directory(receipt_path, context_path, "Wiki context")
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")

    _, feature_slug, ticket_source, tasks = _roster_metadata(roster_path)
    task_id = _required_text(task_id, "taskId").strip()
    if task_id not in tasks:
        raise ReadinessError(f"ticket roster has no task {task_id}")
    context = _validate_context(context_path, roster_path)
    _validate_context_identity(context, feature_slug, ticket_source, task_id)

    rendered, materialized_output = _render_and_materialize_context(
        context_path=context_path,
        task_id=task_id,
        role="implementer",
        project_root=project_root,
    )

    record_readiness(
        receipt_path,
        roster_path,
        task_id,
        "ready",
        reason,
        context_path,
        materialized=True,
    )
    parts = [part.rstrip() for part in (rendered, materialized_output) if part.strip()]
    return "\n\n".join(parts)


def validate_readiness(receipt_path: Path, task_id: str) -> str:
    _, _, entry, _ = _validated_readiness_task(receipt_path, task_id)
    return f"readiness {entry['status']} is valid for task {entry['taskId']}"


def _validated_readiness_task(
    receipt_path: Path,
    task_id: str,
) -> tuple[dict[str, Any], Path, dict[str, Any], Path | None]:
    receipt = _load_json(receipt_path, "readiness receipt")
    _validate_receipt_shape(receipt)
    roster_path = receipt_path.parent / _safe_context_filename(receipt["rosterFile"], "rosterFile")
    _, feature_slug, ticket_source, roster_tasks = _roster_metadata(roster_path)
    if receipt["featureSlug"] != feature_slug:
        raise ReadinessError("readiness receipt featureSlug does not match the current ticket roster")
    if receipt["ticketSource"] != ticket_source:
        raise ReadinessError("readiness receipt ticketSource does not match the current ticket roster")

    seen: set[str] = set()
    task_entries: dict[str, dict[str, Any]] = {}
    for raw_task in receipt["tasks"]:
        task = _validate_task_entry(raw_task)
        entry_id = task["taskId"]
        if entry_id in seen:
            raise ReadinessError(f"readiness receipt duplicates task {entry_id}")
        seen.add(entry_id)
        task_entries[entry_id] = task

    task_id = _required_text(task_id, "taskId").strip()
    if task_id not in task_entries:
        raise ReadinessError(f"readiness receipt has no result for task {task_id}")
    if task_id not in roster_tasks:
        raise ReadinessError(f"current ticket roster has no task {task_id}")
    entry = task_entries[task_id]
    roster_task = roster_tasks[task_id]
    if entry["taskTitle"] != roster_task["title"]:
        raise ReadinessError(f"task title drift for {task_id}")
    if entry["taskFingerprint"] != roster_task["hash"]:
        raise ReadinessError(f"task fingerprint drift for {task_id}")

    if entry["status"] == "ready":
        context_path = receipt_path.parent / _safe_context_filename(entry["contextFile"], "contextFile")
        context = _validate_context(context_path, roster_path)
        _validate_context_identity(context, feature_slug, ticket_source, task_id)
    else:
        context_path = None
    return receipt, roster_path, entry, context_path


def _review_handoff_text(
    *,
    status: str,
    task_id: str | None,
    detail: str,
    materialized: str | None = None,
) -> str:
    lines = [
        "# Reviewer Wiki Context",
        "",
        f"- Status: {status}",
        f"- Task ID: `{task_id}`" if task_id else "- Task ID: unknown",
        "",
    ]
    if status != "ready":
        lines.extend(
            [
                "## Non-blocking caveat",
                "",
                "No verified Wiki reviewer context is available for this review.",
                f"This is a non-blocking caveat: {detail}",
                "Continue both Standards and Spec review without Wiki constraints. Do not run late research or delay review.",
                "",
            ]
        )
        return "\n".join(lines)

    lines.extend(
        [
            "Use this same read-only context for both isolated review axes:",
            "",
            "- Standards still reports only repository-standard and code-quality findings.",
            "- Spec still reports only issue/spec completeness, correctness, and scope findings.",
            "- Wiki constraints may inform either axis but must not merge or change their output structure.",
            "",
        ]
    )
    if materialized and materialized.strip():
        lines.extend([materialized.strip(), ""])
    return "\n".join(lines)


def review_handoff(
    *,
    receipt_path: Path | None,
    task_id: str | None,
    project_root: Path,
    handoff_path: Path,
    obsidian_wiki_cmd: str | None,
    shared_wiki_cmd: str | None,
) -> str:
    if not project_root.is_dir():
        raise ReadinessError(f"project root is not a directory: {project_root}")
    context_dir = (project_root / ".adapter" / "context").resolve()
    if handoff_path.resolve().parent != context_dir:
        raise ReadinessError("review handoff must be a plain file in <project-root>/.adapter/context")

    # A failed refresh must never leave an older reviewer handoff available to subagents.
    handoff_path.unlink(missing_ok=True)

    normalized_task_id = task_id.strip() if isinstance(task_id, str) and task_id.strip() else None
    if receipt_path is None or normalized_task_id is None or not receipt_path.is_file():
        _write_text(
            handoff_path,
            _review_handoff_text(
                status="unknown",
                task_id=normalized_task_id,
                detail="the current task or its implementation readiness receipt could not be identified.",
            ),
        )
        return f"wrote fail-open unknown reviewer handoff -> {handoff_path}"

    try:
        if receipt_path.resolve().parent != context_dir:
            raise ReadinessError("readiness receipt is outside the current project .adapter/context")
        _, _, entry, context_path = _validated_readiness_task(receipt_path, normalized_task_id)
    except (ReadinessError, ValidationError, FingerprintError):
        _write_text(
            handoff_path,
            _review_handoff_text(
                status="broken",
                task_id=normalized_task_id,
                detail="the implementation readiness receipt or its bound context failed validation; all Wiki output was discarded.",
            ),
        )
        return f"wrote fail-open broken reviewer handoff -> {handoff_path}"

    status = entry["status"]
    if status != "ready":
        _write_text(
            handoff_path,
            _review_handoff_text(
                status=status,
                task_id=normalized_task_id,
                detail=f"implementation readiness is {status}; no late research or reviewer materialization was attempted.",
            ),
        )
        return f"wrote fail-open {status} reviewer handoff -> {handoff_path}"

    if context_path is None:
        raise ReadinessError("ready readiness did not resolve a Wiki context")

    try:
        _, materialized = _render_and_materialize_context(
            context_path=context_path,
            task_id=normalized_task_id,
            role="reviewer",
            project_root=project_root,
            obsidian_wiki_cmd=obsidian_wiki_cmd,
            shared_wiki_cmd=shared_wiki_cmd,
        )
    except ReadinessError:
        _write_text(
            handoff_path,
            _review_handoff_text(
                status="materialize-failed",
                task_id=normalized_task_id,
                detail="reviewer render/materialize validation failed; partial and stale output was discarded.",
            ),
        )
        return f"wrote fail-open materialize-failed reviewer handoff -> {handoff_path}"

    _write_text(
        handoff_path,
        _review_handoff_text(
            status="ready",
            task_id=normalized_task_id,
            detail="",
            materialized=materialized,
        ),
    )
    return f"wrote ready reviewer handoff -> {handoff_path}"


def main() -> int:
    _configure_stdio()
    parser = argparse.ArgumentParser(
        description="Prepare stable single-task rosters and record reusable implementation Wiki readiness."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    issue = subparsers.add_parser("prepare-issue", help="Build one ticket roster from gh issue JSON")
    issue.add_argument("--feature-slug", required=True)
    issue.add_argument("--issue-json", required=True)
    issue.add_argument("--roster", required=True)

    manual = subparsers.add_parser("prepare-manual", help="Build one manual ticket roster from a confirmed brief")
    manual.add_argument("--feature-slug", required=True)
    manual.add_argument("--task-title", required=True)
    manual.add_argument("--task-text-file", required=True)
    manual.add_argument("--roster", required=True)

    record = subparsers.add_parser("record", help="Record one task's Wiki readiness result")
    record.add_argument("--receipt", required=True)
    record.add_argument("--roster", required=True)
    record.add_argument("--task-id", required=True)
    record.add_argument("--status", choices=sorted(STATUS_DISPOSITIONS), required=True)
    record.add_argument("--reason", required=True)
    record.add_argument("--context")

    bind = subparsers.add_parser(
        "bind",
        help="Atomically render/materialize one implementer task and record ready only on success",
    )
    bind.add_argument("--receipt", required=True)
    bind.add_argument("--roster", required=True)
    bind.add_argument("--context", required=True)
    bind.add_argument("--task-id", required=True)
    bind.add_argument("--project-root", required=True)
    bind.add_argument("--reason", required=True)

    validate = subparsers.add_parser("validate", help="Validate a receipt against its current roster/context")
    validate.add_argument("--receipt", required=True)
    validate.add_argument("--task-id", required=True)

    review = subparsers.add_parser(
        "review-handoff",
        help="Fail-open reviewer materialization from an existing implementation readiness receipt",
    )
    review.add_argument("--receipt")
    review.add_argument("--task-id")
    review.add_argument("--project-root", required=True)
    review.add_argument("--handoff", required=True)
    review.add_argument("--obsidian-wiki-cmd")
    review.add_argument("--shared-wiki-cmd")

    args = parser.parse_args()
    try:
        if args.command == "prepare-issue":
            print(
                prepare_issue(
                    Path(args.issue_json),
                    Path(args.roster),
                    args.feature_slug,
                )
            )
        elif args.command == "prepare-manual":
            print(
                prepare_manual(
                    Path(args.task_text_file),
                    Path(args.roster),
                    args.feature_slug,
                    args.task_title,
                )
            )
        elif args.command == "record":
            print(
                record_readiness(
                    Path(args.receipt),
                    Path(args.roster),
                    args.task_id,
                    args.status,
                    args.reason,
                    Path(args.context) if args.context else None,
                )
            )
        elif args.command == "bind":
            print(
                bind_readiness(
                    Path(args.receipt),
                    Path(args.roster),
                    Path(args.context),
                    args.task_id,
                    Path(args.project_root),
                    args.reason,
                )
            )
        elif args.command == "validate":
            print(validate_readiness(Path(args.receipt), args.task_id))
        else:
            print(
                review_handoff(
                    receipt_path=Path(args.receipt) if args.receipt else None,
                    task_id=args.task_id,
                    project_root=Path(args.project_root),
                    handoff_path=Path(args.handoff),
                    obsidian_wiki_cmd=args.obsidian_wiki_cmd,
                    shared_wiki_cmd=args.shared_wiki_cmd,
                )
            )
        return 0
    except (ReadinessError, ValidationError, FingerprintError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
