#!/usr/bin/env python3
"""Generated by grill-adapter."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from adr_identity import AdrIdentityError, source_id_for_path, validate_identity

KIND = "grill-adapter.wiki-context"
SCHEMA_VERSION = 6
LEGACY_SCHEMA_VERSION = 5
SUPPORTED_SCHEMA_VERSIONS = {LEGACY_SCHEMA_VERSION, SCHEMA_VERSION}
CONSTRAINT_CATEGORIES = ("implementation", "test", "review", "general")
ROLE_CATEGORIES = {
    "implementer": ("implementation", "test", "general"),
    "reviewer": ("implementation", "test", "review", "general"),
}
# Map the renderer's task role onto the card-marker binding role (wiki_section.KNOWN_BINDING_ROLES).
# A section may declare `roles` (stamped mechanically from a discovery-card marker) to bind to only
# some roles; render + reread skip a section whose roles exclude the active role. Absent roles =
# binds to every role (historical behavior; non-card sections never carry roles).
ROLE_TO_BINDING = {"implementer": "implement", "reviewer": "review"}
# Source anchors are bounded pointers into a section, not the section body -- the authoritative full
# text always comes from the reread. A long excerpt is soft-capped at render (the only place an anchor
# reaches an execution prompt) so a verbose selection cannot bloat per-task injection.
MAX_SOURCE_ANCHOR_EXCERPT = 200
DESTINATION_KINDS = {"task-bound", "global", "planning-only"}
SCAFFOLD_GENERATED_BY = "grill-adapter"
# taskRouting block emitted by --scaffold. These are the pre-confirmation values: the author flips
# status to "confirmed" and selectedSectionsFrozen to true once routing is final, and
# --bind-fingerprints + --execution-ready then gate it. The other three are fixed declared strings.
SCAFFOLD_TASK_ROUTING = {
    "status": "candidate_sections_only",
    "ticketRosterFormat": "grill-adapter-ticket-roster-v1",
    "fingerprintAlgorithm": "sha256:grill-adapter-task-text-v1",
    "selectedSectionsFrozen": False,
    "refreshPolicy": "refresh-taskWikiRefs-and-fingerprints-only",  # Note bindings, hashes, and routing are frozen.
}
# Declared ticket sources. Audit metadata only: the engine fingerprints whatever text the roster
# hands it and never branches on this value, reads a tracker, or touches the network.
TICKET_SOURCES = {"grill-local-scratch", "github-issues", "manual"}
HEX_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
SHA256_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
SKILL_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
SKILL_VERSION_RE = re.compile(
    r"^(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)"
    r"(?:-(?:0|[1-9][0-9]*|[A-Za-z-][0-9A-Za-z-]*)"
    r"(?:\.(?:0|[1-9][0-9]*|[A-Za-z-][0-9A-Za-z-]*))*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)
V6_NOTE_TYPES = {"constraint", "domain", "decision", "guide"}
V6_ROLES = {"project", "shared"}
V6_REQUIRED_SKILL_ROLES = {"implementer", "reviewer"}
ADR_SOURCE_ID_RE = re.compile(r"^project-adr:[a-f0-9]{64}$")
# A digest of 64 identical hex chars (0000…, 1111…, ffff…) is an authoring placeholder, never a
# real sha256. Rejecting it stops copy-pasted skeleton fingerprints from passing validation and
# only blowing up later at the execution-side --fingerprint-preflight.
PLACEHOLDER_FINGERPRINT_RE = re.compile(r"^([0-9a-f])\1{63}$")


class ValidationError(Exception):
    pass


class FingerprintError(Exception):
    pass


def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass


def _as_list(value: Any, field: str) -> list[Any]:
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValidationError(f"{field} must be a list")
    return value


def _as_dict(value: Any, field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValidationError(f"{field} must be an object")
    return value


def _load_json(path: Path, label: str) -> dict[str, Any]:
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValidationError(f"Cannot read {label}: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValidationError(f"Invalid JSON in {label}: {exc}") from exc
    return _as_dict(data, label)


def _load_context(path: Path) -> dict[str, Any]:
    if path.suffix == ".md":
        raise ValidationError("Legacy .wiki-context.md is not supported; schemaVersion 5 JSON is read-only compatibility and new planning must create a schemaVersion 6 Obsidian sidecar.")
    return _load_json(path, "wiki context")


def _section_id(section: dict[str, Any]) -> str:
    section_id = section.get("sectionId") or section.get("section_name")
    if not section_id:
        raise ValidationError("section must include sectionId or section_name")
    return str(section_id)


def _section_key(page: dict[str, Any], section: dict[str, Any]) -> tuple[str, str, str, str]:
    root = str(page.get("root") or "")
    source = str(page.get("source") or "")
    path = str(page.get("localPath") or page.get("wikiPath") or page.get("displayPath") or page.get("path") or "")
    return (root, source, path, _section_id(section))


def _iter_sections(data: dict[str, Any]) -> list[tuple[dict[str, Any], dict[str, Any]]]:
    pairs: list[tuple[dict[str, Any], dict[str, Any]]] = []
    for page in _as_list(data.get("wikiPages"), "wikiPages"):
        page_obj = _as_dict(page, "wikiPages[]")
        for section in _as_list(page_obj.get("sections"), "sections"):
            pairs.append((page_obj, _as_dict(section, "sections[]")))
    return pairs


def _validate_task_fingerprint(task_ref: dict[str, Any], field: str) -> None:
    fingerprint = task_ref.get("taskFingerprint")
    if not isinstance(fingerprint, str) or not HEX_SHA256_RE.match(fingerprint):
        raise ValidationError(f"{field}.taskFingerprint must be a 64-character lowercase sha256 hex digest")
    if PLACEHOLDER_FINGERPRINT_RE.match(fingerprint):
        raise ValidationError(
            f"{field}.taskFingerprint looks like a placeholder; run --bind-fingerprints --ticket-roster <roster> to stamp the real fingerprint"
        )


def _validate_v6_note(
    note: Any,
    field: str,
    require_skill: bool = False,
    allow_destination: bool = False,
    project_root: Path | None = None,
) -> dict[str, Any]:
    value = _as_dict(note, field)
    allowed_fields = {
        "sourceId", "role", "path", "wikiId", "type", "summary", "bindingDigest", "contentHash",
        "adrSourceId", "adrSourcePath", "adrSourceContentHash",
        *(
            (
                "requiredFor",
                "skillProvider",
                "skillName",
                "skillVersion",
                "skillContractHash",
                "skillTriggers",
                "discoveryState",
            )
            if require_skill
            else ("constraintStrength",)
        ),
        *( ("destination",) if allow_destination else () ),
    }
    unknown_fields = sorted(set(value) - allowed_fields)
    if unknown_fields:
        raise ValidationError(f"{field} contains unsupported fields: {', '.join(unknown_fields)}")
    for key in ("sourceId", "path", "wikiId", "summary", "bindingDigest", "contentHash"):
        if not isinstance(value.get(key), str) or not value[key].strip():
            raise ValidationError(f"{field}.{key} must be a non-empty string")
    if value.get("role") not in V6_ROLES:
        raise ValidationError(f"{field}.role must be one of {', '.join(sorted(V6_ROLES))}")
    if value.get("type") not in V6_NOTE_TYPES:
        raise ValidationError(f"{field}.type must be one of {', '.join(sorted(V6_NOTE_TYPES))}")
    if not HEX_SHA256_RE.match(value["bindingDigest"]):
        raise ValidationError(f"{field}.bindingDigest must be a 64-character sha256 digest")
    if not SHA256_RE.match(value["contentHash"]):
        raise ValidationError(f"{field}.contentHash must be a sha256 digest")
    adr_values = [value.get("adrSourceId"), value.get("adrSourcePath"), value.get("adrSourceContentHash")]
    if any(item is not None for item in adr_values):
        if require_skill:
            raise ValidationError(f"{field} Skill Cards must not carry ADR execution projection identity")
        if any(not isinstance(item, str) or not item.strip() for item in adr_values):
            raise ValidationError(f"{field} ADR identity must include adrSourceId, adrSourcePath, and adrSourceContentHash together")
        if value.get("role") != "project":
            raise ValidationError(f"{field} ADR execution projections must use the project Source")
        if value.get("type") != "constraint" or value.get("constraintStrength") != "hard":
            raise ValidationError(f"{field} ADR execution projections must be hard constraint Notes")
        if not ADR_SOURCE_ID_RE.fullmatch(value["adrSourceId"]):
            raise ValidationError(f"{field}.adrSourceId must be project-adr:<sha256>")
        if not SHA256_RE.fullmatch(value["adrSourceContentHash"]):
            raise ValidationError(f"{field}.adrSourceContentHash must be a sha256 digest")
        try:
            expected_id = source_id_for_path(value["adrSourcePath"])
        except AdrIdentityError as exc:
            raise ValidationError(f"{field}.adrSourcePath is invalid: {exc}") from exc
        if value["adrSourceId"] != expected_id:
            raise ValidationError(f"{field}.adrSourceId does not match adrSourcePath")
        if project_root is not None:
            try:
                validate_identity(
                    project_root,
                    value["adrSourceId"],
                    value["adrSourcePath"],
                    value["adrSourceContentHash"],
                )
            except AdrIdentityError as exc:
                raise ValidationError(f"{field} ADR authority validation failed: {exc}") from exc
    if "content" in value:
        raise ValidationError(f"{field}.content is not allowed; schemaVersion 6 carries Note metadata only")
    if require_skill:
        roles = _as_list(value.get("requiredFor"), f"{field}.requiredFor")
        if (
            not roles
            or len(roles) != len(set(roles))
            or any(role not in V6_REQUIRED_SKILL_ROLES for role in roles)
        ):
            raise ValidationError(
                f"{field}.requiredFor must be a non-empty unique subset of "
                f"{sorted(V6_REQUIRED_SKILL_ROLES)}"
            )
        if value.get("skillProvider") != "claude-code-project":
            raise ValidationError(f"{field}.skillProvider must be claude-code-project")
        if not isinstance(value.get("skillName"), str) or not SKILL_NAME_RE.fullmatch(value["skillName"]):
            raise ValidationError(f"{field}.skillName must use kebab-case")
        if not isinstance(value.get("skillVersion"), str) or not SKILL_VERSION_RE.fullmatch(value["skillVersion"]):
            raise ValidationError(
                f"{field}.skillVersion must be a semantic major.minor.patch version"
            )
        if not SHA256_RE.match(str(value.get("skillContractHash", ""))):
            raise ValidationError(f"{field}.skillContractHash must be a sha256 digest")
        triggers = _as_list(value.get("skillTriggers"), f"{field}.skillTriggers")
        if (
            not triggers
            or any(not isinstance(trigger, str) or not trigger.strip() for trigger in triggers)
            or len(set(triggers)) != len(triggers)
        ):
            raise ValidationError(f"{field}.skillTriggers must be a non-empty unique string array")
        if value.get("discoveryState") != "discoverable":
            raise ValidationError(f"{field}.discoveryState must be discoverable")
    elif value.get("constraintStrength") not in ("hard", "soft", None):
        raise ValidationError(f"{field}.constraintStrength must be hard or soft when present")
    return value


def _validate_v6_execution_ready(data: dict[str, Any]) -> None:
    task_routing = _as_dict(data.get("taskRouting"), "taskRouting")
    if task_routing.get("status") != "confirmed":
        raise ValidationError("taskRouting.status must be confirmed for execution-ready wiki context")
    if task_routing.get("selectedSectionsFrozen") is not True:
        raise ValidationError("taskRouting.selectedSectionsFrozen must be true for execution-ready wiki context")
    task_refs = _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
    task_ids: set[str] = set()
    for index, task_ref in enumerate(task_refs):
        task = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task.get("taskId")
        if not isinstance(task_id, str) or not task_id.strip() or task_id in task_ids:
            raise ValidationError(f"taskWikiRefs[{index}].taskId must be a unique non-empty task id")
        task_ids.add(task_id)
        if not isinstance(task.get("taskTitle"), str) or not task["taskTitle"].strip():
            raise ValidationError(f"taskWikiRefs[{index}].taskTitle is required")
        _validate_task_fingerprint(task, f"taskWikiRefs[{index}]")
    for collection in ("wikiNotes", "requiredSkills"):
        for index, raw_note in enumerate(_as_list(data.get(collection), collection)):
            note = _as_dict(raw_note, f"{collection}[{index}]")
            destination = _as_dict(note.get("destination"), f"{collection}[{index}].destination")
            kind = destination.get("kind")
            if kind not in DESTINATION_KINDS:
                raise ValidationError(f"{collection}[{index}].destination.kind must be one of {', '.join(sorted(DESTINATION_KINDS))}")
            if not isinstance(destination.get("reason"), str) or not destination["reason"].strip():
                raise ValidationError(f"{collection}[{index}].destination.reason is required")
            if collection == "wikiNotes" and note.get("constraintStrength") == "hard" and kind == "planning-only":
                raise ValidationError(f"hard Note {note.get('wikiId')} cannot have planning-only destination")
            tasks = destination.get("tasks")
            if kind == "task-bound":
                task_list = _as_list(tasks, f"{collection}[{index}].destination.tasks")
                if not task_list or any(not isinstance(task_id, str) or not task_id.strip() or task_id not in task_ids for task_id in task_list):
                    raise ValidationError(f"{collection}[{index}].destination.tasks must name known task ids")
                if len(set(task_list)) != len(task_list):
                    raise ValidationError(f"{collection}[{index}].destination.tasks must not duplicate task ids")
            elif tasks:
                raise ValidationError(f"{collection}[{index}].destination.tasks is only valid for task-bound routing")


def _validate_execution_ready(data: dict[str, Any]) -> None:
    if data.get("schemaVersion") == SCHEMA_VERSION:
        _validate_v6_execution_ready(data)
        return
    task_routing = _as_dict(data.get("taskRouting"), "taskRouting")
    if task_routing.get("status") != "confirmed":
        raise ValidationError("taskRouting.status must be confirmed for execution-ready wiki context")
    if task_routing.get("selectedSectionsFrozen") is not True:
        raise ValidationError("taskRouting.selectedSectionsFrozen must be true for execution-ready wiki context")

    # taskWikiRefs is the task roster + fingerprint anchor only. In schemaVersion 5 there are no per-task
    # wiki refs and no globalWikiRefs collection; routing lives entirely on each section's destination.
    # Collect valid task ids first so task-bound sections can be checked against them.
    task_refs = _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
    task_ids: set[str] = set()
    for index, task_ref in enumerate(task_refs):
        task_obj = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task_obj.get("taskId")
        if not isinstance(task_id, str) or not task_id.strip():
            raise ValidationError(f"taskWikiRefs[{index}].taskId is required")
        if task_id in task_ids:
            raise ValidationError(f"taskWikiRefs[{index}].taskId duplicates {task_id}")
        task_ids.add(task_id)
        if not isinstance(task_obj.get("taskTitle"), str) or not task_obj.get("taskTitle", "").strip():
            raise ValidationError(f"taskWikiRefs[{index}].taskTitle is required")
        _validate_task_fingerprint(task_obj, f"taskWikiRefs[{index}]")

    for page, section in _iter_sections(data):
        key = _section_key(page, section)
        destination = _as_dict(section.get("destination"), f"section {key}.destination")
        kind = destination.get("kind")
        if kind not in DESTINATION_KINDS:
            raise ValidationError(f"section {key}.destination.kind must be one of {', '.join(sorted(DESTINATION_KINDS))}")
        if not str(destination.get("reason") or "").strip():
            raise ValidationError(f"section {key}.destination.reason is required")
        relevance = section.get("relevance")
        if (section.get("hardConstraint") or relevance == "direct") and kind == "planning-only":
            raise ValidationError(f"hard/direct section {key} cannot have planning-only destination")
        # Hard constraints are authoritative and must be reread in full at execution time, not
        # only distilled into planning bullets. render_reread_list() silently skips hard sections
        # that lack a reread block, so requiring it here is a load-bearing backstop: do not relax it
        # to save planning tokens (guarded by tests/wiki-context-json-render-smoke.sh HARD_NO_REREAD).
        if section.get("hardConstraint"):
            reread = section.get("reread")
            if not isinstance(reread, dict) or not reread:
                raise ValidationError(
                    f"hard-constraint section {key} must include a reread block so execution can reread the full section text"
                )
        # Routing: task-bound sections name the plan tasks they bind to (the one genuinely authored
        # mapping); global/planning-only carry no task list. globalWikiRefs/wikiRefs are gone -- the
        # renderer derives task scope straight from destination.kind and destination.tasks.
        tasks = destination.get("tasks")
        if kind == "task-bound":
            task_list = _as_list(tasks, f"section {key}.destination.tasks")
            if not task_list:
                raise ValidationError(f"task-bound section {key} must list one or more plan task ids in destination.tasks")
            seen_tasks: set[str] = set()
            for bound_id in task_list:
                if not isinstance(bound_id, str) or not bound_id.strip():
                    raise ValidationError(f"section {key}.destination.tasks entries must be non-empty task id strings")
                if bound_id in seen_tasks:
                    raise ValidationError(f"section {key}.destination.tasks duplicates {bound_id}")
                seen_tasks.add(bound_id)
                if bound_id not in task_ids:
                    raise ValidationError(f"task-bound section {key}.destination.tasks references unknown task id {bound_id}")
        elif tasks:
            raise ValidationError(f"{kind} section {key} must not set destination.tasks")


def _validate_v6_context(
    data: dict[str, Any],
    execution_ready: bool,
    project_root: Path | None = None,
) -> list[str]:
    if data.get("kind") != KIND:
        raise ValidationError(f"kind must be {KIND}")
    if not isinstance(data.get("featureSlug"), str) or not data["featureSlug"].strip():
        raise ValidationError("schemaVersion 6 wiki context requires a non-empty featureSlug")
    snapshot = data.get("snapshotHash")
    if not isinstance(snapshot, str) or not SHA256_RE.match(snapshot):
        raise ValidationError("snapshotHash must be a sha256 digest")
    bindings = _as_list(data.get("wikiBindings"), "wikiBindings")
    binding_digests: dict[str, str] = {}
    binding_roles: dict[str, str] = {}
    for index, raw_binding in enumerate(bindings):
        binding = _as_dict(raw_binding, f"wikiBindings[{index}]")
        source_id = binding.get("sourceId")
        if not isinstance(source_id, str) or not source_id.strip() or source_id in binding_digests:
            raise ValidationError(f"wikiBindings[{index}].sourceId must be a unique non-empty string")
        if binding.get("role") not in V6_ROLES:
            raise ValidationError(f"wikiBindings[{index}].role must be one of {', '.join(sorted(V6_ROLES))}")
        digest = binding.get("bindingDigest")
        if not isinstance(digest, str) or not HEX_SHA256_RE.match(digest):
            raise ValidationError(f"wikiBindings[{index}].bindingDigest must be a 64-character sha256 digest")
        binding_digests[source_id] = digest
        binding_roles[source_id] = binding["role"]
    if not binding_digests:
        raise ValidationError("wikiBindings must contain one or more bound Sources")
    seen_ids: set[str] = set()
    seen_adr_sources: set[str] = set()
    for collection, is_skill in (("wikiNotes", False), ("requiredSkills", True)):
        for index, raw_note in enumerate(_as_list(data.get(collection), collection)):
            note = _validate_v6_note(
                raw_note,
                f"{collection}[{index}]",
                require_skill=is_skill,
                allow_destination=True,
                project_root=project_root,
            )
            if note["wikiId"] in seen_ids:
                raise ValidationError(f"{collection}[{index}] duplicates wikiId {note['wikiId']}")
            seen_ids.add(note["wikiId"])
            if binding_digests.get(note["sourceId"]) != note["bindingDigest"]:
                raise ValidationError(f"{collection}[{index}] does not match a declared Source binding digest")
            if binding_roles.get(note["sourceId"]) != note["role"]:
                raise ValidationError(f"{collection}[{index}] does not match the declared Source binding role")
            adr_source_id = note.get("adrSourceId")
            if adr_source_id:
                if adr_source_id in seen_adr_sources:
                    raise ValidationError(f"{collection}[{index}] duplicates ADR authority identity {adr_source_id}")
                seen_adr_sources.add(adr_source_id)
    if "wikiPages" in data or "sharedWiki" in data:
        raise ValidationError("schemaVersion 6 uses wikiNotes/wikiBindings, not wikiPages/sharedWiki")
    _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
    _as_dict(data.get("taskRouting"), "taskRouting")
    if "caveats" in data:
        _as_list(data.get("caveats"), "caveats")
    if "maintenanceWarnings" in data:
        _as_list(data.get("maintenanceWarnings"), "maintenanceWarnings")
    if execution_ready:
        _validate_execution_ready(data)
    return []


def _validate_context(
    data: dict[str, Any],
    strict: bool,
    execution_ready: bool = False,
    project_root: Path | None = None,
) -> list[str]:
    caveats: list[str] = []
    schema_version = data.get("schemaVersion")
    if schema_version not in SUPPORTED_SCHEMA_VERSIONS:
        raise ValidationError(f"schemaVersion must be one of {', '.join(str(version) for version in sorted(SUPPORTED_SCHEMA_VERSIONS))}")
    if schema_version == SCHEMA_VERSION:
        return _validate_v6_context(data, execution_ready, project_root)
    if data.get("kind") != KIND:
        raise ValidationError(f"kind must be {KIND}")

    # Optional shared-wiki identity (which github_mcp shared wiki this plan was built against).
    # Tolerated when absent; lightly type-checked when present so execution can compare it to the
    # connected server's repoUrl and detect rebinding drift.
    shared_wiki = data.get("sharedWiki")
    if shared_wiki is not None:
        shared_wiki_obj = _as_dict(shared_wiki, "sharedWiki")
        repo_url = shared_wiki_obj.get("repoUrl")
        if repo_url is not None and (not isinstance(repo_url, str) or not repo_url.strip()):
            raise ValidationError("sharedWiki.repoUrl must be a non-empty string when present")

    pages = _as_list(data.get("wikiPages"), "wikiPages")
    for page_index, page in enumerate(pages):
        page_obj = _as_dict(page, f"wikiPages[{page_index}]")
        _as_dict(page_obj.get("documentContext"), f"wikiPages[{page_index}].documentContext")
        if "maintenanceWarnings" in page_obj:
            _as_list(page_obj.get("maintenanceWarnings"), f"wikiPages[{page_index}].maintenanceWarnings")
        sections = _as_list(page_obj.get("sections"), f"wikiPages[{page_index}].sections")
        for section_index, section in enumerate(sections):
            section_obj = _as_dict(section, f"wikiPages[{page_index}].sections[{section_index}]")
            if strict and "documentContext" in section_obj:
                raise ValidationError(f"wikiPages[{page_index}].sections[{section_index}].documentContext is not allowed; documentContext belongs on the page")
            section_id = section_obj.get("sectionId") or section_obj.get("section_name")
            if not section_id:
                raise ValidationError(f"wikiPages[{page_index}].sections[{section_index}] must include sectionId or section_name")
            constraints = _as_dict(section_obj.get("constraints"), f"wikiPages[{page_index}].sections[{section_index}].constraints")
            unknown = sorted(set(constraints) - set(CONSTRAINT_CATEGORIES))
            if unknown:
                message = f"wikiPages[{page_index}].sections[{section_index}].constraints contains unsupported categories: {', '.join(unknown)}"
                if strict:
                    raise ValidationError(message)
                caveats.append(message)
            for category in CONSTRAINT_CATEGORIES:
                _as_list(constraints.get(category), f"wikiPages[{page_index}].sections[{section_index}].constraints.{category}")
            if strict and "appliesTo" in section_obj:
                raise ValidationError(f"wikiPages[{page_index}].sections[{section_index}].appliesTo is removed in schemaVersion {SCHEMA_VERSION}; bind tasks via section.destination.tasks instead")
            if "sourceAnchors" in section_obj:
                _as_list(section_obj.get("sourceAnchors"), f"wikiPages[{page_index}].sections[{section_index}].sourceAnchors")
            if "roles" in section_obj:
                where = f"wikiPages[{page_index}].sections[{section_index}].roles"
                role_values = _as_list(section_obj.get("roles"), where)
                known = set(ROLE_TO_BINDING.values())
                unknown = [r for r in role_values if not (isinstance(r, str) and r in known)]
                if not role_values or unknown:
                    raise ValidationError(
                        f"{where} must be a non-empty subset of {sorted(known)} (got {section_obj.get('roles')!r})"
                    )
    if "maintenanceWarnings" in data:
        _as_list(data.get("maintenanceWarnings"), "maintenanceWarnings")
    if execution_ready:
        _validate_execution_ready(data)
    return caveats


def _selected_pages(data: dict[str, Any], section_keys: set[tuple[str, str, str, str]] | None = None) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for page in _as_list(data.get("wikiPages"), "wikiPages"):
        page_obj = dict(_as_dict(page, "wikiPages[]"))
        sections = []
        for section in _as_list(page_obj.get("sections"), "sections"):
            section_obj = _as_dict(section, "sections[]")
            if section_keys is not None and _section_key(page_obj, section_obj) not in section_keys:
                continue
            sections.append(section_obj)
        if sections:
            page_obj["sections"] = sections
            selected.append(page_obj)
    return selected


def _task_section_keys(data: dict[str, Any], task_id: str) -> set[tuple[str, str, str, str]]:
    # The task must exist in the taskWikiRefs roster (preserves the "unknown task id" guard for rendering).
    matches = [
        _as_dict(task_ref, "taskWikiRefs[]")
        for task_ref in _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
        if _as_dict(task_ref, "taskWikiRefs[]").get("taskId") == task_id
    ]
    if len(matches) != 1:
        raise ValidationError(f"taskWikiRefs must contain exactly one entry for taskId {task_id}")
    # Routing is read straight from each section's destination: global sections reach every task; a
    # task-bound section reaches this task only when its destination.tasks lists this task id.
    keys: set[tuple[str, str, str, str]] = set()
    for page, section in _iter_sections(data):
        destination = section.get("destination")
        if not isinstance(destination, dict):
            continue
        kind = destination.get("kind")
        if kind == "global":
            keys.add(_section_key(page, section))
        elif kind == "task-bound" and task_id in _as_list(destination.get("tasks"), "destination.tasks"):
            keys.add(_section_key(page, section))
    return keys


def _section_roles(section: dict[str, Any]) -> list[str] | None:
    """Return a section's binding-role restriction, or None when it binds to every role.

    A section restricts to a subset only when `roles` is a non-empty list of known binding
    roles that is a strict subset; anything else (absent, empty, unknown-only, or all roles)
    means no restriction. Non-card sections never carry `roles`, so they always return None.
    """
    raw = section.get("roles")
    if not isinstance(raw, list) or not raw:
        return None
    known = set(ROLE_TO_BINDING.values())
    roles = [role for role in raw if role in known]
    if not roles or len(set(roles)) == len(known):
        return None
    return roles


def _role_allows(section: dict[str, Any], role: str) -> bool:
    """Whether a section is visible to the active task role given its `roles` restriction."""
    roles = _section_roles(section)
    if roles is None:
        return True
    return ROLE_TO_BINDING.get(role, role) in roles


def _append_document_context(lines: list[str], display: str, context: dict[str, Any]) -> None:
    """Render the page heading plus its bounded document context, content-first.

    The heading folds the wiki path (its `.adapter/` vs `.shared-adapter/` prefix already
    signals the root) and the human title into one line; the overview renders as a blockquote. The
    machine plumbing an execution/reviewer subagent never acts on -- root/source/localPath/wikiPath
    metadata rows, the `.index.md` context-source path, the standalone "Document Context" heading --
    is dropped: nothing downstream parses this Markdown (it is Read once and discarded), so those
    rows were pure per-task token cost.
    """
    title = context.get("title")
    # The companion-index H1 is the canonical "Sections: <rel-path>" marker (migrate-wiki / scaffold
    # seed), not a human title -- folding it in would just echo the page path already in the heading.
    # Keep a genuine title (rare in practice); drop the structural placeholder.
    if isinstance(title, str) and title.strip().startswith("Sections:"):
        title = None
    heading = f"### `{display}`"
    if title:
        heading += f" — {title}"
    lines.append(heading)
    if context.get("overview"):
        lines.append(f"> {context['overview']}")
    if context.get("scope"):
        lines.append(f"- Scope: {context['scope']}")
    for caveat in _as_list(context.get("caveats"), "documentContext.caveats"):
        lines.append(f"- Caveat: {caveat}")


def _append_constraints(lines: list[str], constraints: dict[str, Any], role: str) -> None:
    for category in ROLE_CATEGORIES[role]:
        items = _as_list(constraints.get(category), f"constraints.{category}")
        if not items:
            continue
        # Bold label, not a heading: sections already render at h4, so a category h4 would collide.
        lines.append(f"**{category.capitalize()} constraints:**")
        for item in items:
            lines.append(f"- {item}")


def _truncate_excerpt(value: Any) -> str:
    """Soft-cap a source-anchor excerpt to a bounded pointer length with an ellipsis hint.

    Anchors are pointers, not authoritative text (that is the reread's job), so a pathologically long
    excerpt is trimmed here rather than rejected -- non-destructive to the stored selection, bounded in
    the execution prompt. The trailing hint tells the reader where the full text lives.
    """
    if value is None:
        return ""
    text = str(value)
    if len(text) <= MAX_SOURCE_ANCHOR_EXCERPT:
        return text
    return text[:MAX_SOURCE_ANCHOR_EXCERPT].rstrip() + "… (truncated; reread the section for full text)"


def _append_source_anchors(lines: list[str], anchors: Any) -> None:
    source_anchors = _as_list(anchors, "sourceAnchors")
    if not source_anchors:
        return
    lines.append("**Source anchors:**")
    for anchor in source_anchors:
        if isinstance(anchor, dict):
            heading = anchor.get("heading")
            excerpt = _truncate_excerpt(anchor.get("excerpt"))
            prefix = f"{heading}: " if heading else ""
            lines.append(f"- {prefix}{excerpt}".rstrip())
        else:
            lines.append(f"- {_truncate_excerpt(anchor)}")


def _v6_task_notes(data: dict[str, Any], task_id: str | None, role: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    if task_id:
        matches = [
            _as_dict(task_ref, "taskWikiRefs[]")
            for task_ref in _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
            if _as_dict(task_ref, "taskWikiRefs[]").get("taskId") == task_id
        ]
        if len(matches) != 1:
            raise ValidationError(f"taskWikiRefs must contain exactly one entry for taskId {task_id}")

    def routed(note: dict[str, Any]) -> bool:
        destination = _as_dict(note.get("destination"), "Note destination")
        if destination.get("kind") == "global":
            return True
        return task_id is not None and destination.get("kind") == "task-bound" and task_id in _as_list(destination.get("tasks"), "destination.tasks")

    notes = [
        _as_dict(note, "wikiNotes[]")
        for note in _as_list(data.get("wikiNotes"), "wikiNotes")
        if routed(_as_dict(note, "wikiNotes[]"))
    ]
    skills = [
        _as_dict(skill, "requiredSkills[]")
        for skill in _as_list(data.get("requiredSkills"), "requiredSkills")
        if role in _as_list(_as_dict(skill, "requiredSkills[]").get("requiredFor"), "requiredSkills[].requiredFor")
        and routed(_as_dict(skill, "requiredSkills[]"))
    ]
    return notes, skills


def _render_v6_markdown(data: dict[str, Any], role: str, task_id: str | None) -> str:
    notes, skills = _v6_task_notes(data, task_id, role)
    if not notes and not skills:
        if task_id:
            return f"No selected wiki constraints for task `{task_id}` and role `{role}`."
        return "No selected wiki constraints for this role."
    lines = ["## Wiki Constraints", ""]
    if task_id:
        lines.extend([f"- Task ID: `{task_id}`", ""])
    for note in notes:
        strength = note.get("constraintStrength") or "context"
        lines.append(f"### `{note['wikiId']}` · {strength}")
        lines.append(f"- Summary: {note['summary']}")
        lines.append(f"- Note: `{note['path']}`")
        lines.append("")
    if skills:
        lines.extend(["### Required Skill Cards", ""])
        for skill in skills:
            lines.append(f"- `{skill['wikiId']}`: {skill['summary']} (`{skill['path']}`)")
        lines.append("")
    for caveat in _as_list(data.get("caveats"), "caveats"):
        lines.append(f"- Context caveat: {caveat}")
    return "\n".join(lines).rstrip()


def render_markdown(data: dict[str, Any], role: str, task_id: str | None = None) -> str:
    if data.get("schemaVersion") == SCHEMA_VERSION:
        return _render_v6_markdown(data, role, task_id)
    section_keys = _task_section_keys(data, task_id) if task_id else None
    pages = _selected_pages(data, section_keys)
    if not pages:
        if task_id:
            return f"No selected wiki constraints for task `{task_id}` and role `{role}`."
        return "No selected wiki constraints for this role."

    lines: list[str] = ["## Wiki Constraints", ""]
    if task_id:
        lines.append(f"- Task ID: `{task_id}`")
        lines.append("")
    shared_wiki = data.get("sharedWiki")
    if isinstance(shared_wiki, dict):
        repo_url = shared_wiki.get("repoUrl")
        revision = shared_wiki.get("revision")
        commit = None
        if isinstance(revision, dict):
            commit = revision.get("commitSha") or revision.get("shortSha") or revision.get("ref")
        identity_bits: list[str] = []
        if repo_url:
            identity_bits.append(f"repo `{repo_url}`")
        if commit:
            identity_bits.append(f"revision `{commit}`")
        if identity_bits:
            # Identity only. The drift check ("confirm the MCP still serves this repo") is not the
            # subagent's job: wiki_materialize_task.py already fails closed on sharedWiki rebinding
            # and revision drift before appending the rereads this file gets Read alongside.
            lines.append(f"- Shared wiki source: {', '.join(identity_bits)}")
            lines.append("")
    for page in pages:
        display = page.get("displayPath") or page.get("path") or page.get("wikiPath") or "unknown wiki page"
        _append_document_context(lines, display, _as_dict(page.get("documentContext"), "documentContext"))
        for caveat in _as_list(page.get("caveats"), "page.caveats"):
            lines.append(f"- Caveat: {caveat}")
        lines.append("")

        for section in _as_list(page.get("sections"), "sections"):
            # A role-restricted section (roles stamped from a discovery-card marker) is invisible
            # to roles it does not bind — e.g. a review-only skill card never reaches implementers.
            if not _role_allows(section, role):
                continue
            section_id = section.get("sectionId") or section.get("section_name")
            hard = bool(section.get("hardConstraint"))
            # Execution render carries only what the implementer/reviewer acts on for this task: the
            # section id + binding strength (folded into the heading), relevanceTo + reason (separate
            # fields, never merged), and the constraints. Planning/routing bookkeeping is dropped
            # (relevance/confidence selection signals, destination kind/reason -- routing is already
            # resolved: this section only renders because it routed to this task), and so is the
            # `#### Reread` pointer block: it duplicated the page metadata above and the section's full
            # text below, which materialize appends verbatim under "## Hard Wiki Constraint Rereads".
            lines.append(f"#### `{section_id}` · {'hard' if hard else 'soft'}")
            if section.get("relevanceTo"):
                lines.append(f"- Relevance: {section['relevanceTo']}")
            if section.get("reason"):
                lines.append(f"- Why: {section['reason']}")
            for caveat in _as_list(section.get("caveats"), "section.caveats"):
                lines.append(f"- Caveat: {caveat}")
            _append_constraints(lines, _as_dict(section.get("constraints"), "constraints"), role)
            # Source anchors are a lossy pointer into the section body. For a hard constraint the
            # authoritative full text is appended below, so an anchor there is pure duplication; render
            # anchors only for soft (no-reread) sections, where they are the sole verbatim provenance.
            if not hard:
                _append_source_anchors(lines, section.get("sourceAnchors"))
            lines.append("")
    for caveat in _as_list(data.get("caveats"), "caveats"):
        lines.append(f"- Context caveat: {caveat}")
    return "\n".join(lines).rstrip()


def _load_local_section_graph(root_name: str) -> dict[str, Any] | None:
    """Load a local wiki root's derived .graph.json, or None if unavailable.

    Works for both ``project`` (``.adapter/wiki``) and a locally checked-out
    ``shared`` wiki (``.shared-adapter/wiki``). Read lazily and defensively:
    depends-on closure is an additive convenience, so any failure to locate/parse the
    graph must degrade to "no closure", never break rereads. The github_mcp shared wiki
    has no local graph; its closure is computed by wiki_materialize_task.py against the
    remote graph instead.
    """
    try:
        from wiki_common import repo_root, select_wiki_root  # local import keeps the renderer stdlib-only otherwise

        wiki = select_wiki_root(repo_root(Path.cwd()), root_name)
        graph_path = wiki.path / ".graph.json"
        if not graph_path.is_file():
            return None
        graph = json.loads(graph_path.read_text(encoding="utf-8"))
        return graph if isinstance(graph, dict) else None
    except Exception:
        return None


def _depends_on_closure_entries(
    local_source_nodes: dict[str, list[str]],
    emitted_keys: set[tuple[str, str]],
) -> list[dict[str, Any]]:
    """1-hop selection-time closure of depends-on edges for LOCAL hard-constraint sections.

    ``local_source_nodes`` maps a local root name (``project`` / ``shared``) to its
    selected hard-constraint ``page#section`` nodes. For each root we load that wiki's own
    derived .graph.json and pull each section's ``depends-on`` targets into the reread set,
    so a load-bearing dependency is never left behind a link at execution. Bounded to one
    hop (a target's own depends-on edges are NOT followed) and deduped against the directly
    emitted rereads. Returns synthesized reread entries (same local root, section-level
    targets only); page-level depends-on targets are skipped (not rereadable as a section).

    github_mcp shared sections are intentionally NOT handled here: their graph is remote, so
    wiki_materialize_task.py closes them via the shared-wiki graph-neighbors CLI. Both paths
    share wiki_common.depends_on_closure_targets, so what counts as a closed edge never forks.
    """
    from wiki_common import depends_on_closure_targets, one_hop_neighbors  # keep renderer stdlib-only otherwise

    entries: list[dict[str, Any]] = []
    for root_name, source_nodes in local_source_nodes.items():
        if not source_nodes:
            continue
        graph = _load_local_section_graph(root_name)
        if not graph:
            continue
        slices = one_hop_neighbors(graph, source_nodes)
        for closed_via, local_path, section_id in depends_on_closure_targets(slices, source_nodes):
            key = (root_name, f"{local_path}#{section_id}")
            if key in emitted_keys:
                continue
            emitted_keys.add(key)
            entries.append({
                "root": root_name,
                "source": "local",
                "displayPath": local_path,
                "localPath": local_path,
                "wikiPath": local_path,
                "sectionId": section_id,
                "reread": {"localPath": local_path, "sectionId": section_id, "includeDocumentContext": True},
                "closureType": "depends-on",
                "closedVia": closed_via,
            })
    return entries


def reread_entries(data: dict[str, Any], role: str = "implementer", task_id: str | None = None) -> list[dict[str, Any]]:
    """Task-scoped hard-constraint reread set as structured entries (the data behind --reread-list).

    Exposed so an orchestrator (wiki_materialize_task.py) can consume the same selection the
    renderer emits as JSONL — both go through this one function so the reread set never forks.
    Each entry carries the page identity (root/source/localPath/wikiPath/revision), the section
    id, and the section's reread block; local (project or locally checked-out shared) hard
    sections additionally seed the 1-hop depends-on closure appended at the end. A github_mcp
    shared section's closure is computed downstream by wiki_materialize_task.py (remote graph).
    """
    if data.get("schemaVersion") == SCHEMA_VERSION:
        notes, _ = _v6_task_notes(data, task_id, role)
        return [
            {
                "sourceId": note["sourceId"],
                "role": note["role"],
                "path": note["path"],
                "wikiId": note["wikiId"],
                "contentHash": note["contentHash"],
                "bindingDigest": note["bindingDigest"],
                "summary": note["summary"],
            }
            for note in notes
            if note.get("constraintStrength") == "hard"
        ]
    section_keys = _task_section_keys(data, task_id) if task_id else None
    entries: list[dict[str, Any]] = []
    emitted_keys: set[tuple[str, str]] = set()
    local_source_nodes: dict[str, list[str]] = {"project": [], "shared": []}

    for page in _selected_pages(data, section_keys):
        root = page.get("root")
        root_key = root if root in ("project", "shared") else "project"
        source = page.get("source") or "local"
        local_path = page.get("localPath")
        for section in _as_list(page.get("sections"), "sections"):
            if not section.get("hardConstraint") or not section.get("reread"):
                continue
            # Honor the section's role binding here too: a review-only card's full-text reread
            # must not be injected into an implementer prompt (and vice versa).
            if not _role_allows(section, role):
                continue
            section_id = section.get("sectionId") or section.get("section_name")
            entry = {
                "root": root,
                "source": page.get("source"),
                "displayPath": page.get("displayPath"),
                "localPath": local_path,
                "wikiPath": page.get("wikiPath"),
                "revision": page.get("revision"),
                "sectionId": section_id,
                "reread": section.get("reread"),
            }
            entries.append({key: value for key, value in entry.items() if value is not None})
            # Track local hard sections (project or locally checked-out shared) so we can close
            # their depends-on edges below; github_mcp sections have no local graph here.
            if source == "local" and local_path and section_id:
                emitted_keys.add((root_key, f"{local_path}#{section_id}"))
                local_source_nodes[root_key].append(f"{local_path}#{section_id}")

    entries.extend(_depends_on_closure_entries(local_source_nodes, emitted_keys))
    return entries


def render_reread_list(data: dict[str, Any], role: str = "implementer", task_id: str | None = None) -> str:
    entries = reread_entries(data, role, task_id)
    lines = [json.dumps(entry, ensure_ascii=False, sort_keys=True) for entry in entries]
    if lines:
        return "\n".join(lines)
    if task_id:
        return f"No hard-constraint rereads for task `{task_id}`."
    return "No hard-constraint rereads for selected wiki context."


def _normalize_task_text(task_text: str) -> str:
    lines = task_text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    lines = [line.rstrip() for line in lines]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


def _task_fingerprint(task_text: str) -> str:
    normalized = _normalize_task_text(task_text)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def load_ticket_roster(
    roster_path: Path,
    expected_feature_slug: str | None = None,
) -> dict[str, dict[str, str]]:
    """Load the host-produced ticket roster: the task identity + fingerprint source of truth.

    This is the host-agnostic boundary. The engine never reads a tracker, a plan document, or the
    network -- it fingerprints exactly the text it is handed. Each host's convention block tells the
    agent how to fill the roster (grill local-markdown reads `.scratch/<slug>/issues/<NN>-<slug>.md`,
    grill GitHub runs `gh issue view`, plain takes a user-specified source), so a new host needs a
    convention block and no engine change.

    Returns the same shape the renderer's fingerprint/scaffold paths consume: taskId -> title/text/hash.
    """
    # _load_json already rejects a non-object (as ValidationError) and unreadable/invalid JSON.
    raw = _load_json(roster_path, "ticket roster")
    source = raw.get("ticketSource")
    if source is not None and source not in TICKET_SOURCES:
        raise FingerprintError(f"Unknown ticketSource {source!r}; expected one of {', '.join(sorted(TICKET_SOURCES))}")
    roster_feature_slug = raw.get("featureSlug")
    if expected_feature_slug is not None:
        if not isinstance(expected_feature_slug, str) or not expected_feature_slug.strip():
            raise FingerprintError("wiki context requires a non-empty featureSlug to bind a ticket roster")
        if not isinstance(roster_feature_slug, str) or not roster_feature_slug.strip():
            raise FingerprintError("ticket roster requires a non-empty featureSlug matching the wiki context")
        if roster_feature_slug != expected_feature_slug:
            raise FingerprintError(
                f"ticket roster featureSlug {roster_feature_slug!r} does not match wiki context featureSlug {expected_feature_slug!r}"
            )
    entries = raw.get("tickets")
    if not isinstance(entries, list) or not entries:
        raise FingerprintError("Ticket roster has no tickets; expected a non-empty `tickets` array")

    tasks: dict[str, dict[str, str]] = {}
    for index, entry in enumerate(entries):
        ticket = _as_dict(entry, f"tickets[{index}]")
        task_id = ticket.get("taskId")
        if not isinstance(task_id, str) or not task_id.strip():
            raise FingerprintError(f"tickets[{index}] missing a non-empty taskId")
        task_id = task_id.strip()
        if task_id in tasks:
            raise FingerprintError(f"Duplicate taskId in ticket roster: {task_id}")
        text = ticket.get("text")
        if not isinstance(text, str) or not text.strip():
            raise FingerprintError(f"tickets[{index}] (taskId {task_id}) missing non-empty text to fingerprint")
        title = ticket.get("taskTitle")
        if not isinstance(title, str) or not title.strip():
            raise FingerprintError(f"tickets[{index}] (taskId {task_id}) missing a non-empty taskTitle")
        tasks[task_id] = {"title": title.strip(), "text": text, "hash": _task_fingerprint(text)}
    return tasks


def fingerprint_preflight(data: dict[str, Any], roster_path: Path) -> str:
    roster_tasks = load_ticket_roster(roster_path, data.get("featureSlug"))
    sidecar_tasks: dict[str, dict[str, Any]] = {}
    errors: list[str] = []
    for index, task_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        task_obj = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task_obj.get("taskId")
        if not isinstance(task_id, str) or not task_id:
            errors.append(f"taskWikiRefs[{index}] missing taskId")
            continue
        if task_id in sidecar_tasks:
            errors.append(f"duplicate sidecar taskId: {task_id}")
            continue
        sidecar_tasks[task_id] = task_obj

    for task_id, task in roster_tasks.items():
        sidecar = sidecar_tasks.get(task_id)
        if not sidecar:
            errors.append(f"roster ticket missing from taskWikiRefs: {task_id}")
            continue
        fingerprint = sidecar.get("taskFingerprint")
        if fingerprint != task["hash"]:
            errors.append(f"fingerprint mismatch for {task_id}: expected {fingerprint}, current {task['hash']}")

    for task_id in sorted(set(sidecar_tasks) - set(roster_tasks)):
        errors.append(f"taskWikiRefs contains task not found in the ticket roster: {task_id}")

    if errors:
        raise FingerprintError("\n".join(errors))
    return f"fingerprint preflight passed for {len(roster_tasks)} task(s)"


def bind_fingerprints(data: dict[str, Any], roster_path: Path) -> tuple[int, int, list[str]]:
    """Stamp each taskWikiRefs entry's taskFingerprint from the current ticket roster text.

    Routing (which sections bind to which task) stays author-owned; only the mechanical sha256 of
    the normalized ticket text is (re)written here, from the single source of truth in this
    module. Mirrors fingerprint_preflight's structural checks and refuses to write on any mismatch,
    so a successful bind guarantees the execution-side --fingerprint-preflight will pass.
    """
    roster_tasks = load_ticket_roster(roster_path, data.get("featureSlug"))
    sidecar_tasks: dict[str, dict[str, Any]] = {}
    errors: list[str] = []
    for index, task_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        task_obj = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task_obj.get("taskId")
        if not isinstance(task_id, str) or not task_id:
            errors.append(f"taskWikiRefs[{index}] missing taskId")
            continue
        if task_id in sidecar_tasks:
            errors.append(f"duplicate sidecar taskId: {task_id}")
            continue
        sidecar_tasks[task_id] = task_obj

    for task_id in sorted(set(sidecar_tasks) - set(roster_tasks)):
        errors.append(f"taskWikiRefs contains task not found in the ticket roster: {task_id}")
    for task_id in roster_tasks:
        if task_id not in sidecar_tasks:
            errors.append(f"roster ticket missing from taskWikiRefs: {task_id}")
    if errors:
        raise FingerprintError("\n".join(errors))

    changed = 0
    for task_id, task_obj in sidecar_tasks.items():
        current_hash = roster_tasks[task_id]["hash"]
        if task_obj.get("taskFingerprint") != current_hash:
            task_obj["taskFingerprint"] = current_hash
            changed += 1
    return len(sidecar_tasks), changed, sorted(sidecar_tasks)


def _default_destination_kind(section: dict[str, Any]) -> str:
    """Starting-guess routing for a freshly scaffolded section.

    hard/direct sections may never be planning-only (execution-ready validation rejects that), so they
    default to task-bound; soft context defaults to planning-only. The author confirms or overrides the
    kind and MUST supply a non-empty destination.reason before --execution-ready passes.
    """
    if section.get("hardConstraint") or section.get("relevance") == "direct":
        return "task-bound"
    return "planning-only"


def _derive_reread(page: dict[str, Any], section_id: str) -> dict[str, Any]:
    """Mechanically build the reread block every hardConstraint section needs.

    Derivable entirely from the page identity plus the section id, this removes the single most common
    authoring omission (a hard section missing reread, which fails execution-ready validation). Mirrors
    the page's path shape: localPath for local pages, wikiPath for github_mcp pages.
    """
    reread: dict[str, Any] = {"root": page.get("root"), "source": page.get("source")}
    if page.get("localPath"):
        reread["localPath"] = page["localPath"]
    if page.get("wikiPath"):
        reread["wikiPath"] = page["wikiPath"]
    reread["sectionId"] = section_id
    reread["includeDocumentContext"] = True
    return {key: value for key, value in reread.items() if value is not None}


def _read_card_roles(page: dict[str, Any], section_id: str) -> list[str] | None:
    """Read a section's binding-role restriction from its source wiki file, or None.

    Role binding is intrinsic to the skill and authoritative on the discovery-card marker, so the
    generator stamps it mechanically rather than trusting the researcher selection to carry it.
    Only project-local pages have a readable marker file; the path is resolved like the rest of the
    tool's relative paths (CWD = project root). Any failure — non-local page, missing file, parse
    error — degrades to None ("binds to every role"), never a hard error. extract_section_roles
    returns a value only for a strict-subset restriction, so unrestricted cards stamp nothing.
    """
    if page.get("root") not in (None, "project") or page.get("source") not in (None, "local"):
        return None
    candidate = page.get("displayPath") or page.get("path")
    if not candidate:
        return None
    try:
        path = Path(candidate)
        if not path.is_file():
            return None
        from wiki_section import extract_section_roles  # local import keeps the renderer stdlib-only otherwise

        return extract_section_roles(path.read_text(encoding="utf-8")).get(section_id)
    except Exception:
        return None


def _scaffold_section(page: dict[str, Any], raw_section: Any, page_index: int, section_index: int) -> dict[str, Any]:
    where = f"selection wikiPages[{page_index}].sections[{section_index}]"
    section = _as_dict(raw_section, where)
    section_id = section.get("sectionId") or section.get("section_name")
    if not section_id:
        raise ValidationError(f"{where} must include sectionId or section_name")
    section_id = str(section_id)

    out: dict[str, Any] = {"sectionId": section_id}
    for field_name in ("readDepth", "relevance", "confidence", "reason", "relevanceTo"):
        if section.get(field_name) is not None:
            out[field_name] = section[field_name]
    out["hardConstraint"] = bool(section.get("hardConstraint"))

    constraints = _as_dict(section.get("constraints") or {}, f"{where}.constraints")
    unknown = sorted(set(constraints) - set(CONSTRAINT_CATEGORIES))
    if unknown:
        raise ValidationError(f"{where}.constraints contains unsupported categories: {', '.join(unknown)}")
    # Keep only non-empty categories so the sidecar the planning agent reads (and every per-task
    # render) carry no empty buckets. _as_list still validates each present value is a list; an absent
    # category degrades to empty downstream (_as_list(None) -> []), so dropping empties is lossless.
    out["constraints"] = {
        category: items
        for category in CONSTRAINT_CATEGORIES
        if (items := _as_list(constraints.get(category), f"{where}.constraints.{category}"))
    }

    # destination.kind is a starting guess; reason stays empty on purpose so the author must justify
    # routing before --execution-ready (which requires a non-empty reason for every section) passes.
    # A task-bound default also seeds an empty tasks list for the author to fill with plan task ids
    # once --scaffold-tasks has populated the task roster.
    default_kind = _default_destination_kind(section)
    out["destination"] = {"kind": default_kind, "reason": ""}
    if default_kind == "task-bound":
        out["destination"]["tasks"] = []
    if out["hardConstraint"]:
        out["reread"] = _derive_reread(page, section_id)
    # Stamp the card's role binding from the authoritative marker (project-local pages only);
    # only a strict-subset restriction is recorded, so ordinary sections carry no `roles`.
    roles = _read_card_roles(page, section_id)
    if roles:
        out["roles"] = roles
    if "sourceAnchors" in section:
        out["sourceAnchors"] = _as_list(section.get("sourceAnchors"), f"{where}.sourceAnchors")
    if "caveats" in section:
        out["caveats"] = _as_list(section.get("caveats"), f"{where}.caveats")
    return out


def _scaffold_page(raw_page: Any, page_index: int) -> dict[str, Any]:
    where = f"selection wikiPages[{page_index}]"
    page = _as_dict(raw_page, where)
    if not any(page.get(key) for key in ("displayPath", "localPath", "wikiPath", "path")):
        raise ValidationError(f"{where} must include one of displayPath, localPath, wikiPath, or path")

    out: dict[str, Any] = {}
    for field_name in ("root", "source", "displayPath", "localPath", "wikiPath", "path", "revision"):
        if page.get(field_name) is not None:
            out[field_name] = page[field_name]
    out["documentContext"] = _as_dict(page.get("documentContext") or {}, f"{where}.documentContext")
    if "caveats" in page:
        out["caveats"] = _as_list(page.get("caveats"), f"{where}.caveats")
    if "maintenanceWarnings" in page:
        out["maintenanceWarnings"] = _as_list(page.get("maintenanceWarnings"), f"{where}.maintenanceWarnings")

    raw_sections = _as_list(page.get("sections"), f"{where}.sections")
    out["sections"] = [
        _scaffold_section(out, raw_section, page_index, section_index)
        for section_index, raw_section in enumerate(raw_sections)
    ]
    return out


def _scaffold_shared_wiki(selection: dict[str, Any], pages: list[dict[str, Any]]) -> dict[str, Any] | None:
    # Record shared-wiki identity only when a github_mcp page is actually selected (mirrors the
    # contract: omit the block entirely otherwise). Identity comes from the researcher's
    # sharedWikiSource (shared_wiki_status) so execution can later detect rebinding drift.
    if not any(page.get("source") == "github_mcp" for page in pages):
        return None
    source = selection.get("sharedWikiSource")
    if not isinstance(source, dict):
        return None
    repo_url = source.get("repoUrl")
    if not isinstance(repo_url, str) or not repo_url.strip():
        return None
    shared: dict[str, Any] = {"source": "github_mcp", "repoUrl": repo_url}
    if source.get("baseBranch"):
        shared["baseBranch"] = source["baseBranch"]
    if isinstance(source.get("revision"), dict):
        shared["revision"] = source["revision"]
    return shared


def _scaffold_v6_destination(note: dict[str, Any], is_skill: bool = False) -> None:
    hard = not is_skill and note.get("constraintStrength") == "hard"
    note["destination"] = {"kind": "task-bound" if hard or is_skill else "planning-only", "reason": ""}
    if note["destination"]["kind"] == "task-bound":
        note["destination"]["tasks"] = []


def _scaffold_v6_from_selection(selection: dict[str, Any], feature_slug: str | None, ticket_source: str | None) -> dict[str, Any]:
    bindings = [_as_dict(binding, "selection.wikiBindings[]") for binding in _as_list(selection.get("wikiBindings"), "selection.wikiBindings")]
    notes = [_validate_v6_note(note, "selection.wikiNotes[]") for note in _as_list(selection.get("wikiNotes"), "selection.wikiNotes")]
    skills = [_validate_v6_note(skill, "selection.requiredSkills[]", require_skill=True) for skill in _as_list(selection.get("requiredSkills"), "selection.requiredSkills")]
    data: dict[str, Any] = {
        "schemaVersion": SCHEMA_VERSION,
        "kind": KIND,
        "generatedBy": SCAFFOLD_GENERATED_BY,
        "snapshotHash": selection.get("snapshotHash"),
        "wikiBindings": bindings,
        "wikiNotes": [dict(note) for note in notes],
        "requiredSkills": [dict(skill) for skill in skills],
        "taskRouting": dict(SCAFFOLD_TASK_ROUTING),
        "taskWikiRefs": [],
        "caveats": _as_list(selection.get("caveats"), "selection.caveats") if "caveats" in selection else [],
        "maintenanceWarnings": _as_list(selection.get("maintenanceWarnings"), "selection.maintenanceWarnings") if "maintenanceWarnings" in selection else [],
    }
    if feature_slug:
        data["featureSlug"] = feature_slug
    if ticket_source:
        data["ticketSource"] = ticket_source
    for note in data["wikiNotes"]:
        _scaffold_v6_destination(note)
    for skill in data["requiredSkills"]:
        _scaffold_v6_destination(skill, is_skill=True)
    return data


def scaffold_from_selection(
    selection: dict[str, Any], feature_slug: str | None, ticket_source: str | None
) -> dict[str, Any]:
    """Build a schema-v6 sidecar skeleton from a bound Obsidian metadata selection.

    The generator carries only binding, Note identity, path, hash, summary, and declared Skill Card
    roles. It adds task routing plus default destinations; the author then supplies routing reasons and
    task-bound task ids. taskWikiRefs remain empty until the host-produced ticket roster is finalized.
    Legacy section selections cannot create a new schema-v5 sidecar during this transition.
    """
    if ticket_source is not None and ticket_source not in TICKET_SOURCES:
        raise ValidationError(f"Unknown ticketSource {ticket_source!r}; expected one of {', '.join(sorted(TICKET_SOURCES))}")
    if selection.get("phase") != "plan":
        raise ValidationError("Obsidian selection.phase must be plan before Carry can scaffold a sidecar")
    if selection.get("status") not in {"ok", "partial"}:
        raise ValidationError("Obsidian selection.status must be ok or partial before Carry can scaffold a sidecar")
    if "wikiNotes" in selection or "wikiBindings" in selection or "requiredSkills" in selection:
        return _scaffold_v6_from_selection(selection, feature_slug, ticket_source)
    raise ValidationError(
        "Legacy section selection cannot create a new schemaVersion 5 sidecar. "
        "schemaVersion 5 is read-only during the Obsidian transition; run wiki-research against bound "
        "Obsidian Sources and scaffold contracts/obsidian-wiki-selection-v1.example.jsonc into schemaVersion 6."
    )
def scaffold_tasks(data: dict[str, Any], roster_path: Path) -> tuple[list[str], list[str]]:
    """Scaffold one taskWikiRefs entry per roster ticket (the task roster + fingerprint anchor).

    taskId/taskTitle come mechanically from the ticket roster (load_ticket_roster). Any prior
    taskFingerprint/caveats are preserved for surviving tasks so re-running after a ticket edit is
    idempotent; tasks no longer in the roster are dropped and reported. taskFingerprint is never stamped
    here -- that stays --bind-fingerprints' single responsibility. Section->task routing is NOT touched
    here: it lives on each section's destination.tasks, independent of this roster.
    """
    roster_tasks = load_ticket_roster(roster_path, data.get("featureSlug"))
    existing: dict[str, dict[str, Any]] = {}
    for index, raw_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        ref = _as_dict(raw_ref, f"taskWikiRefs[{index}]")
        task_id = ref.get("taskId")
        if isinstance(task_id, str) and task_id:
            existing[task_id] = ref

    new_refs: list[dict[str, Any]] = []
    for task_id, task in roster_tasks.items():
        prev = existing.get(task_id)
        ref: dict[str, Any] = {"taskId": task_id, "taskTitle": task["title"]}
        if prev and prev.get("taskFingerprint"):
            ref["taskFingerprint"] = prev["taskFingerprint"]
        if prev and prev.get("caveats"):
            ref["caveats"] = prev["caveats"]
        new_refs.append(ref)

    dropped = sorted(set(existing) - set(roster_tasks))
    data["taskWikiRefs"] = new_refs
    return list(roster_tasks), dropped


def _write_context(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    tmp = path.with_name(path.name + ".tmp")
    # Pin LF so the sidecar is byte-deterministic across platforms (Windows text mode
    # would otherwise translate "\n" to "\r\n" and churn against an LF-committed file).
    with tmp.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    tmp.replace(path)


def main() -> int:
    _configure_stdio()
    parser = argparse.ArgumentParser(description="Validate and render schemaVersion 5 compatibility or schemaVersion 6 Obsidian wiki context JSON.")
    parser.add_argument("context_path", help="Path to .adapter/context/<feature-slug>.wiki-context.json")
    parser.add_argument("--task", action="append", default=[], help="Deprecated compatibility option; selected wiki context is not filtered by task string")
    parser.add_argument("--task-id", help="Render only wiki refs bound to the finalized ticket id, plus global refs")
    parser.add_argument("--ticket-roster", help="Path to the host-produced ticket roster JSON (.adapter/context/<feature-slug>.ticket-roster.json) used as the task identity + fingerprint source")
    parser.add_argument("--project-root", help="Project root used to revalidate ADR projection authority (defaults to the current directory)")
    parser.add_argument("--feature-slug", help="With --scaffold, the feature identity stamped into the sidecar")
    parser.add_argument("--ticket-source", choices=sorted(TICKET_SOURCES), help="With --scaffold, records where the roster's tickets came from (audit metadata; the engine never branches on it)")
    parser.add_argument("--execution-ready", action="store_true", help="Require confirmed taskRouting and per-section destination routing suitable for execution")
    parser.add_argument("--fingerprint-preflight", action="store_true", help="Compare taskWikiRefs fingerprints against the current ticket roster text")
    parser.add_argument("--bind-fingerprints", action="store_true", help="Stamp taskWikiRefs taskFingerprint values from the current ticket roster text and write the sidecar in place (requires --ticket-roster)")
    parser.add_argument("--role", choices=["implementer", "reviewer"], default="implementer")
    parser.add_argument("--format", choices=["markdown"], default="markdown")
    parser.add_argument("--validate-only", action="store_true")
    parser.add_argument("--reread-list", action="store_true")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--scaffold", metavar="SELECTION_JSON", help="Generate a sidecar skeleton from a wiki-researcher selection JSON and write it to the positional context path")
    parser.add_argument("--keep-selection", action="store_true", help="With --scaffold, keep the consumed selection JSON instead of removing it on success (for tests/debugging, or to regenerate from an edited selection)")
    parser.add_argument("--scaffold-tasks", action="store_true", help="Scaffold the taskWikiRefs roster (taskId/taskTitle) from the ticket roster into the existing sidecar, preserving any prior taskFingerprint (requires --ticket-roster)")
    parser.add_argument("--finalize", action="store_true", help="One-shot planning finalize after the single destination edit pass: scaffold the taskWikiRefs roster from the ticket roster, stamp every taskFingerprint, validate execution readiness, and write the sidecar once (requires --ticket-roster). Combines --scaffold-tasks + --bind-fingerprints into a single write.")
    args = parser.parse_args()
    project_root = Path(args.project_root).resolve() if args.project_root else Path.cwd().resolve()

    try:
        if args.scaffold and args.scaffold_tasks:
            raise ValidationError("Run --scaffold and --scaffold-tasks in separate invocations: --scaffold builds the sidecar from a selection, --scaffold-tasks adds task routing once the ticket roster exists")
        if args.finalize and (args.scaffold or args.scaffold_tasks or args.bind_fingerprints):
            raise ValidationError("--finalize already runs scaffold-tasks + bind-fingerprints in one write; do not combine it with --scaffold, --scaffold-tasks, or --bind-fingerprints")
        if args.scaffold:
            selection_path = Path(args.scaffold)
            selection = _load_json(selection_path, "wiki selection")
            data = scaffold_from_selection(selection, args.feature_slug, args.ticket_source)
            _validate_context(data, args.strict, execution_ready=False, project_root=project_root)
            context_path = Path(args.context_path)
            _write_context(context_path, data)
            selected_count = len(data["wikiNotes"]) if data.get("schemaVersion") == SCHEMA_VERSION else len(data["wikiPages"])
            selected_label = "Note(s)" if data.get("schemaVersion") == SCHEMA_VERSION else "page(s)"
            summary = f"scaffolded wiki context with {selected_count} {selected_label} -> {args.context_path}"
            # The selection is a transient intermediate: scaffolding is its only consumer (execution reads
            # the generated sidecar, never the selection). Remove it on success so only the plan and its
            # .wiki-context.json persist. A malformed selection raises above before this write, so a failed
            # scaffold always keeps the selection for repair. --keep-selection opts out (tests/debugging,
            # or to regenerate from an edited selection).
            if args.keep_selection:
                print(f"{summary} (kept selection {selection_path})")
            elif selection_path.resolve() == context_path.resolve():
                print(f"{summary} (selection path equals context path; not removed)")
            else:
                try:
                    selection_path.unlink()
                    print(f"{summary}; removed consumed selection {selection_path}")
                except OSError as exc:
                    print(f"Warning: scaffolded the sidecar but could not remove selection {selection_path}: {exc}", file=sys.stderr)
                    print(summary)
            return 0
        data = _load_context(Path(args.context_path))
        if args.finalize:
            if not args.ticket_roster:
                raise ValidationError("--finalize requires --ticket-roster")
            # Single transactional finalize for the planning flow, run once after the author's lone
            # destination edit pass: refresh the task roster from the ticket roster (idempotent,
            # preserving prior fingerprints), validate structure, stamp every taskFingerprint from the
            # current ticket text, then confirm the result is fully execution-ready before the one
            # write. Combining scaffold-tasks + bind into a single write means the planning agent's
            # Read-tracked sidecar is re-surfaced once here instead of after two separate rewrites.
            task_ids, dropped = scaffold_tasks(data, Path(args.ticket_roster))
            _validate_context(data, args.strict, execution_ready=False, project_root=project_root)
            total, changed, _ = bind_fingerprints(data, Path(args.ticket_roster))
            _validate_context(data, args.strict, execution_ready=True, project_root=project_root)
            _write_context(Path(args.context_path), data)
            for task_id in dropped:
                print(f"Warning: dropped taskWikiRefs entry no longer in the ticket roster: {task_id}", file=sys.stderr)
            status = f"{changed} updated" if changed else "already current"
            print(f"finalized {total} task(s) ({status}): {', '.join(task_ids)}")
            return 0
        if args.scaffold_tasks:
            if not args.ticket_roster:
                raise ValidationError("--scaffold-tasks requires --ticket-roster")
            task_ids, dropped = scaffold_tasks(data, Path(args.ticket_roster))
            _validate_context(data, args.strict, execution_ready=False, project_root=project_root)
            _write_context(Path(args.context_path), data)
            for task_id in dropped:
                print(f"Warning: dropped taskWikiRefs entry no longer in the ticket roster: {task_id}", file=sys.stderr)
            print(f"scaffolded {len(task_ids)} task(s): {', '.join(task_ids)}")
            return 0
        if args.bind_fingerprints:
            if not args.ticket_roster:
                raise ValidationError("--bind-fingerprints requires --ticket-roster")
            # Validate structure but tolerate missing/placeholder fingerprints; stamping fixes them.
            _validate_context(data, args.strict, execution_ready=False, project_root=project_root)
            total, changed, task_ids = bind_fingerprints(data, Path(args.ticket_roster))
            # With real fingerprints stamped, confirm the result is fully execution-ready before
            # writing, so a successful bind is transactional (correct fingerprints + valid routing).
            if args.execution_ready:
                _validate_context(data, args.strict, execution_ready=True, project_root=project_root)
            _write_context(Path(args.context_path), data)
            status = f"{changed} updated" if changed else "already current"
            print(f"bound taskFingerprint for {total} task(s) ({status}): {', '.join(task_ids)}")
            return 0
        caveats = _validate_context(data, args.strict, args.execution_ready, project_root)
        if args.fingerprint_preflight:
            if not args.ticket_roster:
                raise ValidationError("--fingerprint-preflight requires --ticket-roster")
            print(fingerprint_preflight(data, Path(args.ticket_roster)))
            return 0
        if args.validate_only:
            # --ticket-roster alone cannot catch stale fingerprints in validate-only mode (format-only),
            # so when execution-ready validation is requested with a roster, run the same fingerprint
            # preflight execution uses. This closes the gap where placeholder/stale fingerprints
            # passed planning validation and only failed later at dispatch time.
            if args.execution_ready and args.ticket_roster:
                fingerprint_preflight(data, Path(args.ticket_roster))
            for caveat in caveats:
                print(f"Warning: {caveat}", file=sys.stderr)
            print("wiki context JSON is valid")
            return 0
        if args.reread_list:
            print(render_reread_list(data, args.role, args.task_id))
            return 0
        print(render_markdown(data, args.role, args.task_id))
        return 0
    except (ValidationError, FingerprintError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
