#!/usr/bin/env python3
"""Generated by grill-adapter.

Single fixed fetcher that materializes a task's hard-constraint full-section rereads from BOTH
sources into one rendered wiki file:

  - `source: local` (project / shared local wiki) -> extracted straight from the filesystem.
  - `source: github_mcp` (shared wiki) -> fetched via the shared-wiki MCP `read-sections` CLI,
    which reuses the MCP server's own loadConfig + readSectionsTool (one shared-wiki reader,
    not a re-implementation), so it returns the connected repo's revision + repoUrl for drift
    detection.

The task-scoped hard-constraint reread set comes from wiki_context_render.reread_entries (the
same selection behind `--reread-list`), which also closes each LOCAL hard section's 1-hop
`depends-on` edges. github_mcp shared sections cannot be closed by the renderer (their graph is
remote), so this fetcher closes them here too: it queries the shared-wiki `graph-neighbors` CLI
for each selected github_mcp hard node and folds its indexed `depends-on` section targets into
the same read-sections batch. Both closure paths share wiki_common.depends_on_closure_targets, so
what counts as a closed edge never forks. The rendered output is appended under a
`## Hard Wiki Constraint Rereads` heading (or printed to stdout), so a subagent reads the
authoritative full section text in the same file as the rest of its wiki constraints; a section
pulled in by closure is labelled with the node it was closed from. Fails closed on shared-wiki
rebinding drift, revision drift, section errors, or partial results -- it never silently drops a
hard constraint.

Usage:
  wiki_materialize_task.py <context.json> --task-id <id> [--role implementer|reviewer]
      [--project-root <path>] [--append-to <file>] [--strict] [--execution-ready]
      [--shared-wiki-cmd "<cmd>"] [--allow-revision-drift]
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from wiki_context_render import (  # noqa: E402
    ValidationError,
    _load_context,
    _v6_task_notes,
    _validate_context,
    reread_entries,
)
from adr_identity import AdrIdentityError, validate_identity  # noqa: E402
from wiki_section import (  # noqa: E402
    extract_document_context_from_index,
    extract_section,
    list_section_ids,
)
from wiki_common import depends_on_closure_targets, repo_root, select_wiki_root  # noqa: E402

MCP_SOURCE = "github_mcp"
REREAD_HEADING = "## Hard Wiki Constraint Rereads"
REREAD_PREAMBLE = (
    "Authoritative full-section rereads of this task's hard constraints. Treat them as binding; "
    "do not substitute sibling sections or whole-page body text."
)
# Server names the README documents for the generic registration, tried in order before the
# heuristic args scan. Keep `shared-wiki` first (the documented name).
SHARED_WIKI_SERVER_NAMES = ("shared-wiki", "shared_wiki", "sharedWiki", "shared-wiki-mcp")


class MaterializeError(Exception):
    pass


def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass


def _eff(entry: dict[str, Any], key: str) -> Any:
    """Effective value: the reread block overrides the entry when it sets the key."""
    reread = entry.get("reread") if isinstance(entry.get("reread"), dict) else {}
    value = reread.get(key)
    return value if value is not None else entry.get(key)


def _entry_source(entry: dict[str, Any]) -> str:
    return str(_eff(entry, "source") or "local")


def _closure_via(entry: dict[str, Any]) -> str | None:
    """The source node a closure entry was pulled in from, or None for a direct selection."""
    if entry.get("closureType") == "depends-on" and entry.get("closedVia"):
        return str(entry["closedVia"])
    return None


def _display_rel(path: Path, wiki_root: Path) -> str:
    try:
        return path.relative_to(wiki_root).as_posix()
    except ValueError:
        return path.as_posix()


def _rev_match(expected: str, actual: str) -> bool:
    expected, actual = expected.strip(), actual.strip()
    if expected == actual:
        return True
    n = min(len(expected), len(actual))
    return n >= 7 and expected[:n] == actual[:n]


def _materialize_local(entry: dict[str, Any], project_root: Path) -> dict[str, Any]:
    root_name = _eff(entry, "root") or "project"
    if root_name not in {"project", "shared"}:
        raise MaterializeError(f"unsupported local wiki root: {root_name}")
    wiki = select_wiki_root(project_root, root_name)

    local_path = _eff(entry, "localPath") or entry.get("displayPath") or _eff(entry, "wikiPath")
    if not local_path:
        raise MaterializeError(f"local reread entry missing localPath: {entry}")
    file_path = Path(local_path)
    if not file_path.is_absolute():
        file_path = wiki.path / file_path

    section_id = _eff(entry, "sectionId")
    if not file_path.is_file():
        raise MaterializeError(f"wiki file not found: {file_path}")
    text = file_path.read_text(encoding="utf-8")
    content = extract_section(text, section_id)
    if content is None:
        available = list_section_ids(text)
        hint = f"; available sections: {', '.join(available)}" if available else ""
        raise MaterializeError(f"section '{section_id}' not found in {file_path.name}{hint}")

    index_path = file_path.parent / f"{file_path.stem}.index.md"
    title: Any = None
    overview: Any = None
    caveats: list[str] = ["companion section index not found"]
    context_source: str | None = None
    if index_path.is_file():
        context = extract_document_context_from_index(index_path.read_text(encoding="utf-8"))
        title = context.get("title")
        overview = context.get("overview")
        caveats = list(context.get("caveats") or [])
        context_source = _display_rel(index_path, wiki.path)

    return {
        "displayPath": entry.get("displayPath") or local_path,
        "root": root_name,
        "source": _entry_source(entry),
        "sectionId": section_id,
        "revision": None,
        "title": title,
        "overview": overview,
        "contextSource": context_source,
        "caveats": caveats,
        "content": content,
        "closedVia": _closure_via(entry),
    }


def _materialize_mcp(
    entries: list[dict[str, Any]],
    data: dict[str, Any],
    project_root: Path,
    cmd: dict[str, Any],
    allow_revision_drift: bool,
) -> dict[tuple[str, str], dict[str, Any]]:
    sections = []
    for entry in entries:
        wiki_path = _eff(entry, "wikiPath") or entry.get("displayPath")
        if not wiki_path:
            raise MaterializeError(f"github_mcp reread entry missing wikiPath: {entry}")
        sections.append({"path": wiki_path, "section": _eff(entry, "sectionId"), "includeDocumentContext": True})

    payload = _invoke_cli(cmd, project_root, {"sections": sections, "includeDocumentContext": True, "errorMode": "strict"})

    global_caveats: list[str] = []
    _check_drift(data, payload, allow_revision_drift, global_caveats)

    revision = (payload.get("revision") or {}).get("commitSha") if isinstance(payload.get("revision"), dict) else None
    by_key: dict[tuple[str, str], dict[str, Any]] = {}
    for item in payload.get("results") or []:
        if isinstance(item, dict) and item.get("status") == "ok":
            by_key[(item.get("path"), item.get("section"))] = item

    materialized: dict[tuple[str, str], dict[str, Any]] = {}
    for entry in entries:
        wiki_path = _eff(entry, "wikiPath") or entry.get("displayPath")
        section_id = _eff(entry, "sectionId")
        item = by_key.get((wiki_path, section_id))
        if item is None:
            raise MaterializeError(f"shared-wiki CLI returned no usable section for {wiki_path}#{section_id}")
        doc = item.get("documentContext") if isinstance(item.get("documentContext"), dict) else {}
        materialized[(wiki_path, section_id)] = {
            "displayPath": entry.get("displayPath") or item.get("displayPath") or wiki_path,
            "root": _eff(entry, "root") or "shared",
            "source": MCP_SOURCE,
            "sectionId": section_id,
            "revision": revision,
            "title": doc.get("title"),
            "overview": doc.get("overview"),
            "contextSource": doc.get("contextSource") or doc.get("displayPath"),
            "caveats": list(doc.get("caveats") or []) + global_caveats,
            "content": item.get("content") or "",
            "closedVia": _closure_via(entry),
        }
    return materialized


def _check_drift(data: dict[str, Any], payload: dict[str, Any], allow_revision_drift: bool, caveats_out: list[str]) -> None:
    shared = data.get("sharedWiki") if isinstance(data.get("sharedWiki"), dict) else {}
    expected_repo = shared.get("repoUrl")
    actual_repo = payload.get("repoUrl")
    if expected_repo and actual_repo and expected_repo != actual_repo:
        raise MaterializeError(
            f"shared-wiki rebinding drift: sidecar sharedWiki.repoUrl {expected_repo!r} != connected repo "
            f"{actual_repo!r}; the project rebound its shared wiki after planning. Re-confirm the binding before rereading."
        )

    expected_rev = None
    rev = shared.get("revision")
    if isinstance(rev, dict):
        expected_rev = rev.get("commitSha") or rev.get("shortSha") or rev.get("ref")
    actual_rev = (payload.get("revision") or {}).get("commitSha") if isinstance(payload.get("revision"), dict) else None
    if expected_rev and actual_rev and not _rev_match(str(expected_rev), str(actual_rev)):
        message = (
            f"shared-wiki revision drift: sidecar revision {expected_rev} != connected HEAD {actual_rev}; "
            "the shared wiki moved since planning."
        )
        if allow_revision_drift:
            caveats_out.append(f"{message} (proceeding under --allow-revision-drift; reverify constraints against current text)")
        else:
            raise MaterializeError(f"{message} Re-confirm the constraints, or pass --allow-revision-drift to proceed with a caveat.")


def _invoke_cli(
    cmd: dict[str, Any],
    project_root: Path,
    request: dict[str, Any],
    subcommand: str = "read-sections",
) -> dict[str, Any]:
    env = dict(os.environ)
    env.update(cmd.get("env") or {})
    # The CLI self-configures from CLAUDE_PROJECT_DIR exactly like the stdio server, so point it
    # at this project's root to resolve wiki.sharedMcp.
    env["CLAUDE_PROJECT_DIR"] = str(project_root)
    argv = list(cmd["argv"]) + [subcommand]
    try:
        proc = subprocess.run(
            argv,
            input=json.dumps(request),
            capture_output=True,
            text=True,
            encoding="utf-8",
            env=env,
        )
    except OSError as exc:
        raise MaterializeError(f"failed to launch shared-wiki MCP CLI {argv!r}: {exc}") from exc
    if proc.returncode != 0:
        detail = (proc.stderr or "").strip() or (proc.stdout or "").strip()
        raise MaterializeError(f"shared-wiki MCP CLI failed (exit {proc.returncode}): {detail}")
    out = (proc.stdout or "").strip()
    if not out:
        raise MaterializeError("shared-wiki MCP CLI produced no output")
    try:
        parsed = json.loads(out.splitlines()[-1])
    except (json.JSONDecodeError, IndexError) as exc:
        raise MaterializeError(f"could not parse shared-wiki MCP CLI output: {exc}; output was: {out[:500]}")
    if not isinstance(parsed, dict):
        raise MaterializeError("shared-wiki MCP CLI output was not a JSON object")
    if parsed.get("status") not in (None, "ok"):
        raise MaterializeError(f"shared-wiki MCP CLI returned status {parsed.get('status')!r} (expected ok): {parsed.get('errors')}")
    return parsed


def _graph_neighbors_via_cli(
    cmd: dict[str, Any],
    project_root: Path,
    nodes: list[str],
) -> dict[str, dict[str, Any]]:
    """1-hop neighbor slices for `nodes` from the shared-wiki `graph-neighbors` CLI.

    Returns the connected shared graph's slice map ({node: {"out": [...], "in": [...]}}),
    each out-edge carrying `type` and an `indexed` flag. The CLI shares the server's
    loadConfig + graphNeighborsTool, so it reads the same remote graph at the same HEAD the
    follow-up read-sections call materializes against.
    """
    payload = _invoke_cli(cmd, project_root, {"nodes": nodes}, subcommand="graph-neighbors")
    neighbors = payload.get("neighbors")
    slices: dict[str, dict[str, Any]] = {}
    if isinstance(neighbors, dict):
        for node, slice_ in neighbors.items():
            if isinstance(slice_, dict):
                slices[node] = {"out": slice_.get("out") or [], "in": slice_.get("in") or []}
    return slices


def _github_mcp_closure_entries(
    mcp_entries: list[dict[str, Any]],
    cmd: dict[str, Any],
    project_root: Path,
) -> tuple[list[dict[str, Any]], int, str | None]:
    """1-hop depends-on closure for github_mcp hard sections against the remote shared graph.

    The renderer closes depends-on edges for LOCAL roots only (it cannot reach the remote
    graph); this is the symmetric closure for github_mcp shared sections. For each directly
    selected github_mcp hard node we pull its `depends-on` section targets (via the same
    wiki_common.depends_on_closure_targets the renderer uses) into the reread set, gated on
    the graph's `indexed` flag so a follow-up read-sections can actually serve them. Returns
    (synthesized github_mcp reread entries, count of unindexed depends-on targets skipped, a
    degrade caveat or None). Deduped against the already-selected github_mcp sections; bounded
    to one hop (closure entries themselves are not re-closed).

    Closure is an additive convenience, mirroring the renderer's local-graph closure: if the
    graph-neighbors CLI is unavailable or errors (e.g. a shared-wiki MCP deployment that
    predates the graph-neighbors subcommand), degrade to "no closure" with a caveat rather than
    failing the materialization. The directly-selected hard constraints still fail closed via
    the strict read-sections batch.
    """
    direct = [entry for entry in mcp_entries if not _closure_via(entry)]
    nodes: list[str] = []
    seen_nodes: set[str] = set()
    for entry in direct:
        wiki_path = _eff(entry, "wikiPath") or entry.get("displayPath")
        section_id = _eff(entry, "sectionId")
        if not wiki_path or not section_id:
            continue
        node = f"{wiki_path}#{section_id}"
        if node not in seen_nodes:
            seen_nodes.add(node)
            nodes.append(node)
    if not nodes:
        return [], 0, None

    try:
        slices = _graph_neighbors_via_cli(cmd, project_root, nodes)
    except MaterializeError as exc:
        return [], 0, f"depends-on closure skipped (graph-neighbors unavailable): {exc}"
    existing = {
        (_eff(entry, "wikiPath") or entry.get("displayPath"), _eff(entry, "sectionId"))
        for entry in mcp_entries
    }

    all_targets = depends_on_closure_targets(slices, nodes, require_indexed=False)
    indexed_keys = {(page, section) for _, page, section in depends_on_closure_targets(slices, nodes, require_indexed=True)}
    skipped = sum(
        1 for _, page, section in all_targets if (page, section) not in indexed_keys and (page, section) not in existing
    )

    entries: list[dict[str, Any]] = []
    for closed_via, page, section in all_targets:
        if (page, section) not in indexed_keys:
            continue
        if (page, section) in existing:
            continue
        existing.add((page, section))
        entries.append({
            "root": "shared",
            "source": MCP_SOURCE,
            "wikiPath": page,
            "sectionId": section,
            "reread": {"wikiPath": page, "sectionId": section, "includeDocumentContext": True},
            "closureType": "depends-on",
            "closedVia": closed_via,
        })
    return entries, skipped, None


def _resolve_shared_wiki_cmd(explicit: str | None, project_root: Path) -> dict[str, Any] | None:
    if explicit:
        return {"argv": shlex.split(explicit), "env": {}}
    env_cmd = os.environ.get("SHARED_WIKI_MCP_CMD")
    if env_cmd:
        return {"argv": shlex.split(env_cmd), "env": {}}
    for candidate in _registration_candidates(project_root):
        resolved = _cmd_from_registration(candidate)
        if resolved:
            return resolved
    return _bundled_cmd()


def _bundled_cmd() -> dict[str, Any] | None:
    """The shared-wiki MCP bundle shipped next to this script inside the plugin.

    A plugin-bundled MCP is registered in ``${CLAUDE_PLUGIN_ROOT}/.mcp.json``, which none of the
    ``_registration_candidates`` paths cover -- so registration discovery comes up empty for the
    very server we ship. This script lives at ``<plugin_root>/scripts/``, so self-locate the
    bundle the way the hooks self-locate via ``BASH_SOURCE``. Tried last, so an explicit flag, an
    env var, or a real registration (an externally deployed server) all still win.
    """
    entry = Path(__file__).resolve().parent.parent / "mcp" / "shared-wiki" / "dist" / "index.js"
    if not entry.is_file():
        return None
    return {"argv": ["node", entry.as_posix()], "env": {}}


def _registration_candidates(project_root: Path) -> list[Path]:
    home = Path.home()
    return [
        project_root / ".mcp.json",
        project_root / ".claude" / "settings.local.json",
        project_root / ".claude" / "settings.json",
        home / ".claude.json",
        home / ".claude" / "settings.json",
    ]


def _cmd_from_registration(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    server = _pick_shared_wiki_server(data.get("mcpServers") if isinstance(data, dict) else None)
    if not isinstance(server, dict):
        return None
    command = server.get("command")
    args = server.get("args") or []
    if not isinstance(command, str) or not isinstance(args, list):
        return None
    env = server.get("env") if isinstance(server.get("env"), dict) else {}
    return {
        "argv": [command, *[str(arg) for arg in args]],
        "env": {str(key): str(value) for key, value in env.items()},
    }


def _pick_shared_wiki_server(servers: Any) -> dict[str, Any] | None:
    if not isinstance(servers, dict):
        return None
    for name in SHARED_WIKI_SERVER_NAMES:
        server = servers.get(name)
        if isinstance(server, dict):
            return server
    # Fallback: any server whose args point at a shared-wiki dist entry.
    for server in servers.values():
        if not isinstance(server, dict):
            continue
        joined = " ".join(str(arg) for arg in (server.get("args") or [])).lower()
        if "shared-wiki" in joined and ("index.js" in joined or joined.endswith(".js")):
            return server
    return None


def _render_section_block(mat: dict[str, Any]) -> str:
    # The heading (displayPath # sectionId) is the provenance; its wiki-root prefix already signals
    # project vs shared, so the root/source rows are dropped. Document/Overview/Context-source rows are
    # dropped too: they duplicated the top-half page context (the same page renders there) or degraded
    # to a bare "Type: constraint". What stays is what the reader acts on -- the revision stamp (drift
    # authority), the closure provenance, any drift caveats, and the authoritative full text.
    lines = [f"### Reread: `{mat['displayPath']}` # `{mat['sectionId']}`"]
    if mat.get("revision"):
        lines.append(f"- Revision: `{mat['revision']}`")
    if mat.get("closedVia"):
        lines.append(f"- Pulled in via: depends-on closure of `{mat['closedVia']}`")
    for caveat in mat.get("caveats") or []:
        lines.append(f"- Caveat: {caveat}")
    required_skill = mat.get("requiredSkill")
    if isinstance(required_skill, dict):
        lines.extend(
            [
                "#### Required executable skill",
                "",
                f"MUST invoke project skill `{required_skill['name']}` for this "
                f"`{required_skill['role']}` task before acting on the Card below.",
                "The Card text is discovery metadata; the verified pack is the executable procedure.",
            ]
        )
    lines.append("#### Full section text")
    lines.append("")
    lines.append(mat["content"])
    return "\n".join(lines)


def _render_rereads(materialized: list[dict[str, Any]]) -> str:
    out = [REREAD_HEADING, "", REREAD_PREAMBLE, ""]
    out.append("\n\n".join(_render_section_block(mat) for mat in materialized))
    return "\n".join(out).rstrip() + "\n"


def _obsidian_cmd(explicit: str | None) -> dict[str, Any] | None:
    if explicit:
        return {"argv": shlex.split(explicit), "env": {}}
    env_cmd = os.environ.get("OBSIDIAN_WIKI_MCP_CMD")
    if env_cmd:
        return {"argv": shlex.split(env_cmd), "env": {}}
    entry = Path(__file__).resolve().parent.parent / "mcp" / "obsidian-wiki" / "dist" / "index.js"
    if entry.is_file():
        return {"argv": ["node", entry.as_posix()], "env": {}}
    return None


def _invoke_obsidian_cli(cmd: dict[str, Any], project_root: Path, request: dict[str, Any], subcommand: str) -> dict[str, Any]:
    env = dict(os.environ)
    env.update(cmd.get("env") or {})
    env["CLAUDE_PROJECT_DIR"] = str(project_root)
    argv = [*cmd["argv"], subcommand]
    try:
        proc = subprocess.run(argv, input=json.dumps(request), capture_output=True, text=True, encoding="utf-8", env=env)
    except OSError as exc:
        raise MaterializeError(f"failed to launch Obsidian Wiki MCP CLI {argv!r}: {exc}") from exc
    if proc.returncode != 0:
        # A failed MCP process may have emitted partial Note content on stdout. Never copy it
        # into a fail-open reviewer handoff or other diagnostic surface.
        detail = (proc.stderr or "").strip() or f"exit code {proc.returncode}; stdout discarded"
        raise MaterializeError(f"Obsidian Wiki MCP CLI failed (exit {proc.returncode}): {detail}")
    try:
        result = json.loads((proc.stdout or "").strip().splitlines()[-1])
    except (json.JSONDecodeError, IndexError) as exc:
        raise MaterializeError(f"could not parse Obsidian Wiki MCP CLI output: {exc}") from exc
    if not isinstance(result, dict):
        raise MaterializeError("Obsidian Wiki MCP CLI output was not a JSON object")
    return result


def _assert_v6_note_matches(expected: dict[str, Any], actual: dict[str, Any], role: str, is_skill: bool) -> None:
    identity = f"{expected.get('path')} ({expected.get('wikiId')})"
    for key in ("sourceId", "role", "path", "wikiId", "type", "bindingDigest", "contentHash"):
        if actual.get(key) != expected.get(key):
            if key == "contentHash":
                raise MaterializeError(f"Obsidian Note content drift for {identity}")
            raise MaterializeError(f"Obsidian Note {key} drift for {identity}")
    if actual.get("summary") != expected.get("summary"):
        raise MaterializeError(f"Obsidian Note summary drift for {identity}")
    expected_adr = (
        expected.get("adrSourceId"),
        expected.get("adrSourcePath"),
        expected.get("adrSourceContentHash"),
    )
    actual_adr = (
        actual.get("adrSourceId"),
        actual.get("adrSourcePath"),
        actual.get("adrSourceContentHash"),
    )
    if any(value is not None for value in expected_adr + actual_adr):
        if actual_adr != expected_adr:
            raise MaterializeError(f"ADR projection identity drift for {identity}")
    if is_skill:
        for key in (
            "skillProvider",
            "skillName",
            "skillVersion",
            "skillContractHash",
            "skillTriggers",
            "discoveryState",
        ):
            if actual.get(key) != expected.get(key):
                raise MaterializeError(f"required Skill Card {key} drift for {identity}")
        roles = actual.get("skillRoles")
        expected_roles = expected.get("requiredFor")
        if not isinstance(roles, list) or not isinstance(expected_roles, list) or sorted(roles) != sorted(expected_roles):
            raise MaterializeError(f"required Skill Card role policy drift for {identity}")
        if role not in roles:
            raise MaterializeError(f"required Skill Card role policy violation for {identity}: {role} is no longer allowed")
    elif actual.get("constraintStrength") != "hard":
        raise MaterializeError(f"hard Note policy violation for {identity}: runtime Note is no longer hard")
    if not isinstance(actual.get("content"), str) or not actual["content"].strip():
        raise MaterializeError(f"Obsidian Note has no readable content: {identity}")


def _validate_adr_authority(project_root: Path, note: dict[str, Any], identity: str) -> None:
    if not note.get("adrSourceId"):
        return
    try:
        validate_identity(
            project_root,
            note["adrSourceId"],
            note["adrSourcePath"],
            note["adrSourceContentHash"],
        )
    except (AdrIdentityError, KeyError, TypeError) as exc:
        raise MaterializeError(f"ADR projection authority validation failed for {identity}: {exc}") from exc


def _v6_materialize(data: dict[str, Any], task_id: str | None, role: str, project_root: Path, explicit_cmd: str | None) -> list[dict[str, Any]]:
    if not task_id:
        raise MaterializeError("schema-v6 materialization requires --task-id")
    notes, skills = _v6_task_notes(data, task_id, role)
    direct: list[tuple[dict[str, Any], bool]] = [(note, False) for note in notes if note.get("constraintStrength") == "hard"]
    direct.extend((skill, True) for skill in skills)
    if not direct:
        return []
    cmd = _obsidian_cmd(explicit_cmd)
    if not cmd:
        raise MaterializeError("Obsidian Wiki MCP CLI could not be resolved; install the plugin bundle or pass --obsidian-wiki-cmd")
    direct_ids = [str(note["wikiId"]) for note, _ in direct]
    read = _invoke_obsidian_cli(cmd, project_root, {"wikiIds": direct_ids}, "read-notes-by-wiki-ids")
    direct_snapshot = read.get("snapshotHash")
    if not isinstance(direct_snapshot, str) or not direct_snapshot:
        raise MaterializeError("Obsidian Wiki MCP returned no direct Note snapshot hash")
    actual_notes = read.get("notes")
    if not isinstance(actual_notes, list) or len(actual_notes) != len(direct_ids):
        raise MaterializeError("Obsidian Wiki MCP returned partial Note results")
    by_id: dict[str, dict[str, Any]] = {}
    for actual in actual_notes:
        if not isinstance(actual, dict) or not isinstance(actual.get("wikiId"), str) or actual["wikiId"] in by_id:
            raise MaterializeError("Obsidian Wiki MCP returned duplicate or invalid Note IDs")
        by_id[actual["wikiId"]] = actual
    materialized: list[dict[str, Any]] = []
    for expected, is_skill in direct:
        actual = by_id.get(expected["wikiId"])
        if actual is None:
            raise MaterializeError(f"Obsidian Wiki MCP returned no Note for {expected['wikiId']}")
        _validate_adr_authority(project_root, expected, expected["wikiId"])
        _assert_v6_note_matches(expected, actual, role, is_skill)
        materialized.append(
            {
                "displayPath": actual["path"],
                "sectionId": actual["wikiId"],
                "content": actual["content"],
                "closedVia": None,
                "revision": None,
                "caveats": [],
                "requiredSkill": (
                    {"name": actual["skillName"], "role": role}
                    if is_skill
                    else None
                ),
            }
        )

    hard_note_ids = [str(note["wikiId"]) for note, is_skill in direct if not is_skill]
    closure_ids: list[str] = []
    closed_via: dict[str, str] = {}
    direct_id_set = set(direct_ids)
    if hard_note_ids:
        graph = _invoke_obsidian_cli(cmd, project_root, {"wikiIds": hard_note_ids}, "graph-neighbors")
        neighbors = graph.get("neighbors")
        if not isinstance(neighbors, dict):
            raise MaterializeError("Obsidian Wiki MCP returned invalid graph neighbors")
        for wiki_id in hard_note_ids:
            edges = neighbors.get(wiki_id)
            if not isinstance(edges, list):
                raise MaterializeError(f"Obsidian Wiki MCP returned no graph slice for {wiki_id}")
            for edge in edges:
                if not isinstance(edge, dict) or edge.get("type") != "depends_on":
                    continue
                path = edge.get("path")
                target_id = edge.get("wikiId")
                if not isinstance(path, str) or not path or not isinstance(target_id, str) or not target_id:
                    raise MaterializeError(f"Obsidian Wiki MCP returned invalid depends_on edge for {wiki_id}")
                if target_id not in direct_id_set and target_id not in closed_via:
                    closure_ids.append(target_id)
                    closed_via[target_id] = wiki_id
    if closure_ids:
        closure_read = _invoke_obsidian_cli(cmd, project_root, {"wikiIds": closure_ids}, "read-notes-by-wiki-ids")
        closure_notes = closure_read.get("notes")
        if not isinstance(closure_notes, list) or len(closure_notes) != len(closure_ids):
            raise MaterializeError("Obsidian Wiki MCP returned partial depends_on Note results")
        by_closure_id = {note.get("wikiId"): note for note in closure_notes if isinstance(note, dict) and isinstance(note.get("wikiId"), str)}
        if len(by_closure_id) != len(closure_ids):
            raise MaterializeError("Obsidian Wiki MCP returned duplicate or invalid depends_on Note IDs")
        seen_ids = set(direct_ids)
        for wiki_id in closure_ids:
            actual = by_closure_id.get(wiki_id)
            if actual is None or actual.get("wikiId") in seen_ids:
                raise MaterializeError(f"duplicate or missing depends_on Note for {wiki_id}")
            if not isinstance(actual.get("content"), str) or not actual["content"].strip():
                raise MaterializeError(f"depends_on Note policy violation for {wiki_id}")
            _validate_adr_authority(project_root, actual, wiki_id)
            seen_ids.add(str(actual["wikiId"]))
            materialized.append({"displayPath": actual["path"], "sectionId": actual["wikiId"], "content": actual["content"], "closedVia": closed_via[wiki_id], "revision": None, "caveats": []})
    if hard_note_ids:
        verified_graph = _invoke_obsidian_cli(cmd, project_root, {"wikiIds": hard_note_ids}, "graph-neighbors")
        if verified_graph.get("neighbors") != graph.get("neighbors"):
            raise MaterializeError("Obsidian Wiki dependency graph drifted during materialization")
        verified_read = _invoke_obsidian_cli(cmd, project_root, {"wikiIds": direct_ids}, "read-notes-by-wiki-ids")
        if verified_read.get("snapshotHash") != direct_snapshot:
            raise MaterializeError("Obsidian Wiki direct Note snapshot drifted during materialization")
        verified_notes = verified_read.get("notes")
        if not isinstance(verified_notes, list) or len(verified_notes) != len(direct_ids):
            raise MaterializeError("Obsidian Wiki MCP returned partial verification Note results")
        verified_by_id = {note.get("wikiId"): note for note in verified_notes if isinstance(note, dict) and isinstance(note.get("wikiId"), str)}
        if len(verified_by_id) != len(direct_ids):
            raise MaterializeError("Obsidian Wiki MCP returned duplicate or invalid verification Note IDs")
        for expected, is_skill in direct:
            verified = verified_by_id.get(expected["wikiId"])
            if verified is None:
                raise MaterializeError(f"Obsidian Wiki MCP returned no verification Note for {expected['wikiId']}")
            _assert_v6_note_matches(expected, verified, role, is_skill)
    return materialized


def _append(path: Path, block: str) -> None:
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    if existing and not existing.endswith("\n"):
        existing += "\n"
    text = (existing + "\n" if existing else "") + block
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def main() -> int:
    _configure_stdio()
    parser = argparse.ArgumentParser(description="Materialize a task's hard-constraint full-section rereads (local + github_mcp).")
    parser.add_argument("context_path", help="Path to the .wiki-context.json sidecar")
    parser.add_argument("--task-id", help="Render only rereads bound to this finalized plan task id")
    parser.add_argument("--role", choices=["implementer", "reviewer"], default="implementer")
    parser.add_argument("--project-root", default=None, help="Project root (auto-detected if omitted)")
    parser.add_argument("--append-to", default=None, help="Append the rendered rereads to this file instead of stdout")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--execution-ready", action="store_true", help="Require confirmed taskRouting and per-section destination routing")
    parser.add_argument("--shared-wiki-cmd", default=None, help="Base command for the shared-wiki MCP CLI (POSIX-split); the 'read-sections' / 'graph-neighbors' subcommand is appended. Overrides SHARED_WIKI_MCP_CMD and registration discovery")
    parser.add_argument("--obsidian-wiki-cmd", default=None, help="Base command for the Obsidian Wiki MCP CLI (POSIX-split); read-notes and graph-neighbors are appended. Overrides OBSIDIAN_WIKI_MCP_CMD")
    parser.add_argument("--allow-revision-drift", action="store_true", help="Downgrade shared-wiki revision drift from a hard stop to an appended caveat")
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve() if args.project_root else repo_root(Path.cwd())

    try:
        data = _load_context(Path(args.context_path))
        _validate_context(data, args.strict, args.execution_ready, project_root)
        if data.get("schemaVersion") == 6:
            materialized = _v6_materialize(data, args.task_id, args.role, project_root, args.obsidian_wiki_cmd)
            if not materialized:
                scope = f"task `{args.task_id}`" if args.task_id else "selected wiki context"
                print(f"no hard-constraint rereads for {scope}", file=sys.stderr)
                return 0
            block = _render_rereads(materialized)
            if args.append_to:
                _append(Path(args.append_to), block)
                print(f"materialized {len(materialized)} Obsidian hard-constraint reread(s) -> {args.append_to}", file=sys.stderr)
            else:
                sys.stdout.write(block)
            return 0
        entries = reread_entries(data, args.role, args.task_id)
    except (ValidationError, MaterializeError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    if not entries:
        scope = f"task `{args.task_id}`" if args.task_id else "selected wiki context"
        print(f"no hard-constraint rereads for {scope}", file=sys.stderr)
        return 0

    mcp_entries = [entry for entry in entries if _entry_source(entry) == MCP_SOURCE]
    closure_added = 0
    closure_skipped = 0

    try:
        mcp_map: dict[tuple[str, str], dict[str, Any]] = {}
        if mcp_entries:
            cmd = _resolve_shared_wiki_cmd(args.shared_wiki_cmd, project_root)
            if not cmd:
                raise MaterializeError(
                    f"{len(mcp_entries)} github_mcp hard-constraint section(s) require the shared-wiki MCP "
                    "CLI, but it could not be resolved. The server ships inside the grill-adapter "
                    "plugin, so this normally means a broken install (no mcp/shared-wiki/dist/index.js "
                    "next to these scripts). Otherwise register a shared-wiki MCP server, pass "
                    "--shared-wiki-cmd, or set SHARED_WIKI_MCP_CMD."
                )
            # Close each selected github_mcp hard section's 1-hop depends-on edges against the
            # remote graph, then materialize the directly-selected + closed sections in one
            # strict batch (same connection, same HEAD as the graph-neighbors call). Closure is
            # additive: a graph-neighbors failure degrades to no closure, never a hard stop.
            closure_entries, closure_skipped, closure_caveat = _github_mcp_closure_entries(mcp_entries, cmd, project_root)
            if closure_caveat:
                print(f"Warning: {closure_caveat}", file=sys.stderr)
            if closure_entries:
                entries.extend(closure_entries)
                mcp_entries.extend(closure_entries)
                closure_added = len(closure_entries)
            mcp_map = _materialize_mcp(mcp_entries, data, project_root, cmd, args.allow_revision_drift)

        materialized: list[dict[str, Any]] = []
        for entry in entries:
            if _entry_source(entry) == MCP_SOURCE:
                key = (_eff(entry, "wikiPath") or entry.get("displayPath"), _eff(entry, "sectionId"))
                materialized.append(mcp_map[key])
            else:
                materialized.append(_materialize_local(entry, project_root))
    except MaterializeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    block = _render_rereads(materialized)
    closure_suffix = ""
    if closure_added:
        closure_suffix += f" (+{closure_added} via depends-on closure)"
    if closure_skipped:
        closure_suffix += f"; {closure_skipped} unindexed depends-on target(s) skipped"
    if args.append_to:
        _append(Path(args.append_to), block)
        print(f"materialized {len(materialized)} hard-constraint reread(s){closure_suffix} -> {args.append_to}", file=sys.stderr)
    else:
        if closure_suffix:
            print(f"materialized {len(materialized)} hard-constraint reread(s){closure_suffix}", file=sys.stderr)
        sys.stdout.write(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
